// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_kernel_store_stats_fp32 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_l_0_AWVALID,
        m_axi_gmem_l_0_AWREADY,
        m_axi_gmem_l_0_AWADDR,
        m_axi_gmem_l_0_AWID,
        m_axi_gmem_l_0_AWLEN,
        m_axi_gmem_l_0_AWSIZE,
        m_axi_gmem_l_0_AWBURST,
        m_axi_gmem_l_0_AWLOCK,
        m_axi_gmem_l_0_AWCACHE,
        m_axi_gmem_l_0_AWPROT,
        m_axi_gmem_l_0_AWQOS,
        m_axi_gmem_l_0_AWREGION,
        m_axi_gmem_l_0_AWUSER,
        m_axi_gmem_l_0_WVALID,
        m_axi_gmem_l_0_WREADY,
        m_axi_gmem_l_0_WDATA,
        m_axi_gmem_l_0_WSTRB,
        m_axi_gmem_l_0_WLAST,
        m_axi_gmem_l_0_WID,
        m_axi_gmem_l_0_WUSER,
        m_axi_gmem_l_0_ARVALID,
        m_axi_gmem_l_0_ARREADY,
        m_axi_gmem_l_0_ARADDR,
        m_axi_gmem_l_0_ARID,
        m_axi_gmem_l_0_ARLEN,
        m_axi_gmem_l_0_ARSIZE,
        m_axi_gmem_l_0_ARBURST,
        m_axi_gmem_l_0_ARLOCK,
        m_axi_gmem_l_0_ARCACHE,
        m_axi_gmem_l_0_ARPROT,
        m_axi_gmem_l_0_ARQOS,
        m_axi_gmem_l_0_ARREGION,
        m_axi_gmem_l_0_ARUSER,
        m_axi_gmem_l_0_RVALID,
        m_axi_gmem_l_0_RREADY,
        m_axi_gmem_l_0_RDATA,
        m_axi_gmem_l_0_RLAST,
        m_axi_gmem_l_0_RID,
        m_axi_gmem_l_0_RFIFONUM,
        m_axi_gmem_l_0_RUSER,
        m_axi_gmem_l_0_RRESP,
        m_axi_gmem_l_0_BVALID,
        m_axi_gmem_l_0_BREADY,
        m_axi_gmem_l_0_BRESP,
        m_axi_gmem_l_0_BID,
        m_axi_gmem_l_0_BUSER,
        hbm_port,
        stats_0_val,
        stats_1_val,
        stats_2_val,
        stats_3_val,
        stats_4_val,
        stats_5_val,
        stats_6_val,
        stats_7_val,
        stats_8_val,
        stats_9_val,
        stats_10_val,
        stats_11_val,
        stats_12_val,
        stats_13_val,
        stats_14_val,
        stats_15_val,
        stats_16_val,
        stats_17_val,
        stats_18_val,
        stats_19_val,
        stats_20_val,
        stats_21_val,
        stats_22_val,
        stats_23_val,
        stats_24_val,
        stats_25_val,
        stats_26_val,
        stats_27_val,
        stats_28_val,
        stats_29_val,
        stats_30_val,
        stats_31_val,
        stats_32_val,
        stats_33_val,
        stats_34_val,
        stats_35_val,
        stats_36_val,
        stats_37_val,
        stats_38_val,
        stats_39_val,
        stats_40_val,
        stats_41_val,
        stats_42_val,
        stats_43_val,
        stats_44_val,
        stats_45_val,
        stats_46_val,
        stats_47_val,
        stats_48_val,
        stats_49_val,
        stats_50_val,
        stats_51_val,
        stats_52_val,
        stats_53_val,
        stats_54_val,
        stats_55_val,
        stats_56_val,
        stats_57_val,
        stats_58_val,
        stats_59_val,
        stats_60_val,
        stats_61_val,
        stats_62_val,
        stats_63_val,
        base_idx,
        num_elements
);

parameter    ap_ST_fsm_state1 = 77'd1;
parameter    ap_ST_fsm_state2 = 77'd2;
parameter    ap_ST_fsm_state3 = 77'd4;
parameter    ap_ST_fsm_state4 = 77'd8;
parameter    ap_ST_fsm_state5 = 77'd16;
parameter    ap_ST_fsm_state6 = 77'd32;
parameter    ap_ST_fsm_state7 = 77'd64;
parameter    ap_ST_fsm_state8 = 77'd128;
parameter    ap_ST_fsm_state9 = 77'd256;
parameter    ap_ST_fsm_state10 = 77'd512;
parameter    ap_ST_fsm_state11 = 77'd1024;
parameter    ap_ST_fsm_state12 = 77'd2048;
parameter    ap_ST_fsm_state13 = 77'd4096;
parameter    ap_ST_fsm_state14 = 77'd8192;
parameter    ap_ST_fsm_state15 = 77'd16384;
parameter    ap_ST_fsm_state16 = 77'd32768;
parameter    ap_ST_fsm_state17 = 77'd65536;
parameter    ap_ST_fsm_state18 = 77'd131072;
parameter    ap_ST_fsm_state19 = 77'd262144;
parameter    ap_ST_fsm_state20 = 77'd524288;
parameter    ap_ST_fsm_state21 = 77'd1048576;
parameter    ap_ST_fsm_state22 = 77'd2097152;
parameter    ap_ST_fsm_state23 = 77'd4194304;
parameter    ap_ST_fsm_state24 = 77'd8388608;
parameter    ap_ST_fsm_state25 = 77'd16777216;
parameter    ap_ST_fsm_state26 = 77'd33554432;
parameter    ap_ST_fsm_state27 = 77'd67108864;
parameter    ap_ST_fsm_state28 = 77'd134217728;
parameter    ap_ST_fsm_state29 = 77'd268435456;
parameter    ap_ST_fsm_state30 = 77'd536870912;
parameter    ap_ST_fsm_state31 = 77'd1073741824;
parameter    ap_ST_fsm_state32 = 77'd2147483648;
parameter    ap_ST_fsm_state33 = 77'd4294967296;
parameter    ap_ST_fsm_state34 = 77'd8589934592;
parameter    ap_ST_fsm_state35 = 77'd17179869184;
parameter    ap_ST_fsm_state36 = 77'd34359738368;
parameter    ap_ST_fsm_state37 = 77'd68719476736;
parameter    ap_ST_fsm_state38 = 77'd137438953472;
parameter    ap_ST_fsm_state39 = 77'd274877906944;
parameter    ap_ST_fsm_state40 = 77'd549755813888;
parameter    ap_ST_fsm_state41 = 77'd1099511627776;
parameter    ap_ST_fsm_state42 = 77'd2199023255552;
parameter    ap_ST_fsm_state43 = 77'd4398046511104;
parameter    ap_ST_fsm_state44 = 77'd8796093022208;
parameter    ap_ST_fsm_state45 = 77'd17592186044416;
parameter    ap_ST_fsm_state46 = 77'd35184372088832;
parameter    ap_ST_fsm_state47 = 77'd70368744177664;
parameter    ap_ST_fsm_state48 = 77'd140737488355328;
parameter    ap_ST_fsm_state49 = 77'd281474976710656;
parameter    ap_ST_fsm_state50 = 77'd562949953421312;
parameter    ap_ST_fsm_state51 = 77'd1125899906842624;
parameter    ap_ST_fsm_state52 = 77'd2251799813685248;
parameter    ap_ST_fsm_state53 = 77'd4503599627370496;
parameter    ap_ST_fsm_state54 = 77'd9007199254740992;
parameter    ap_ST_fsm_state55 = 77'd18014398509481984;
parameter    ap_ST_fsm_state56 = 77'd36028797018963968;
parameter    ap_ST_fsm_state57 = 77'd72057594037927936;
parameter    ap_ST_fsm_state58 = 77'd144115188075855872;
parameter    ap_ST_fsm_state59 = 77'd288230376151711744;
parameter    ap_ST_fsm_state60 = 77'd576460752303423488;
parameter    ap_ST_fsm_state61 = 77'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 77'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 77'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 77'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 77'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 77'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 77'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 77'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 77'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 77'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 77'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 77'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 77'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 77'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 77'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 77'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 77'd75557863725914323419136;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_l_0_AWVALID;
input   m_axi_gmem_l_0_AWREADY;
output  [63:0] m_axi_gmem_l_0_AWADDR;
output  [0:0] m_axi_gmem_l_0_AWID;
output  [31:0] m_axi_gmem_l_0_AWLEN;
output  [2:0] m_axi_gmem_l_0_AWSIZE;
output  [1:0] m_axi_gmem_l_0_AWBURST;
output  [1:0] m_axi_gmem_l_0_AWLOCK;
output  [3:0] m_axi_gmem_l_0_AWCACHE;
output  [2:0] m_axi_gmem_l_0_AWPROT;
output  [3:0] m_axi_gmem_l_0_AWQOS;
output  [3:0] m_axi_gmem_l_0_AWREGION;
output  [0:0] m_axi_gmem_l_0_AWUSER;
output   m_axi_gmem_l_0_WVALID;
input   m_axi_gmem_l_0_WREADY;
output  [511:0] m_axi_gmem_l_0_WDATA;
output  [63:0] m_axi_gmem_l_0_WSTRB;
output   m_axi_gmem_l_0_WLAST;
output  [0:0] m_axi_gmem_l_0_WID;
output  [0:0] m_axi_gmem_l_0_WUSER;
output   m_axi_gmem_l_0_ARVALID;
input   m_axi_gmem_l_0_ARREADY;
output  [63:0] m_axi_gmem_l_0_ARADDR;
output  [0:0] m_axi_gmem_l_0_ARID;
output  [31:0] m_axi_gmem_l_0_ARLEN;
output  [2:0] m_axi_gmem_l_0_ARSIZE;
output  [1:0] m_axi_gmem_l_0_ARBURST;
output  [1:0] m_axi_gmem_l_0_ARLOCK;
output  [3:0] m_axi_gmem_l_0_ARCACHE;
output  [2:0] m_axi_gmem_l_0_ARPROT;
output  [3:0] m_axi_gmem_l_0_ARQOS;
output  [3:0] m_axi_gmem_l_0_ARREGION;
output  [0:0] m_axi_gmem_l_0_ARUSER;
input   m_axi_gmem_l_0_RVALID;
output   m_axi_gmem_l_0_RREADY;
input  [511:0] m_axi_gmem_l_0_RDATA;
input   m_axi_gmem_l_0_RLAST;
input  [0:0] m_axi_gmem_l_0_RID;
input  [8:0] m_axi_gmem_l_0_RFIFONUM;
input  [0:0] m_axi_gmem_l_0_RUSER;
input  [1:0] m_axi_gmem_l_0_RRESP;
input   m_axi_gmem_l_0_BVALID;
output   m_axi_gmem_l_0_BREADY;
input  [1:0] m_axi_gmem_l_0_BRESP;
input  [0:0] m_axi_gmem_l_0_BID;
input  [0:0] m_axi_gmem_l_0_BUSER;
input  [63:0] hbm_port;
input  [31:0] stats_0_val;
input  [31:0] stats_1_val;
input  [31:0] stats_2_val;
input  [31:0] stats_3_val;
input  [31:0] stats_4_val;
input  [31:0] stats_5_val;
input  [31:0] stats_6_val;
input  [31:0] stats_7_val;
input  [31:0] stats_8_val;
input  [31:0] stats_9_val;
input  [31:0] stats_10_val;
input  [31:0] stats_11_val;
input  [31:0] stats_12_val;
input  [31:0] stats_13_val;
input  [31:0] stats_14_val;
input  [31:0] stats_15_val;
input  [31:0] stats_16_val;
input  [31:0] stats_17_val;
input  [31:0] stats_18_val;
input  [31:0] stats_19_val;
input  [31:0] stats_20_val;
input  [31:0] stats_21_val;
input  [31:0] stats_22_val;
input  [31:0] stats_23_val;
input  [31:0] stats_24_val;
input  [31:0] stats_25_val;
input  [31:0] stats_26_val;
input  [31:0] stats_27_val;
input  [31:0] stats_28_val;
input  [31:0] stats_29_val;
input  [31:0] stats_30_val;
input  [31:0] stats_31_val;
input  [31:0] stats_32_val;
input  [31:0] stats_33_val;
input  [31:0] stats_34_val;
input  [31:0] stats_35_val;
input  [31:0] stats_36_val;
input  [31:0] stats_37_val;
input  [31:0] stats_38_val;
input  [31:0] stats_39_val;
input  [31:0] stats_40_val;
input  [31:0] stats_41_val;
input  [31:0] stats_42_val;
input  [31:0] stats_43_val;
input  [31:0] stats_44_val;
input  [31:0] stats_45_val;
input  [31:0] stats_46_val;
input  [31:0] stats_47_val;
input  [31:0] stats_48_val;
input  [31:0] stats_49_val;
input  [31:0] stats_50_val;
input  [31:0] stats_51_val;
input  [31:0] stats_52_val;
input  [31:0] stats_53_val;
input  [31:0] stats_54_val;
input  [31:0] stats_55_val;
input  [31:0] stats_56_val;
input  [31:0] stats_57_val;
input  [31:0] stats_58_val;
input  [31:0] stats_59_val;
input  [31:0] stats_60_val;
input  [31:0] stats_61_val;
input  [31:0] stats_62_val;
input  [31:0] stats_63_val;
input  [30:0] base_idx;
input  [31:0] num_elements;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_l_0_AWVALID;
reg[63:0] m_axi_gmem_l_0_AWADDR;
reg[0:0] m_axi_gmem_l_0_AWID;
reg[31:0] m_axi_gmem_l_0_AWLEN;
reg[2:0] m_axi_gmem_l_0_AWSIZE;
reg[1:0] m_axi_gmem_l_0_AWBURST;
reg[1:0] m_axi_gmem_l_0_AWLOCK;
reg[3:0] m_axi_gmem_l_0_AWCACHE;
reg[2:0] m_axi_gmem_l_0_AWPROT;
reg[3:0] m_axi_gmem_l_0_AWQOS;
reg[3:0] m_axi_gmem_l_0_AWREGION;
reg[0:0] m_axi_gmem_l_0_AWUSER;
reg m_axi_gmem_l_0_WVALID;
reg m_axi_gmem_l_0_BREADY;

(* fsm_encoding = "none" *) reg   [76:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem_l_blk_n_AW;
reg    gmem_l_blk_n_B;
wire    ap_CS_fsm_state77;
wire   [28:0] total_beats_fu_802_p3;
reg   [28:0] total_beats_reg_897;
wire  signed [57:0] trunc_ln3_fu_844_p4;
reg   [57:0] trunc_ln3_reg_902;
wire    ap_CS_fsm_state2;
wire    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_start;
wire    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_done;
wire    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_idle;
wire    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_ready;
wire    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWVALID;
wire   [63:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWADDR;
wire   [0:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWID;
wire   [31:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWLEN;
wire   [2:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWSIZE;
wire   [1:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWBURST;
wire   [1:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWLOCK;
wire   [3:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWCACHE;
wire   [2:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWPROT;
wire   [3:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWQOS;
wire   [3:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWREGION;
wire   [0:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWUSER;
wire    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WVALID;
wire   [511:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WDATA;
wire   [63:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WSTRB;
wire    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WLAST;
wire   [0:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WID;
wire   [0:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WUSER;
wire    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARVALID;
wire   [63:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARADDR;
wire   [0:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARID;
wire   [31:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARLEN;
wire   [2:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARSIZE;
wire   [1:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARBURST;
wire   [1:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARLOCK;
wire   [3:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARCACHE;
wire   [2:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARPROT;
wire   [3:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARQOS;
wire   [3:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARREGION;
wire   [0:0] grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARUSER;
wire    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_RREADY;
wire    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_BREADY;
reg    grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_start_reg;
wire    ap_CS_fsm_state3;
wire  signed [63:0] sext_ln272_fu_854_p1;
wire   [63:0] zext_ln272_1_fu_877_p1;
wire   [31:0] add_ln268_fu_748_p2;
wire   [31:0] sub_ln268_fu_762_p2;
wire   [27:0] tmp_15_fu_768_p4;
wire   [28:0] zext_ln268_fu_778_p1;
wire   [27:0] tmp_s_fu_788_p4;
wire   [0:0] tmp_fu_754_p3;
wire   [28:0] sub_ln268_1_fu_782_p2;
wire   [28:0] zext_ln268_1_fu_798_p1;
wire   [26:0] tmp_1_fu_816_p4;
wire   [32:0] tmp_2_fu_826_p3;
wire   [63:0] zext_ln272_fu_834_p1;
wire   [63:0] add_ln272_fu_838_p2;
wire   [0:0] icmp_ln272_fu_810_p2;
wire   [28:0] empty_fu_865_p3;
wire  signed [31:0] sext_ln272_1_fu_873_p1;
reg   [76:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
reg    ap_ST_fsm_state77_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 77'd1;
#0 grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_start_reg = 1'b0;
end

flash_attention_kernel_store_stats_fp32_Pipeline_STORE_STATS grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_start),
    .ap_done(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_done),
    .ap_idle(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_idle),
    .ap_ready(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_ready),
    .m_axi_gmem_l_0_AWVALID(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWVALID),
    .m_axi_gmem_l_0_AWREADY(m_axi_gmem_l_0_AWREADY),
    .m_axi_gmem_l_0_AWADDR(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWADDR),
    .m_axi_gmem_l_0_AWID(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWID),
    .m_axi_gmem_l_0_AWLEN(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWLEN),
    .m_axi_gmem_l_0_AWSIZE(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWSIZE),
    .m_axi_gmem_l_0_AWBURST(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWBURST),
    .m_axi_gmem_l_0_AWLOCK(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWLOCK),
    .m_axi_gmem_l_0_AWCACHE(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWCACHE),
    .m_axi_gmem_l_0_AWPROT(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWPROT),
    .m_axi_gmem_l_0_AWQOS(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWQOS),
    .m_axi_gmem_l_0_AWREGION(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWREGION),
    .m_axi_gmem_l_0_AWUSER(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWUSER),
    .m_axi_gmem_l_0_WVALID(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WVALID),
    .m_axi_gmem_l_0_WREADY(m_axi_gmem_l_0_WREADY),
    .m_axi_gmem_l_0_WDATA(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WDATA),
    .m_axi_gmem_l_0_WSTRB(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WSTRB),
    .m_axi_gmem_l_0_WLAST(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WLAST),
    .m_axi_gmem_l_0_WID(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WID),
    .m_axi_gmem_l_0_WUSER(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WUSER),
    .m_axi_gmem_l_0_ARVALID(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARVALID),
    .m_axi_gmem_l_0_ARREADY(1'b0),
    .m_axi_gmem_l_0_ARADDR(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARADDR),
    .m_axi_gmem_l_0_ARID(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARID),
    .m_axi_gmem_l_0_ARLEN(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARLEN),
    .m_axi_gmem_l_0_ARSIZE(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARSIZE),
    .m_axi_gmem_l_0_ARBURST(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARBURST),
    .m_axi_gmem_l_0_ARLOCK(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARLOCK),
    .m_axi_gmem_l_0_ARCACHE(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARCACHE),
    .m_axi_gmem_l_0_ARPROT(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARPROT),
    .m_axi_gmem_l_0_ARQOS(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARQOS),
    .m_axi_gmem_l_0_ARREGION(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARREGION),
    .m_axi_gmem_l_0_ARUSER(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_ARUSER),
    .m_axi_gmem_l_0_RVALID(1'b0),
    .m_axi_gmem_l_0_RREADY(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_RREADY),
    .m_axi_gmem_l_0_RDATA(512'd0),
    .m_axi_gmem_l_0_RLAST(1'b0),
    .m_axi_gmem_l_0_RID(1'd0),
    .m_axi_gmem_l_0_RFIFONUM(9'd0),
    .m_axi_gmem_l_0_RUSER(1'd0),
    .m_axi_gmem_l_0_RRESP(2'd0),
    .m_axi_gmem_l_0_BVALID(m_axi_gmem_l_0_BVALID),
    .m_axi_gmem_l_0_BREADY(grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_BREADY),
    .m_axi_gmem_l_0_BRESP(m_axi_gmem_l_0_BRESP),
    .m_axi_gmem_l_0_BID(m_axi_gmem_l_0_BID),
    .m_axi_gmem_l_0_BUSER(m_axi_gmem_l_0_BUSER),
    .num_elements(num_elements),
    .total_beats(total_beats_reg_897),
    .sext_ln272(trunc_ln3_reg_902),
    .stats_0_val(stats_0_val),
    .stats_16_val(stats_16_val),
    .stats_32_val(stats_32_val),
    .stats_48_val(stats_48_val),
    .stats_1_val(stats_1_val),
    .stats_17_val(stats_17_val),
    .stats_33_val(stats_33_val),
    .stats_49_val(stats_49_val),
    .stats_2_val(stats_2_val),
    .stats_18_val(stats_18_val),
    .stats_34_val(stats_34_val),
    .stats_50_val(stats_50_val),
    .stats_3_val(stats_3_val),
    .stats_19_val(stats_19_val),
    .stats_35_val(stats_35_val),
    .stats_51_val(stats_51_val),
    .stats_4_val(stats_4_val),
    .stats_20_val(stats_20_val),
    .stats_36_val(stats_36_val),
    .stats_52_val(stats_52_val),
    .stats_5_val(stats_5_val),
    .stats_21_val(stats_21_val),
    .stats_37_val(stats_37_val),
    .stats_53_val(stats_53_val),
    .stats_6_val(stats_6_val),
    .stats_22_val(stats_22_val),
    .stats_38_val(stats_38_val),
    .stats_54_val(stats_54_val),
    .stats_7_val(stats_7_val),
    .stats_23_val(stats_23_val),
    .stats_39_val(stats_39_val),
    .stats_55_val(stats_55_val),
    .stats_8_val(stats_8_val),
    .stats_24_val(stats_24_val),
    .stats_40_val(stats_40_val),
    .stats_56_val(stats_56_val),
    .stats_9_val(stats_9_val),
    .stats_25_val(stats_25_val),
    .stats_41_val(stats_41_val),
    .stats_57_val(stats_57_val),
    .stats_10_val(stats_10_val),
    .stats_26_val(stats_26_val),
    .stats_42_val(stats_42_val),
    .stats_58_val(stats_58_val),
    .stats_11_val(stats_11_val),
    .stats_27_val(stats_27_val),
    .stats_43_val(stats_43_val),
    .stats_59_val(stats_59_val),
    .stats_12_val(stats_12_val),
    .stats_28_val(stats_28_val),
    .stats_44_val(stats_44_val),
    .stats_60_val(stats_60_val),
    .stats_13_val(stats_13_val),
    .stats_29_val(stats_29_val),
    .stats_45_val(stats_45_val),
    .stats_61_val(stats_61_val),
    .stats_14_val(stats_14_val),
    .stats_30_val(stats_30_val),
    .stats_46_val(stats_46_val),
    .stats_62_val(stats_62_val),
    .stats_15_val(stats_15_val),
    .stats_31_val(stats_31_val),
    .stats_47_val(stats_47_val),
    .stats_63_val(stats_63_val)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_start_reg <= 1'b1;
        end else if ((grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_ready == 1'b1)) begin
            grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        total_beats_reg_897 <= total_beats_fu_802_p3;
        trunc_ln3_reg_902 <= {{add_ln272_fu_838_p2[63:6]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((ap_start == 1'b0) | (m_axi_gmem_l_0_AWREADY == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_l_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state77_blk = 1'b1;
    end else begin
        ap_ST_fsm_state77_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state77) & (m_axi_gmem_l_0_BVALID == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) & (m_axi_gmem_l_0_BVALID == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        gmem_l_blk_n_AW = m_axi_gmem_l_0_AWREADY;
    end else begin
        gmem_l_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        gmem_l_blk_n_B = m_axi_gmem_l_0_BVALID;
    end else begin
        gmem_l_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (m_axi_gmem_l_0_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_l_0_AWADDR = sext_ln272_fu_854_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWADDR = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWADDR;
    end else begin
        m_axi_gmem_l_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWBURST = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWBURST;
    end else begin
        m_axi_gmem_l_0_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWCACHE = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWCACHE;
    end else begin
        m_axi_gmem_l_0_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWID = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWID;
    end else begin
        m_axi_gmem_l_0_AWID = 1'd0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (m_axi_gmem_l_0_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_l_0_AWLEN = zext_ln272_1_fu_877_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWLEN = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWLEN;
    end else begin
        m_axi_gmem_l_0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWLOCK = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWLOCK;
    end else begin
        m_axi_gmem_l_0_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWPROT = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWPROT;
    end else begin
        m_axi_gmem_l_0_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWQOS = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWQOS;
    end else begin
        m_axi_gmem_l_0_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWREGION = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWREGION;
    end else begin
        m_axi_gmem_l_0_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWSIZE = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWSIZE;
    end else begin
        m_axi_gmem_l_0_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWUSER = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWUSER;
    end else begin
        m_axi_gmem_l_0_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (m_axi_gmem_l_0_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_l_0_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_AWVALID = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_AWVALID;
    end else begin
        m_axi_gmem_l_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) & (m_axi_gmem_l_0_BVALID == 1'b1))) begin
        m_axi_gmem_l_0_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_BREADY = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_BREADY;
    end else begin
        m_axi_gmem_l_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_l_0_WVALID = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WVALID;
    end else begin
        m_axi_gmem_l_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (m_axi_gmem_l_0_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            if (((1'b1 == ap_CS_fsm_state77) & (m_axi_gmem_l_0_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln268_fu_748_p2 = (num_elements + 32'd15);

assign add_ln272_fu_838_p2 = (zext_ln272_fu_834_p1 + hbm_port);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign empty_fu_865_p3 = ((icmp_ln272_fu_810_p2[0:0] == 1'b1) ? total_beats_fu_802_p3 : 29'd0);

assign grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_start = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_ap_start_reg;

assign icmp_ln272_fu_810_p2 = (($signed(num_elements) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign m_axi_gmem_l_0_ARADDR = 64'd0;

assign m_axi_gmem_l_0_ARBURST = 2'd0;

assign m_axi_gmem_l_0_ARCACHE = 4'd0;

assign m_axi_gmem_l_0_ARID = 1'd0;

assign m_axi_gmem_l_0_ARLEN = 32'd0;

assign m_axi_gmem_l_0_ARLOCK = 2'd0;

assign m_axi_gmem_l_0_ARPROT = 3'd0;

assign m_axi_gmem_l_0_ARQOS = 4'd0;

assign m_axi_gmem_l_0_ARREGION = 4'd0;

assign m_axi_gmem_l_0_ARSIZE = 3'd0;

assign m_axi_gmem_l_0_ARUSER = 1'd0;

assign m_axi_gmem_l_0_ARVALID = 1'b0;

assign m_axi_gmem_l_0_RREADY = 1'b0;

assign m_axi_gmem_l_0_WDATA = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WDATA;

assign m_axi_gmem_l_0_WID = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WID;

assign m_axi_gmem_l_0_WLAST = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WLAST;

assign m_axi_gmem_l_0_WSTRB = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WSTRB;

assign m_axi_gmem_l_0_WUSER = grp_store_stats_fp32_Pipeline_STORE_STATS_fu_611_m_axi_gmem_l_0_WUSER;

assign sext_ln272_1_fu_873_p1 = $signed(empty_fu_865_p3);

assign sext_ln272_fu_854_p1 = trunc_ln3_fu_844_p4;

assign sub_ln268_1_fu_782_p2 = (29'd0 - zext_ln268_fu_778_p1);

assign sub_ln268_fu_762_p2 = ($signed(32'd4294967281) - $signed(num_elements));

assign tmp_15_fu_768_p4 = {{sub_ln268_fu_762_p2[31:4]}};

assign tmp_1_fu_816_p4 = {{base_idx[30:4]}};

assign tmp_2_fu_826_p3 = {{tmp_1_fu_816_p4}, {6'd0}};

assign tmp_fu_754_p3 = add_ln268_fu_748_p2[32'd31];

assign tmp_s_fu_788_p4 = {{add_ln268_fu_748_p2[31:4]}};

assign total_beats_fu_802_p3 = ((tmp_fu_754_p3[0:0] == 1'b1) ? sub_ln268_1_fu_782_p2 : zext_ln268_1_fu_798_p1);

assign trunc_ln3_fu_844_p4 = {{add_ln272_fu_838_p2[63:6]}};

assign zext_ln268_1_fu_798_p1 = tmp_s_fu_788_p4;

assign zext_ln268_fu_778_p1 = tmp_15_fu_768_p4;

assign zext_ln272_1_fu_877_p1 = $unsigned(sext_ln272_1_fu_873_p1);

assign zext_ln272_fu_834_p1 = tmp_2_fu_826_p3;

endmodule //flash_attention_kernel_store_stats_fp32
