// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_kernel_gemm_pv_Pipeline_GEMM_PV_RED_GEMM_PV_DCOL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i,
        P_tile_0_address0,
        P_tile_0_ce0,
        P_tile_0_q0,
        P_tile_1_address0,
        P_tile_1_ce0,
        P_tile_1_q0,
        P_tile_2_address0,
        P_tile_2_ce0,
        P_tile_2_q0,
        P_tile_3_address0,
        P_tile_3_ce0,
        P_tile_3_q0,
        P_tile_4_address0,
        P_tile_4_ce0,
        P_tile_4_q0,
        P_tile_5_address0,
        P_tile_5_ce0,
        P_tile_5_q0,
        P_tile_6_address0,
        P_tile_6_ce0,
        P_tile_6_q0,
        P_tile_7_address0,
        P_tile_7_ce0,
        P_tile_7_q0,
        bc_actual,
        cmp9,
        V_tile_0_address0,
        V_tile_0_ce0,
        V_tile_0_q0,
        V_tile_1_address0,
        V_tile_1_ce0,
        V_tile_1_q0,
        V_tile_2_address0,
        V_tile_2_ce0,
        V_tile_2_q0,
        V_tile_3_address0,
        V_tile_3_ce0,
        V_tile_3_q0,
        V_tile_4_address0,
        V_tile_4_ce0,
        V_tile_4_q0,
        V_tile_5_address0,
        V_tile_5_ce0,
        V_tile_5_q0,
        V_tile_6_address0,
        V_tile_6_ce0,
        V_tile_6_q0,
        V_tile_7_address0,
        V_tile_7_ce0,
        V_tile_7_q0,
        V_tile_8_address0,
        V_tile_8_ce0,
        V_tile_8_q0,
        V_tile_9_address0,
        V_tile_9_ce0,
        V_tile_9_q0,
        V_tile_10_address0,
        V_tile_10_ce0,
        V_tile_10_q0,
        V_tile_11_address0,
        V_tile_11_ce0,
        V_tile_11_q0,
        V_tile_12_address0,
        V_tile_12_ce0,
        V_tile_12_q0,
        V_tile_13_address0,
        V_tile_13_ce0,
        V_tile_13_q0,
        V_tile_14_address0,
        V_tile_14_ce0,
        V_tile_14_q0,
        V_tile_15_address0,
        V_tile_15_ce0,
        V_tile_15_q0,
        acc_d_15_address0,
        acc_d_15_ce0,
        acc_d_15_we0,
        acc_d_15_d0,
        acc_d_15_address1,
        acc_d_15_ce1,
        acc_d_15_q1,
        acc_d_14_address0,
        acc_d_14_ce0,
        acc_d_14_we0,
        acc_d_14_d0,
        acc_d_14_address1,
        acc_d_14_ce1,
        acc_d_14_q1,
        acc_d_13_address0,
        acc_d_13_ce0,
        acc_d_13_we0,
        acc_d_13_d0,
        acc_d_13_address1,
        acc_d_13_ce1,
        acc_d_13_q1,
        acc_d_12_address0,
        acc_d_12_ce0,
        acc_d_12_we0,
        acc_d_12_d0,
        acc_d_12_address1,
        acc_d_12_ce1,
        acc_d_12_q1,
        acc_d_11_address0,
        acc_d_11_ce0,
        acc_d_11_we0,
        acc_d_11_d0,
        acc_d_11_address1,
        acc_d_11_ce1,
        acc_d_11_q1,
        acc_d_10_address0,
        acc_d_10_ce0,
        acc_d_10_we0,
        acc_d_10_d0,
        acc_d_10_address1,
        acc_d_10_ce1,
        acc_d_10_q1,
        acc_d_9_address0,
        acc_d_9_ce0,
        acc_d_9_we0,
        acc_d_9_d0,
        acc_d_9_address1,
        acc_d_9_ce1,
        acc_d_9_q1,
        acc_d_8_address0,
        acc_d_8_ce0,
        acc_d_8_we0,
        acc_d_8_d0,
        acc_d_8_address1,
        acc_d_8_ce1,
        acc_d_8_q1,
        acc_d_7_address0,
        acc_d_7_ce0,
        acc_d_7_we0,
        acc_d_7_d0,
        acc_d_7_address1,
        acc_d_7_ce1,
        acc_d_7_q1,
        acc_d_6_address0,
        acc_d_6_ce0,
        acc_d_6_we0,
        acc_d_6_d0,
        acc_d_6_address1,
        acc_d_6_ce1,
        acc_d_6_q1,
        acc_d_5_address0,
        acc_d_5_ce0,
        acc_d_5_we0,
        acc_d_5_d0,
        acc_d_5_address1,
        acc_d_5_ce1,
        acc_d_5_q1,
        acc_d_4_address0,
        acc_d_4_ce0,
        acc_d_4_we0,
        acc_d_4_d0,
        acc_d_4_address1,
        acc_d_4_ce1,
        acc_d_4_q1,
        acc_d_3_address0,
        acc_d_3_ce0,
        acc_d_3_we0,
        acc_d_3_d0,
        acc_d_3_address1,
        acc_d_3_ce1,
        acc_d_3_q1,
        acc_d_2_address0,
        acc_d_2_ce0,
        acc_d_2_we0,
        acc_d_2_d0,
        acc_d_2_address1,
        acc_d_2_ce1,
        acc_d_2_q1,
        acc_d_1_address0,
        acc_d_1_ce0,
        acc_d_1_we0,
        acc_d_1_d0,
        acc_d_1_address1,
        acc_d_1_ce1,
        acc_d_1_q1,
        acc_d_address0,
        acc_d_ce0,
        acc_d_we0,
        acc_d_d0,
        acc_d_address1,
        acc_d_ce1,
        acc_d_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] i;
output  [8:0] P_tile_0_address0;
output   P_tile_0_ce0;
input  [15:0] P_tile_0_q0;
output  [8:0] P_tile_1_address0;
output   P_tile_1_ce0;
input  [15:0] P_tile_1_q0;
output  [8:0] P_tile_2_address0;
output   P_tile_2_ce0;
input  [15:0] P_tile_2_q0;
output  [8:0] P_tile_3_address0;
output   P_tile_3_ce0;
input  [15:0] P_tile_3_q0;
output  [8:0] P_tile_4_address0;
output   P_tile_4_ce0;
input  [15:0] P_tile_4_q0;
output  [8:0] P_tile_5_address0;
output   P_tile_5_ce0;
input  [15:0] P_tile_5_q0;
output  [8:0] P_tile_6_address0;
output   P_tile_6_ce0;
input  [15:0] P_tile_6_q0;
output  [8:0] P_tile_7_address0;
output   P_tile_7_ce0;
input  [15:0] P_tile_7_q0;
input  [31:0] bc_actual;
input  [0:0] cmp9;
output  [8:0] V_tile_0_address0;
output   V_tile_0_ce0;
input  [15:0] V_tile_0_q0;
output  [8:0] V_tile_1_address0;
output   V_tile_1_ce0;
input  [15:0] V_tile_1_q0;
output  [8:0] V_tile_2_address0;
output   V_tile_2_ce0;
input  [15:0] V_tile_2_q0;
output  [8:0] V_tile_3_address0;
output   V_tile_3_ce0;
input  [15:0] V_tile_3_q0;
output  [8:0] V_tile_4_address0;
output   V_tile_4_ce0;
input  [15:0] V_tile_4_q0;
output  [8:0] V_tile_5_address0;
output   V_tile_5_ce0;
input  [15:0] V_tile_5_q0;
output  [8:0] V_tile_6_address0;
output   V_tile_6_ce0;
input  [15:0] V_tile_6_q0;
output  [8:0] V_tile_7_address0;
output   V_tile_7_ce0;
input  [15:0] V_tile_7_q0;
output  [8:0] V_tile_8_address0;
output   V_tile_8_ce0;
input  [15:0] V_tile_8_q0;
output  [8:0] V_tile_9_address0;
output   V_tile_9_ce0;
input  [15:0] V_tile_9_q0;
output  [8:0] V_tile_10_address0;
output   V_tile_10_ce0;
input  [15:0] V_tile_10_q0;
output  [8:0] V_tile_11_address0;
output   V_tile_11_ce0;
input  [15:0] V_tile_11_q0;
output  [8:0] V_tile_12_address0;
output   V_tile_12_ce0;
input  [15:0] V_tile_12_q0;
output  [8:0] V_tile_13_address0;
output   V_tile_13_ce0;
input  [15:0] V_tile_13_q0;
output  [8:0] V_tile_14_address0;
output   V_tile_14_ce0;
input  [15:0] V_tile_14_q0;
output  [8:0] V_tile_15_address0;
output   V_tile_15_ce0;
input  [15:0] V_tile_15_q0;
output  [2:0] acc_d_15_address0;
output   acc_d_15_ce0;
output   acc_d_15_we0;
output  [31:0] acc_d_15_d0;
output  [2:0] acc_d_15_address1;
output   acc_d_15_ce1;
input  [31:0] acc_d_15_q1;
output  [2:0] acc_d_14_address0;
output   acc_d_14_ce0;
output   acc_d_14_we0;
output  [31:0] acc_d_14_d0;
output  [2:0] acc_d_14_address1;
output   acc_d_14_ce1;
input  [31:0] acc_d_14_q1;
output  [2:0] acc_d_13_address0;
output   acc_d_13_ce0;
output   acc_d_13_we0;
output  [31:0] acc_d_13_d0;
output  [2:0] acc_d_13_address1;
output   acc_d_13_ce1;
input  [31:0] acc_d_13_q1;
output  [2:0] acc_d_12_address0;
output   acc_d_12_ce0;
output   acc_d_12_we0;
output  [31:0] acc_d_12_d0;
output  [2:0] acc_d_12_address1;
output   acc_d_12_ce1;
input  [31:0] acc_d_12_q1;
output  [2:0] acc_d_11_address0;
output   acc_d_11_ce0;
output   acc_d_11_we0;
output  [31:0] acc_d_11_d0;
output  [2:0] acc_d_11_address1;
output   acc_d_11_ce1;
input  [31:0] acc_d_11_q1;
output  [2:0] acc_d_10_address0;
output   acc_d_10_ce0;
output   acc_d_10_we0;
output  [31:0] acc_d_10_d0;
output  [2:0] acc_d_10_address1;
output   acc_d_10_ce1;
input  [31:0] acc_d_10_q1;
output  [2:0] acc_d_9_address0;
output   acc_d_9_ce0;
output   acc_d_9_we0;
output  [31:0] acc_d_9_d0;
output  [2:0] acc_d_9_address1;
output   acc_d_9_ce1;
input  [31:0] acc_d_9_q1;
output  [2:0] acc_d_8_address0;
output   acc_d_8_ce0;
output   acc_d_8_we0;
output  [31:0] acc_d_8_d0;
output  [2:0] acc_d_8_address1;
output   acc_d_8_ce1;
input  [31:0] acc_d_8_q1;
output  [2:0] acc_d_7_address0;
output   acc_d_7_ce0;
output   acc_d_7_we0;
output  [31:0] acc_d_7_d0;
output  [2:0] acc_d_7_address1;
output   acc_d_7_ce1;
input  [31:0] acc_d_7_q1;
output  [2:0] acc_d_6_address0;
output   acc_d_6_ce0;
output   acc_d_6_we0;
output  [31:0] acc_d_6_d0;
output  [2:0] acc_d_6_address1;
output   acc_d_6_ce1;
input  [31:0] acc_d_6_q1;
output  [2:0] acc_d_5_address0;
output   acc_d_5_ce0;
output   acc_d_5_we0;
output  [31:0] acc_d_5_d0;
output  [2:0] acc_d_5_address1;
output   acc_d_5_ce1;
input  [31:0] acc_d_5_q1;
output  [2:0] acc_d_4_address0;
output   acc_d_4_ce0;
output   acc_d_4_we0;
output  [31:0] acc_d_4_d0;
output  [2:0] acc_d_4_address1;
output   acc_d_4_ce1;
input  [31:0] acc_d_4_q1;
output  [2:0] acc_d_3_address0;
output   acc_d_3_ce0;
output   acc_d_3_we0;
output  [31:0] acc_d_3_d0;
output  [2:0] acc_d_3_address1;
output   acc_d_3_ce1;
input  [31:0] acc_d_3_q1;
output  [2:0] acc_d_2_address0;
output   acc_d_2_ce0;
output   acc_d_2_we0;
output  [31:0] acc_d_2_d0;
output  [2:0] acc_d_2_address1;
output   acc_d_2_ce1;
input  [31:0] acc_d_2_q1;
output  [2:0] acc_d_1_address0;
output   acc_d_1_ce0;
output   acc_d_1_we0;
output  [31:0] acc_d_1_d0;
output  [2:0] acc_d_1_address1;
output   acc_d_1_ce1;
input  [31:0] acc_d_1_q1;
output  [2:0] acc_d_address0;
output   acc_d_ce0;
output   acc_d_we0;
output  [31:0] acc_d_d0;
output  [2:0] acc_d_address1;
output   acc_d_ce1;
input  [31:0] acc_d_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln149_fu_1017_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln149_fu_1041_p3;
reg   [3:0] select_ln149_reg_1765;
wire   [2:0] trunc_ln149_fu_1073_p1;
reg   [2:0] trunc_ln149_reg_1770;
wire   [0:0] icmp_ln152_fu_1107_p2;
reg   [0:0] icmp_ln152_reg_1815;
wire   [31:0] p_val_fu_1308_p3;
reg   [31:0] p_val_reg_1900;
wire   [31:0] conv17_fu_785_p1;
reg   [31:0] conv17_reg_1936;
reg   [2:0] acc_d_addr_reg_1942;
reg   [2:0] acc_d_1_addr_reg_1949;
reg   [2:0] acc_d_2_addr_reg_1956;
reg   [2:0] acc_d_3_addr_reg_1963;
reg   [2:0] acc_d_4_addr_reg_1970;
reg   [2:0] acc_d_5_addr_reg_1977;
reg   [2:0] acc_d_6_addr_reg_1984;
reg   [2:0] acc_d_7_addr_reg_1991;
reg   [2:0] acc_d_8_addr_reg_1998;
reg   [2:0] acc_d_9_addr_reg_2005;
reg   [2:0] acc_d_10_addr_reg_2012;
reg   [2:0] acc_d_11_addr_reg_2019;
reg   [2:0] acc_d_12_addr_reg_2026;
reg   [2:0] acc_d_13_addr_reg_2033;
reg   [2:0] acc_d_14_addr_reg_2040;
wire   [31:0] conv27_1_fu_789_p1;
reg   [31:0] conv27_1_reg_2047;
wire   [31:0] conv27_2_fu_793_p1;
reg   [31:0] conv27_2_reg_2053;
wire   [31:0] conv27_3_fu_797_p1;
reg   [31:0] conv27_3_reg_2059;
wire   [31:0] conv27_4_fu_801_p1;
reg   [31:0] conv27_4_reg_2065;
wire   [31:0] conv27_5_fu_805_p1;
reg   [31:0] conv27_5_reg_2071;
wire   [31:0] conv27_6_fu_809_p1;
reg   [31:0] conv27_6_reg_2077;
wire   [31:0] conv27_7_fu_813_p1;
reg   [31:0] conv27_7_reg_2083;
wire   [31:0] conv27_8_fu_817_p1;
reg   [31:0] conv27_8_reg_2089;
wire   [31:0] conv27_9_fu_821_p1;
reg   [31:0] conv27_9_reg_2095;
wire   [31:0] conv27_s_fu_825_p1;
reg   [31:0] conv27_s_reg_2101;
wire   [31:0] conv27_10_fu_829_p1;
reg   [31:0] conv27_10_reg_2107;
wire   [31:0] conv27_11_fu_833_p1;
reg   [31:0] conv27_11_reg_2113;
wire   [31:0] conv27_12_fu_837_p1;
reg   [31:0] conv27_12_reg_2119;
wire   [31:0] conv27_13_fu_841_p1;
reg   [31:0] conv27_13_reg_2125;
wire   [31:0] conv27_14_fu_845_p1;
reg   [31:0] conv27_14_reg_2131;
reg   [2:0] acc_d_15_addr_reg_2137;
wire   [63:0] zext_ln153_fu_1095_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln166_1_fu_1155_p1;
wire   [63:0] zext_ln157_fu_1316_p1;
reg   [3:0] kk_fu_168;
wire   [3:0] add_ln157_fu_1239_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_kk_load;
reg   [6:0] j_fu_172;
wire   [6:0] select_ln149_1_fu_1049_p3;
reg   [6:0] ap_sig_allocacmp_j_load;
reg   [9:0] indvar_flatten_fu_176;
wire   [9:0] add_ln149_1_fu_1011_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten_load;
reg    P_tile_0_ce0_local;
reg    P_tile_1_ce0_local;
reg    P_tile_2_ce0_local;
reg    P_tile_3_ce0_local;
reg    P_tile_4_ce0_local;
reg    P_tile_5_ce0_local;
reg    P_tile_6_ce0_local;
reg    P_tile_7_ce0_local;
reg    V_tile_0_ce0_local;
reg    V_tile_1_ce0_local;
reg    V_tile_2_ce0_local;
reg    V_tile_3_ce0_local;
reg    V_tile_4_ce0_local;
reg    V_tile_5_ce0_local;
reg    V_tile_6_ce0_local;
reg    V_tile_7_ce0_local;
reg    V_tile_8_ce0_local;
reg    V_tile_9_ce0_local;
reg    V_tile_10_ce0_local;
reg    V_tile_11_ce0_local;
reg    V_tile_12_ce0_local;
reg    V_tile_13_ce0_local;
reg    V_tile_14_ce0_local;
reg    V_tile_15_ce0_local;
reg    acc_d_ce1_local;
reg    acc_d_we0_local;
wire   [31:0] add_fu_849_p4;
reg    acc_d_ce0_local;
reg    acc_d_1_ce1_local;
reg    acc_d_1_we0_local;
wire   [31:0] add31_s_fu_858_p4;
reg    acc_d_1_ce0_local;
reg    acc_d_2_ce1_local;
reg    acc_d_2_we0_local;
wire   [31:0] add31_1_fu_867_p4;
reg    acc_d_2_ce0_local;
reg    acc_d_3_ce1_local;
reg    acc_d_3_we0_local;
wire   [31:0] add31_2_fu_876_p4;
reg    acc_d_3_ce0_local;
reg    acc_d_4_ce1_local;
reg    acc_d_4_we0_local;
wire   [31:0] add31_3_fu_885_p4;
reg    acc_d_4_ce0_local;
reg    acc_d_5_ce1_local;
reg    acc_d_5_we0_local;
wire   [31:0] add31_4_fu_894_p4;
reg    acc_d_5_ce0_local;
reg    acc_d_6_ce1_local;
reg    acc_d_6_we0_local;
wire   [31:0] add31_5_fu_903_p4;
reg    acc_d_6_ce0_local;
reg    acc_d_7_ce1_local;
reg    acc_d_7_we0_local;
wire   [31:0] add31_6_fu_912_p4;
reg    acc_d_7_ce0_local;
reg    acc_d_8_ce1_local;
reg    acc_d_8_we0_local;
wire   [31:0] add31_7_fu_921_p4;
reg    acc_d_8_ce0_local;
reg    acc_d_9_ce1_local;
reg    acc_d_9_we0_local;
wire   [31:0] add31_8_fu_930_p4;
reg    acc_d_9_ce0_local;
reg    acc_d_10_ce1_local;
reg    acc_d_10_we0_local;
wire   [31:0] add31_9_fu_939_p4;
reg    acc_d_10_ce0_local;
reg    acc_d_11_ce1_local;
reg    acc_d_11_we0_local;
wire   [31:0] add31_10_fu_948_p4;
reg    acc_d_11_ce0_local;
reg    acc_d_12_ce1_local;
reg    acc_d_12_we0_local;
wire   [31:0] add31_11_fu_957_p4;
reg    acc_d_12_ce0_local;
reg    acc_d_13_ce1_local;
reg    acc_d_13_we0_local;
wire   [31:0] add31_12_fu_966_p4;
reg    acc_d_13_ce0_local;
reg    acc_d_14_ce1_local;
reg    acc_d_14_we0_local;
wire   [31:0] add31_13_fu_975_p4;
reg    acc_d_14_ce0_local;
reg    acc_d_15_ce1_local;
reg    acc_d_15_we0_local;
wire   [31:0] add31_14_fu_984_p4;
reg    acc_d_15_ce0_local;
wire   [15:0] tmp_fu_1264_p19;
wire   [0:0] icmp_ln157_fu_1035_p2;
wire   [6:0] add_ln149_fu_1029_p2;
wire   [5:0] trunc_ln166_fu_1057_p1;
wire   [2:0] lshr_ln2_fu_1077_p4;
wire   [8:0] tmp_181_fu_1087_p3;
wire   [31:0] zext_ln149_fu_1069_p1;
wire   [8:0] tmp_s_fu_1061_p3;
wire   [8:0] zext_ln166_fu_1145_p1;
wire   [8:0] add_ln166_fu_1149_p2;
wire   [15:0] tmp_fu_1264_p17;
wire   [0:0] and_ln152_fu_1260_p2;
wire   [31:0] conv_fu_782_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
wire    ap_enable_operation_156;
reg    ap_enable_state2_pp0_iter1_stage0;
wire    ap_enable_operation_250;
reg    ap_enable_state3_pp0_iter2_stage0;
wire    ap_enable_operation_332;
wire    ap_enable_operation_218;
wire    ap_enable_operation_255;
wire    ap_enable_operation_335;
wire    ap_enable_operation_220;
wire    ap_enable_operation_260;
wire    ap_enable_operation_338;
wire    ap_enable_operation_222;
wire    ap_enable_operation_265;
wire    ap_enable_operation_341;
wire    ap_enable_operation_224;
wire    ap_enable_operation_270;
wire    ap_enable_operation_344;
wire    ap_enable_operation_226;
wire    ap_enable_operation_275;
wire    ap_enable_operation_347;
wire    ap_enable_operation_228;
wire    ap_enable_operation_280;
wire    ap_enable_operation_350;
wire    ap_enable_operation_230;
wire    ap_enable_operation_285;
wire    ap_enable_operation_353;
wire    ap_enable_operation_232;
wire    ap_enable_operation_290;
wire    ap_enable_operation_356;
wire    ap_enable_operation_234;
wire    ap_enable_operation_295;
wire    ap_enable_operation_359;
wire    ap_enable_operation_236;
wire    ap_enable_operation_300;
wire    ap_enable_operation_362;
wire    ap_enable_operation_238;
wire    ap_enable_operation_305;
wire    ap_enable_operation_365;
wire    ap_enable_operation_240;
wire    ap_enable_operation_310;
wire    ap_enable_operation_368;
wire    ap_enable_operation_242;
wire    ap_enable_operation_315;
wire    ap_enable_operation_371;
wire    ap_enable_operation_244;
wire    ap_enable_operation_320;
wire    ap_enable_operation_374;
wire    ap_enable_operation_246;
wire    ap_enable_operation_325;
wire    ap_enable_operation_377;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_fu_1264_p1;
wire   [2:0] tmp_fu_1264_p3;
wire   [2:0] tmp_fu_1264_p5;
wire   [2:0] tmp_fu_1264_p7;
wire  signed [2:0] tmp_fu_1264_p9;
wire  signed [2:0] tmp_fu_1264_p11;
wire  signed [2:0] tmp_fu_1264_p13;
wire  signed [2:0] tmp_fu_1264_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 kk_fu_168 = 4'd0;
#0 j_fu_172 = 7'd0;
#0 indvar_flatten_fu_176 = 10'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1004(
    .din0(tmp_fu_1264_p19),
    .dout(conv_fu_782_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1005(
    .din0(V_tile_0_q0),
    .dout(conv17_fu_785_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1006(
    .din0(V_tile_1_q0),
    .dout(conv27_1_fu_789_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1007(
    .din0(V_tile_2_q0),
    .dout(conv27_2_fu_793_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1008(
    .din0(V_tile_3_q0),
    .dout(conv27_3_fu_797_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1009(
    .din0(V_tile_4_q0),
    .dout(conv27_4_fu_801_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1010(
    .din0(V_tile_5_q0),
    .dout(conv27_5_fu_805_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1011(
    .din0(V_tile_6_q0),
    .dout(conv27_6_fu_809_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1012(
    .din0(V_tile_7_q0),
    .dout(conv27_7_fu_813_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1013(
    .din0(V_tile_8_q0),
    .dout(conv27_8_fu_817_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1014(
    .din0(V_tile_9_q0),
    .dout(conv27_9_fu_821_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1015(
    .din0(V_tile_10_q0),
    .dout(conv27_s_fu_825_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1016(
    .din0(V_tile_11_q0),
    .dout(conv27_10_fu_829_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1017(
    .din0(V_tile_12_q0),
    .dout(conv27_11_fu_833_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1018(
    .din0(V_tile_13_q0),
    .dout(conv27_12_fu_837_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1019(
    .din0(V_tile_14_q0),
    .dout(conv27_13_fu_841_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U1020(
    .din0(V_tile_15_q0),
    .dout(conv27_14_fu_845_p1)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1021(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv17_reg_1936),
    .din3(acc_d_q1),
    .dout(add_fu_849_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1022(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_1_reg_2047),
    .din3(acc_d_1_q1),
    .dout(add31_s_fu_858_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1023(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_2_reg_2053),
    .din3(acc_d_2_q1),
    .dout(add31_1_fu_867_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1024(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_3_reg_2059),
    .din3(acc_d_3_q1),
    .dout(add31_2_fu_876_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1025(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_4_reg_2065),
    .din3(acc_d_4_q1),
    .dout(add31_3_fu_885_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1026(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_5_reg_2071),
    .din3(acc_d_5_q1),
    .dout(add31_4_fu_894_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1027(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_6_reg_2077),
    .din3(acc_d_6_q1),
    .dout(add31_5_fu_903_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1028(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_7_reg_2083),
    .din3(acc_d_7_q1),
    .dout(add31_6_fu_912_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1029(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_8_reg_2089),
    .din3(acc_d_8_q1),
    .dout(add31_7_fu_921_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1030(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_9_reg_2095),
    .din3(acc_d_9_q1),
    .dout(add31_8_fu_930_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1031(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_s_reg_2101),
    .din3(acc_d_10_q1),
    .dout(add31_9_fu_939_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1032(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_10_reg_2107),
    .din3(acc_d_11_q1),
    .dout(add31_10_fu_948_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1033(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_11_reg_2113),
    .din3(acc_d_12_q1),
    .dout(add31_11_fu_957_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1034(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_12_reg_2119),
    .din3(acc_d_13_q1),
    .dout(add31_12_fu_966_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1035(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_13_reg_2125),
    .din3(acc_d_14_q1),
    .dout(add31_13_fu_975_p4)
);

flash_attention_kernel_fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_1_primitive_dsp_1_U1036(
    .din0(32'd0),
    .din1(p_val_reg_1900),
    .din2(conv27_14_reg_2131),
    .din3(acc_d_15_q1),
    .dout(add31_14_fu_984_p4)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_17_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_17_3_16_1_1_U1037(
    .din0(P_tile_0_q0),
    .din1(P_tile_1_q0),
    .din2(P_tile_2_q0),
    .din3(P_tile_3_q0),
    .din4(P_tile_4_q0),
    .din5(P_tile_5_q0),
    .din6(P_tile_6_q0),
    .din7(P_tile_7_q0),
    .def(tmp_fu_1264_p17),
    .sel(trunc_ln149_reg_1770),
    .dout(tmp_fu_1264_p19)
);

flash_attention_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln149_fu_1017_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_176 <= add_ln149_1_fu_1011_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_176 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln149_fu_1017_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_172 <= select_ln149_1_fu_1049_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_172 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln149_fu_1017_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            kk_fu_168 <= add_ln157_fu_1239_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            kk_fu_168 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_10_addr_reg_2012 <= zext_ln157_fu_1316_p1;
        acc_d_11_addr_reg_2019 <= zext_ln157_fu_1316_p1;
        acc_d_12_addr_reg_2026 <= zext_ln157_fu_1316_p1;
        acc_d_13_addr_reg_2033 <= zext_ln157_fu_1316_p1;
        acc_d_14_addr_reg_2040 <= zext_ln157_fu_1316_p1;
        acc_d_15_addr_reg_2137 <= zext_ln157_fu_1316_p1;
        acc_d_1_addr_reg_1949 <= zext_ln157_fu_1316_p1;
        acc_d_2_addr_reg_1956 <= zext_ln157_fu_1316_p1;
        acc_d_3_addr_reg_1963 <= zext_ln157_fu_1316_p1;
        acc_d_4_addr_reg_1970 <= zext_ln157_fu_1316_p1;
        acc_d_5_addr_reg_1977 <= zext_ln157_fu_1316_p1;
        acc_d_6_addr_reg_1984 <= zext_ln157_fu_1316_p1;
        acc_d_7_addr_reg_1991 <= zext_ln157_fu_1316_p1;
        acc_d_8_addr_reg_1998 <= zext_ln157_fu_1316_p1;
        acc_d_9_addr_reg_2005 <= zext_ln157_fu_1316_p1;
        acc_d_addr_reg_1942 <= zext_ln157_fu_1316_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        conv17_reg_1936 <= conv17_fu_785_p1;
        conv27_10_reg_2107 <= conv27_10_fu_829_p1;
        conv27_11_reg_2113 <= conv27_11_fu_833_p1;
        conv27_12_reg_2119 <= conv27_12_fu_837_p1;
        conv27_13_reg_2125 <= conv27_13_fu_841_p1;
        conv27_14_reg_2131 <= conv27_14_fu_845_p1;
        conv27_1_reg_2047 <= conv27_1_fu_789_p1;
        conv27_2_reg_2053 <= conv27_2_fu_793_p1;
        conv27_3_reg_2059 <= conv27_3_fu_797_p1;
        conv27_4_reg_2065 <= conv27_4_fu_801_p1;
        conv27_5_reg_2071 <= conv27_5_fu_805_p1;
        conv27_6_reg_2077 <= conv27_6_fu_809_p1;
        conv27_7_reg_2083 <= conv27_7_fu_813_p1;
        conv27_8_reg_2089 <= conv27_8_fu_817_p1;
        conv27_9_reg_2095 <= conv27_9_fu_821_p1;
        conv27_s_reg_2101 <= conv27_s_fu_825_p1;
        icmp_ln152_reg_1815 <= icmp_ln152_fu_1107_p2;
        p_val_reg_1900 <= p_val_fu_1308_p3;
        select_ln149_reg_1765 <= select_ln149_fu_1041_p3;
        trunc_ln149_reg_1770 <= trunc_ln149_fu_1073_p1;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_tile_0_ce0_local = 1'b1;
    end else begin
        P_tile_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_tile_1_ce0_local = 1'b1;
    end else begin
        P_tile_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_tile_2_ce0_local = 1'b1;
    end else begin
        P_tile_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_tile_3_ce0_local = 1'b1;
    end else begin
        P_tile_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_tile_4_ce0_local = 1'b1;
    end else begin
        P_tile_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_tile_5_ce0_local = 1'b1;
    end else begin
        P_tile_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_tile_6_ce0_local = 1'b1;
    end else begin
        P_tile_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_tile_7_ce0_local = 1'b1;
    end else begin
        P_tile_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_0_ce0_local = 1'b1;
    end else begin
        V_tile_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_10_ce0_local = 1'b1;
    end else begin
        V_tile_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_11_ce0_local = 1'b1;
    end else begin
        V_tile_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_12_ce0_local = 1'b1;
    end else begin
        V_tile_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_13_ce0_local = 1'b1;
    end else begin
        V_tile_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_14_ce0_local = 1'b1;
    end else begin
        V_tile_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_15_ce0_local = 1'b1;
    end else begin
        V_tile_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_1_ce0_local = 1'b1;
    end else begin
        V_tile_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_2_ce0_local = 1'b1;
    end else begin
        V_tile_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_3_ce0_local = 1'b1;
    end else begin
        V_tile_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_4_ce0_local = 1'b1;
    end else begin
        V_tile_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_5_ce0_local = 1'b1;
    end else begin
        V_tile_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_6_ce0_local = 1'b1;
    end else begin
        V_tile_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_7_ce0_local = 1'b1;
    end else begin
        V_tile_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_8_ce0_local = 1'b1;
    end else begin
        V_tile_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        V_tile_9_ce0_local = 1'b1;
    end else begin
        V_tile_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_10_ce0_local = 1'b1;
    end else begin
        acc_d_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_10_ce1_local = 1'b1;
    end else begin
        acc_d_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_10_we0_local = 1'b1;
    end else begin
        acc_d_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_11_ce0_local = 1'b1;
    end else begin
        acc_d_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_11_ce1_local = 1'b1;
    end else begin
        acc_d_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_11_we0_local = 1'b1;
    end else begin
        acc_d_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_12_ce0_local = 1'b1;
    end else begin
        acc_d_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_12_ce1_local = 1'b1;
    end else begin
        acc_d_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_12_we0_local = 1'b1;
    end else begin
        acc_d_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_13_ce0_local = 1'b1;
    end else begin
        acc_d_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_13_ce1_local = 1'b1;
    end else begin
        acc_d_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_13_we0_local = 1'b1;
    end else begin
        acc_d_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_14_ce0_local = 1'b1;
    end else begin
        acc_d_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_14_ce1_local = 1'b1;
    end else begin
        acc_d_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_14_we0_local = 1'b1;
    end else begin
        acc_d_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_15_ce0_local = 1'b1;
    end else begin
        acc_d_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_15_ce1_local = 1'b1;
    end else begin
        acc_d_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_15_we0_local = 1'b1;
    end else begin
        acc_d_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_1_ce0_local = 1'b1;
    end else begin
        acc_d_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_1_ce1_local = 1'b1;
    end else begin
        acc_d_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_1_we0_local = 1'b1;
    end else begin
        acc_d_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_2_ce0_local = 1'b1;
    end else begin
        acc_d_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_2_ce1_local = 1'b1;
    end else begin
        acc_d_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_2_we0_local = 1'b1;
    end else begin
        acc_d_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_3_ce0_local = 1'b1;
    end else begin
        acc_d_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_3_ce1_local = 1'b1;
    end else begin
        acc_d_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_3_we0_local = 1'b1;
    end else begin
        acc_d_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_4_ce0_local = 1'b1;
    end else begin
        acc_d_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_4_ce1_local = 1'b1;
    end else begin
        acc_d_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_4_we0_local = 1'b1;
    end else begin
        acc_d_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_5_ce0_local = 1'b1;
    end else begin
        acc_d_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_5_ce1_local = 1'b1;
    end else begin
        acc_d_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_5_we0_local = 1'b1;
    end else begin
        acc_d_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_6_ce0_local = 1'b1;
    end else begin
        acc_d_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_6_ce1_local = 1'b1;
    end else begin
        acc_d_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_6_we0_local = 1'b1;
    end else begin
        acc_d_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_7_ce0_local = 1'b1;
    end else begin
        acc_d_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_7_ce1_local = 1'b1;
    end else begin
        acc_d_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_7_we0_local = 1'b1;
    end else begin
        acc_d_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_8_ce0_local = 1'b1;
    end else begin
        acc_d_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_8_ce1_local = 1'b1;
    end else begin
        acc_d_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_8_we0_local = 1'b1;
    end else begin
        acc_d_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_9_ce0_local = 1'b1;
    end else begin
        acc_d_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_9_ce1_local = 1'b1;
    end else begin
        acc_d_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_9_we0_local = 1'b1;
    end else begin
        acc_d_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_ce0_local = 1'b1;
    end else begin
        acc_d_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_d_ce1_local = 1'b1;
    end else begin
        acc_d_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acc_d_we0_local = 1'b1;
    end else begin
        acc_d_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln149_fu_1017_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_176;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_172;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_kk_load = 4'd0;
    end else begin
        ap_sig_allocacmp_kk_load = kk_fu_168;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign P_tile_0_address0 = zext_ln153_fu_1095_p1;

assign P_tile_0_ce0 = P_tile_0_ce0_local;

assign P_tile_1_address0 = zext_ln153_fu_1095_p1;

assign P_tile_1_ce0 = P_tile_1_ce0_local;

assign P_tile_2_address0 = zext_ln153_fu_1095_p1;

assign P_tile_2_ce0 = P_tile_2_ce0_local;

assign P_tile_3_address0 = zext_ln153_fu_1095_p1;

assign P_tile_3_ce0 = P_tile_3_ce0_local;

assign P_tile_4_address0 = zext_ln153_fu_1095_p1;

assign P_tile_4_ce0 = P_tile_4_ce0_local;

assign P_tile_5_address0 = zext_ln153_fu_1095_p1;

assign P_tile_5_ce0 = P_tile_5_ce0_local;

assign P_tile_6_address0 = zext_ln153_fu_1095_p1;

assign P_tile_6_ce0 = P_tile_6_ce0_local;

assign P_tile_7_address0 = zext_ln153_fu_1095_p1;

assign P_tile_7_ce0 = P_tile_7_ce0_local;

assign V_tile_0_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_0_ce0 = V_tile_0_ce0_local;

assign V_tile_10_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_10_ce0 = V_tile_10_ce0_local;

assign V_tile_11_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_11_ce0 = V_tile_11_ce0_local;

assign V_tile_12_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_12_ce0 = V_tile_12_ce0_local;

assign V_tile_13_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_13_ce0 = V_tile_13_ce0_local;

assign V_tile_14_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_14_ce0 = V_tile_14_ce0_local;

assign V_tile_15_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_15_ce0 = V_tile_15_ce0_local;

assign V_tile_1_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_1_ce0 = V_tile_1_ce0_local;

assign V_tile_2_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_2_ce0 = V_tile_2_ce0_local;

assign V_tile_3_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_3_ce0 = V_tile_3_ce0_local;

assign V_tile_4_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_4_ce0 = V_tile_4_ce0_local;

assign V_tile_5_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_5_ce0 = V_tile_5_ce0_local;

assign V_tile_6_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_6_ce0 = V_tile_6_ce0_local;

assign V_tile_7_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_7_ce0 = V_tile_7_ce0_local;

assign V_tile_8_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_8_ce0 = V_tile_8_ce0_local;

assign V_tile_9_address0 = zext_ln166_1_fu_1155_p1;

assign V_tile_9_ce0 = V_tile_9_ce0_local;

assign acc_d_10_address0 = acc_d_10_addr_reg_2012;

assign acc_d_10_address1 = zext_ln157_fu_1316_p1;

assign acc_d_10_ce0 = acc_d_10_ce0_local;

assign acc_d_10_ce1 = acc_d_10_ce1_local;

assign acc_d_10_d0 = add31_9_fu_939_p4;

assign acc_d_10_we0 = acc_d_10_we0_local;

assign acc_d_11_address0 = acc_d_11_addr_reg_2019;

assign acc_d_11_address1 = zext_ln157_fu_1316_p1;

assign acc_d_11_ce0 = acc_d_11_ce0_local;

assign acc_d_11_ce1 = acc_d_11_ce1_local;

assign acc_d_11_d0 = add31_10_fu_948_p4;

assign acc_d_11_we0 = acc_d_11_we0_local;

assign acc_d_12_address0 = acc_d_12_addr_reg_2026;

assign acc_d_12_address1 = zext_ln157_fu_1316_p1;

assign acc_d_12_ce0 = acc_d_12_ce0_local;

assign acc_d_12_ce1 = acc_d_12_ce1_local;

assign acc_d_12_d0 = add31_11_fu_957_p4;

assign acc_d_12_we0 = acc_d_12_we0_local;

assign acc_d_13_address0 = acc_d_13_addr_reg_2033;

assign acc_d_13_address1 = zext_ln157_fu_1316_p1;

assign acc_d_13_ce0 = acc_d_13_ce0_local;

assign acc_d_13_ce1 = acc_d_13_ce1_local;

assign acc_d_13_d0 = add31_12_fu_966_p4;

assign acc_d_13_we0 = acc_d_13_we0_local;

assign acc_d_14_address0 = acc_d_14_addr_reg_2040;

assign acc_d_14_address1 = zext_ln157_fu_1316_p1;

assign acc_d_14_ce0 = acc_d_14_ce0_local;

assign acc_d_14_ce1 = acc_d_14_ce1_local;

assign acc_d_14_d0 = add31_13_fu_975_p4;

assign acc_d_14_we0 = acc_d_14_we0_local;

assign acc_d_15_address0 = acc_d_15_addr_reg_2137;

assign acc_d_15_address1 = zext_ln157_fu_1316_p1;

assign acc_d_15_ce0 = acc_d_15_ce0_local;

assign acc_d_15_ce1 = acc_d_15_ce1_local;

assign acc_d_15_d0 = add31_14_fu_984_p4;

assign acc_d_15_we0 = acc_d_15_we0_local;

assign acc_d_1_address0 = acc_d_1_addr_reg_1949;

assign acc_d_1_address1 = zext_ln157_fu_1316_p1;

assign acc_d_1_ce0 = acc_d_1_ce0_local;

assign acc_d_1_ce1 = acc_d_1_ce1_local;

assign acc_d_1_d0 = add31_s_fu_858_p4;

assign acc_d_1_we0 = acc_d_1_we0_local;

assign acc_d_2_address0 = acc_d_2_addr_reg_1956;

assign acc_d_2_address1 = zext_ln157_fu_1316_p1;

assign acc_d_2_ce0 = acc_d_2_ce0_local;

assign acc_d_2_ce1 = acc_d_2_ce1_local;

assign acc_d_2_d0 = add31_1_fu_867_p4;

assign acc_d_2_we0 = acc_d_2_we0_local;

assign acc_d_3_address0 = acc_d_3_addr_reg_1963;

assign acc_d_3_address1 = zext_ln157_fu_1316_p1;

assign acc_d_3_ce0 = acc_d_3_ce0_local;

assign acc_d_3_ce1 = acc_d_3_ce1_local;

assign acc_d_3_d0 = add31_2_fu_876_p4;

assign acc_d_3_we0 = acc_d_3_we0_local;

assign acc_d_4_address0 = acc_d_4_addr_reg_1970;

assign acc_d_4_address1 = zext_ln157_fu_1316_p1;

assign acc_d_4_ce0 = acc_d_4_ce0_local;

assign acc_d_4_ce1 = acc_d_4_ce1_local;

assign acc_d_4_d0 = add31_3_fu_885_p4;

assign acc_d_4_we0 = acc_d_4_we0_local;

assign acc_d_5_address0 = acc_d_5_addr_reg_1977;

assign acc_d_5_address1 = zext_ln157_fu_1316_p1;

assign acc_d_5_ce0 = acc_d_5_ce0_local;

assign acc_d_5_ce1 = acc_d_5_ce1_local;

assign acc_d_5_d0 = add31_4_fu_894_p4;

assign acc_d_5_we0 = acc_d_5_we0_local;

assign acc_d_6_address0 = acc_d_6_addr_reg_1984;

assign acc_d_6_address1 = zext_ln157_fu_1316_p1;

assign acc_d_6_ce0 = acc_d_6_ce0_local;

assign acc_d_6_ce1 = acc_d_6_ce1_local;

assign acc_d_6_d0 = add31_5_fu_903_p4;

assign acc_d_6_we0 = acc_d_6_we0_local;

assign acc_d_7_address0 = acc_d_7_addr_reg_1991;

assign acc_d_7_address1 = zext_ln157_fu_1316_p1;

assign acc_d_7_ce0 = acc_d_7_ce0_local;

assign acc_d_7_ce1 = acc_d_7_ce1_local;

assign acc_d_7_d0 = add31_6_fu_912_p4;

assign acc_d_7_we0 = acc_d_7_we0_local;

assign acc_d_8_address0 = acc_d_8_addr_reg_1998;

assign acc_d_8_address1 = zext_ln157_fu_1316_p1;

assign acc_d_8_ce0 = acc_d_8_ce0_local;

assign acc_d_8_ce1 = acc_d_8_ce1_local;

assign acc_d_8_d0 = add31_7_fu_921_p4;

assign acc_d_8_we0 = acc_d_8_we0_local;

assign acc_d_9_address0 = acc_d_9_addr_reg_2005;

assign acc_d_9_address1 = zext_ln157_fu_1316_p1;

assign acc_d_9_ce0 = acc_d_9_ce0_local;

assign acc_d_9_ce1 = acc_d_9_ce1_local;

assign acc_d_9_d0 = add31_8_fu_930_p4;

assign acc_d_9_we0 = acc_d_9_we0_local;

assign acc_d_address0 = acc_d_addr_reg_1942;

assign acc_d_address1 = zext_ln157_fu_1316_p1;

assign acc_d_ce0 = acc_d_ce0_local;

assign acc_d_ce1 = acc_d_ce1_local;

assign acc_d_d0 = add_fu_849_p4;

assign acc_d_we0 = acc_d_we0_local;

assign add_ln149_1_fu_1011_p2 = (ap_sig_allocacmp_indvar_flatten_load + 10'd1);

assign add_ln149_fu_1029_p2 = (ap_sig_allocacmp_j_load + 7'd1);

assign add_ln157_fu_1239_p2 = (select_ln149_fu_1041_p3 + 4'd1);

assign add_ln166_fu_1149_p2 = (tmp_s_fu_1061_p3 + zext_ln166_fu_1145_p1);

assign and_ln152_fu_1260_p2 = (icmp_ln152_reg_1815 & cmp9);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_operation_156 = (1'b1 == 1'b1);

assign ap_enable_operation_218 = (1'b1 == 1'b1);

assign ap_enable_operation_220 = (1'b1 == 1'b1);

assign ap_enable_operation_222 = (1'b1 == 1'b1);

assign ap_enable_operation_224 = (1'b1 == 1'b1);

assign ap_enable_operation_226 = (1'b1 == 1'b1);

assign ap_enable_operation_228 = (1'b1 == 1'b1);

assign ap_enable_operation_230 = (1'b1 == 1'b1);

assign ap_enable_operation_232 = (1'b1 == 1'b1);

assign ap_enable_operation_234 = (1'b1 == 1'b1);

assign ap_enable_operation_236 = (1'b1 == 1'b1);

assign ap_enable_operation_238 = (1'b1 == 1'b1);

assign ap_enable_operation_240 = (1'b1 == 1'b1);

assign ap_enable_operation_242 = (1'b1 == 1'b1);

assign ap_enable_operation_244 = (1'b1 == 1'b1);

assign ap_enable_operation_246 = (1'b1 == 1'b1);

assign ap_enable_operation_250 = (1'b1 == 1'b1);

assign ap_enable_operation_255 = (1'b1 == 1'b1);

assign ap_enable_operation_260 = (1'b1 == 1'b1);

assign ap_enable_operation_265 = (1'b1 == 1'b1);

assign ap_enable_operation_270 = (1'b1 == 1'b1);

assign ap_enable_operation_275 = (1'b1 == 1'b1);

assign ap_enable_operation_280 = (1'b1 == 1'b1);

assign ap_enable_operation_285 = (1'b1 == 1'b1);

assign ap_enable_operation_290 = (1'b1 == 1'b1);

assign ap_enable_operation_295 = (1'b1 == 1'b1);

assign ap_enable_operation_300 = (1'b1 == 1'b1);

assign ap_enable_operation_305 = (1'b1 == 1'b1);

assign ap_enable_operation_310 = (1'b1 == 1'b1);

assign ap_enable_operation_315 = (1'b1 == 1'b1);

assign ap_enable_operation_320 = (1'b1 == 1'b1);

assign ap_enable_operation_325 = (1'b1 == 1'b1);

assign ap_enable_operation_332 = (1'b1 == 1'b1);

assign ap_enable_operation_335 = (1'b1 == 1'b1);

assign ap_enable_operation_338 = (1'b1 == 1'b1);

assign ap_enable_operation_341 = (1'b1 == 1'b1);

assign ap_enable_operation_344 = (1'b1 == 1'b1);

assign ap_enable_operation_347 = (1'b1 == 1'b1);

assign ap_enable_operation_350 = (1'b1 == 1'b1);

assign ap_enable_operation_353 = (1'b1 == 1'b1);

assign ap_enable_operation_356 = (1'b1 == 1'b1);

assign ap_enable_operation_359 = (1'b1 == 1'b1);

assign ap_enable_operation_362 = (1'b1 == 1'b1);

assign ap_enable_operation_365 = (1'b1 == 1'b1);

assign ap_enable_operation_368 = (1'b1 == 1'b1);

assign ap_enable_operation_371 = (1'b1 == 1'b1);

assign ap_enable_operation_374 = (1'b1 == 1'b1);

assign ap_enable_operation_377 = (1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln149_fu_1017_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln152_fu_1107_p2 = (($signed(zext_ln149_fu_1069_p1) < $signed(bc_actual)) ? 1'b1 : 1'b0);

assign icmp_ln157_fu_1035_p2 = ((ap_sig_allocacmp_kk_load == 4'd8) ? 1'b1 : 1'b0);

assign lshr_ln2_fu_1077_p4 = {{select_ln149_1_fu_1049_p3[5:3]}};

assign p_val_fu_1308_p3 = ((and_ln152_fu_1260_p2[0:0] == 1'b1) ? conv_fu_782_p1 : 32'd0);

assign select_ln149_1_fu_1049_p3 = ((icmp_ln157_fu_1035_p2[0:0] == 1'b1) ? add_ln149_fu_1029_p2 : ap_sig_allocacmp_j_load);

assign select_ln149_fu_1041_p3 = ((icmp_ln157_fu_1035_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_kk_load);

assign tmp_181_fu_1087_p3 = {{i}, {lshr_ln2_fu_1077_p4}};

assign tmp_fu_1264_p17 = 'bx;

assign tmp_s_fu_1061_p3 = {{trunc_ln166_fu_1057_p1}, {3'd0}};

assign trunc_ln149_fu_1073_p1 = select_ln149_1_fu_1049_p3[2:0];

assign trunc_ln166_fu_1057_p1 = select_ln149_1_fu_1049_p3[5:0];

assign zext_ln149_fu_1069_p1 = select_ln149_1_fu_1049_p3;

assign zext_ln153_fu_1095_p1 = tmp_181_fu_1087_p3;

assign zext_ln157_fu_1316_p1 = select_ln149_reg_1765;

assign zext_ln166_1_fu_1155_p1 = add_ln166_fu_1149_p2;

assign zext_ln166_fu_1145_p1 = select_ln149_fu_1041_p3;

endmodule //flash_attention_kernel_gemm_pv_Pipeline_GEMM_PV_RED_GEMM_PV_DCOL
