// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_kernel_flash_attention_kernel_Pipeline_INIT_O_ACC_VITIS_LOOP_202_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        O_acc_address1,
        O_acc_ce1,
        O_acc_we1,
        O_acc_d1,
        O_acc_1_address1,
        O_acc_1_ce1,
        O_acc_1_we1,
        O_acc_1_d1,
        O_acc_2_address1,
        O_acc_2_ce1,
        O_acc_2_we1,
        O_acc_2_d1,
        O_acc_3_address1,
        O_acc_3_ce1,
        O_acc_3_we1,
        O_acc_3_d1,
        O_acc_4_address1,
        O_acc_4_ce1,
        O_acc_4_we1,
        O_acc_4_d1,
        O_acc_5_address1,
        O_acc_5_ce1,
        O_acc_5_we1,
        O_acc_5_d1,
        O_acc_6_address1,
        O_acc_6_ce1,
        O_acc_6_we1,
        O_acc_6_d1,
        O_acc_7_address1,
        O_acc_7_ce1,
        O_acc_7_we1,
        O_acc_7_d1,
        O_acc_8_address1,
        O_acc_8_ce1,
        O_acc_8_we1,
        O_acc_8_d1,
        O_acc_9_address1,
        O_acc_9_ce1,
        O_acc_9_we1,
        O_acc_9_d1,
        O_acc_10_address1,
        O_acc_10_ce1,
        O_acc_10_we1,
        O_acc_10_d1,
        O_acc_11_address1,
        O_acc_11_ce1,
        O_acc_11_we1,
        O_acc_11_d1,
        O_acc_12_address1,
        O_acc_12_ce1,
        O_acc_12_we1,
        O_acc_12_d1,
        O_acc_13_address1,
        O_acc_13_ce1,
        O_acc_13_we1,
        O_acc_13_d1,
        O_acc_14_address1,
        O_acc_14_ce1,
        O_acc_14_we1,
        O_acc_14_d1,
        O_acc_15_address1,
        O_acc_15_ce1,
        O_acc_15_we1,
        O_acc_15_d1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] O_acc_address1;
output   O_acc_ce1;
output   O_acc_we1;
output  [31:0] O_acc_d1;
output  [8:0] O_acc_1_address1;
output   O_acc_1_ce1;
output   O_acc_1_we1;
output  [31:0] O_acc_1_d1;
output  [8:0] O_acc_2_address1;
output   O_acc_2_ce1;
output   O_acc_2_we1;
output  [31:0] O_acc_2_d1;
output  [8:0] O_acc_3_address1;
output   O_acc_3_ce1;
output   O_acc_3_we1;
output  [31:0] O_acc_3_d1;
output  [8:0] O_acc_4_address1;
output   O_acc_4_ce1;
output   O_acc_4_we1;
output  [31:0] O_acc_4_d1;
output  [8:0] O_acc_5_address1;
output   O_acc_5_ce1;
output   O_acc_5_we1;
output  [31:0] O_acc_5_d1;
output  [8:0] O_acc_6_address1;
output   O_acc_6_ce1;
output   O_acc_6_we1;
output  [31:0] O_acc_6_d1;
output  [8:0] O_acc_7_address1;
output   O_acc_7_ce1;
output   O_acc_7_we1;
output  [31:0] O_acc_7_d1;
output  [8:0] O_acc_8_address1;
output   O_acc_8_ce1;
output   O_acc_8_we1;
output  [31:0] O_acc_8_d1;
output  [8:0] O_acc_9_address1;
output   O_acc_9_ce1;
output   O_acc_9_we1;
output  [31:0] O_acc_9_d1;
output  [8:0] O_acc_10_address1;
output   O_acc_10_ce1;
output   O_acc_10_we1;
output  [31:0] O_acc_10_d1;
output  [8:0] O_acc_11_address1;
output   O_acc_11_ce1;
output   O_acc_11_we1;
output  [31:0] O_acc_11_d1;
output  [8:0] O_acc_12_address1;
output   O_acc_12_ce1;
output   O_acc_12_we1;
output  [31:0] O_acc_12_d1;
output  [8:0] O_acc_13_address1;
output   O_acc_13_ce1;
output   O_acc_13_we1;
output  [31:0] O_acc_13_d1;
output  [8:0] O_acc_14_address1;
output   O_acc_14_ce1;
output   O_acc_14_we1;
output  [31:0] O_acc_14_d1;
output  [8:0] O_acc_15_address1;
output   O_acc_15_ce1;
output   O_acc_15_we1;
output  [31:0] O_acc_15_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln201_fu_410_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln205_fu_482_p1;
reg   [7:0] c_fu_86;
wire   [7:0] add_ln202_fu_630_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_c_load;
reg   [6:0] r_fu_90;
wire   [6:0] select_ln201_2_fu_452_p3;
reg   [6:0] ap_sig_allocacmp_r_load;
reg   [9:0] indvar_flatten9_fu_94;
wire   [9:0] add_ln201_2_fu_404_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten9_load;
reg    O_acc_we1_local;
reg    O_acc_ce1_local;
reg    O_acc_1_we1_local;
reg    O_acc_1_ce1_local;
reg    O_acc_2_we1_local;
reg    O_acc_2_ce1_local;
reg    O_acc_3_we1_local;
reg    O_acc_3_ce1_local;
reg    O_acc_4_we1_local;
reg    O_acc_4_ce1_local;
reg    O_acc_5_we1_local;
reg    O_acc_5_ce1_local;
reg    O_acc_6_we1_local;
reg    O_acc_6_ce1_local;
reg    O_acc_7_we1_local;
reg    O_acc_7_ce1_local;
reg    O_acc_8_we1_local;
reg    O_acc_8_ce1_local;
reg    O_acc_9_we1_local;
reg    O_acc_9_ce1_local;
reg    O_acc_10_we1_local;
reg    O_acc_10_ce1_local;
reg    O_acc_11_we1_local;
reg    O_acc_11_ce1_local;
reg    O_acc_12_we1_local;
reg    O_acc_12_ce1_local;
reg    O_acc_13_we1_local;
reg    O_acc_13_ce1_local;
reg    O_acc_14_we1_local;
reg    O_acc_14_ce1_local;
reg    O_acc_15_we1_local;
reg    O_acc_15_ce1_local;
wire   [0:0] tmp_fu_432_p3;
wire   [6:0] trunc_ln201_fu_422_p1;
wire   [6:0] select_ln201_fu_440_p3;
wire   [6:0] add_ln201_fu_426_p2;
wire   [5:0] trunc_ln203_fu_460_p1;
wire   [2:0] lshr_ln_fu_464_p4;
wire   [8:0] tmp_s_fu_474_p3;
wire   [7:0] zext_ln201_fu_448_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 c_fu_86 = 8'd0;
#0 r_fu_90 = 7'd0;
#0 indvar_flatten9_fu_94 = 10'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln201_fu_410_p2 == 1'd0)) begin
            c_fu_86 <= add_ln202_fu_630_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_86 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln201_fu_410_p2 == 1'd0)) begin
            indvar_flatten9_fu_94 <= add_ln201_2_fu_404_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten9_fu_94 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln201_fu_410_p2 == 1'd0)) begin
            r_fu_90 <= select_ln201_2_fu_452_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_90 <= 7'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_10_ce1_local = 1'b1;
    end else begin
        O_acc_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_10_we1_local = 1'b1;
    end else begin
        O_acc_10_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_11_ce1_local = 1'b1;
    end else begin
        O_acc_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_11_we1_local = 1'b1;
    end else begin
        O_acc_11_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_12_ce1_local = 1'b1;
    end else begin
        O_acc_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_12_we1_local = 1'b1;
    end else begin
        O_acc_12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_13_ce1_local = 1'b1;
    end else begin
        O_acc_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_13_we1_local = 1'b1;
    end else begin
        O_acc_13_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_14_ce1_local = 1'b1;
    end else begin
        O_acc_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_14_we1_local = 1'b1;
    end else begin
        O_acc_14_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_15_ce1_local = 1'b1;
    end else begin
        O_acc_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_15_we1_local = 1'b1;
    end else begin
        O_acc_15_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_1_ce1_local = 1'b1;
    end else begin
        O_acc_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_1_we1_local = 1'b1;
    end else begin
        O_acc_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_2_ce1_local = 1'b1;
    end else begin
        O_acc_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_2_we1_local = 1'b1;
    end else begin
        O_acc_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_3_ce1_local = 1'b1;
    end else begin
        O_acc_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_3_we1_local = 1'b1;
    end else begin
        O_acc_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_4_ce1_local = 1'b1;
    end else begin
        O_acc_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_4_we1_local = 1'b1;
    end else begin
        O_acc_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_5_ce1_local = 1'b1;
    end else begin
        O_acc_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_5_we1_local = 1'b1;
    end else begin
        O_acc_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_6_ce1_local = 1'b1;
    end else begin
        O_acc_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_6_we1_local = 1'b1;
    end else begin
        O_acc_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_7_ce1_local = 1'b1;
    end else begin
        O_acc_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_7_we1_local = 1'b1;
    end else begin
        O_acc_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_8_ce1_local = 1'b1;
    end else begin
        O_acc_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_8_we1_local = 1'b1;
    end else begin
        O_acc_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_9_ce1_local = 1'b1;
    end else begin
        O_acc_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_9_we1_local = 1'b1;
    end else begin
        O_acc_9_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_ce1_local = 1'b1;
    end else begin
        O_acc_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        O_acc_we1_local = 1'b1;
    end else begin
        O_acc_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_410_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 8'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_86;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten9_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten9_load = indvar_flatten9_fu_94;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_r_load = 7'd0;
    end else begin
        ap_sig_allocacmp_r_load = r_fu_90;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign O_acc_10_address1 = zext_ln205_fu_482_p1;

assign O_acc_10_ce1 = O_acc_10_ce1_local;

assign O_acc_10_d1 = 32'd0;

assign O_acc_10_we1 = O_acc_10_we1_local;

assign O_acc_11_address1 = zext_ln205_fu_482_p1;

assign O_acc_11_ce1 = O_acc_11_ce1_local;

assign O_acc_11_d1 = 32'd0;

assign O_acc_11_we1 = O_acc_11_we1_local;

assign O_acc_12_address1 = zext_ln205_fu_482_p1;

assign O_acc_12_ce1 = O_acc_12_ce1_local;

assign O_acc_12_d1 = 32'd0;

assign O_acc_12_we1 = O_acc_12_we1_local;

assign O_acc_13_address1 = zext_ln205_fu_482_p1;

assign O_acc_13_ce1 = O_acc_13_ce1_local;

assign O_acc_13_d1 = 32'd0;

assign O_acc_13_we1 = O_acc_13_we1_local;

assign O_acc_14_address1 = zext_ln205_fu_482_p1;

assign O_acc_14_ce1 = O_acc_14_ce1_local;

assign O_acc_14_d1 = 32'd0;

assign O_acc_14_we1 = O_acc_14_we1_local;

assign O_acc_15_address1 = zext_ln205_fu_482_p1;

assign O_acc_15_ce1 = O_acc_15_ce1_local;

assign O_acc_15_d1 = 32'd0;

assign O_acc_15_we1 = O_acc_15_we1_local;

assign O_acc_1_address1 = zext_ln205_fu_482_p1;

assign O_acc_1_ce1 = O_acc_1_ce1_local;

assign O_acc_1_d1 = 32'd0;

assign O_acc_1_we1 = O_acc_1_we1_local;

assign O_acc_2_address1 = zext_ln205_fu_482_p1;

assign O_acc_2_ce1 = O_acc_2_ce1_local;

assign O_acc_2_d1 = 32'd0;

assign O_acc_2_we1 = O_acc_2_we1_local;

assign O_acc_3_address1 = zext_ln205_fu_482_p1;

assign O_acc_3_ce1 = O_acc_3_ce1_local;

assign O_acc_3_d1 = 32'd0;

assign O_acc_3_we1 = O_acc_3_we1_local;

assign O_acc_4_address1 = zext_ln205_fu_482_p1;

assign O_acc_4_ce1 = O_acc_4_ce1_local;

assign O_acc_4_d1 = 32'd0;

assign O_acc_4_we1 = O_acc_4_we1_local;

assign O_acc_5_address1 = zext_ln205_fu_482_p1;

assign O_acc_5_ce1 = O_acc_5_ce1_local;

assign O_acc_5_d1 = 32'd0;

assign O_acc_5_we1 = O_acc_5_we1_local;

assign O_acc_6_address1 = zext_ln205_fu_482_p1;

assign O_acc_6_ce1 = O_acc_6_ce1_local;

assign O_acc_6_d1 = 32'd0;

assign O_acc_6_we1 = O_acc_6_we1_local;

assign O_acc_7_address1 = zext_ln205_fu_482_p1;

assign O_acc_7_ce1 = O_acc_7_ce1_local;

assign O_acc_7_d1 = 32'd0;

assign O_acc_7_we1 = O_acc_7_we1_local;

assign O_acc_8_address1 = zext_ln205_fu_482_p1;

assign O_acc_8_ce1 = O_acc_8_ce1_local;

assign O_acc_8_d1 = 32'd0;

assign O_acc_8_we1 = O_acc_8_we1_local;

assign O_acc_9_address1 = zext_ln205_fu_482_p1;

assign O_acc_9_ce1 = O_acc_9_ce1_local;

assign O_acc_9_d1 = 32'd0;

assign O_acc_9_we1 = O_acc_9_we1_local;

assign O_acc_address1 = zext_ln205_fu_482_p1;

assign O_acc_ce1 = O_acc_ce1_local;

assign O_acc_d1 = 32'd0;

assign O_acc_we1 = O_acc_we1_local;

assign add_ln201_2_fu_404_p2 = (ap_sig_allocacmp_indvar_flatten9_load + 10'd1);

assign add_ln201_fu_426_p2 = (ap_sig_allocacmp_r_load + 7'd1);

assign add_ln202_fu_630_p2 = (zext_ln201_fu_448_p1 + 8'd16);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln201_fu_410_p2 = ((ap_sig_allocacmp_indvar_flatten9_load == 10'd512) ? 1'b1 : 1'b0);

assign lshr_ln_fu_464_p4 = {{select_ln201_fu_440_p3[6:4]}};

assign select_ln201_2_fu_452_p3 = ((tmp_fu_432_p3[0:0] == 1'b1) ? add_ln201_fu_426_p2 : ap_sig_allocacmp_r_load);

assign select_ln201_fu_440_p3 = ((tmp_fu_432_p3[0:0] == 1'b1) ? 7'd0 : trunc_ln201_fu_422_p1);

assign tmp_fu_432_p3 = ap_sig_allocacmp_c_load[32'd7];

assign tmp_s_fu_474_p3 = {{trunc_ln203_fu_460_p1}, {lshr_ln_fu_464_p4}};

assign trunc_ln201_fu_422_p1 = ap_sig_allocacmp_c_load[6:0];

assign trunc_ln203_fu_460_p1 = select_ln201_2_fu_452_p3[5:0];

assign zext_ln201_fu_448_p1 = select_ln201_fu_440_p3;

assign zext_ln205_fu_482_p1 = tmp_s_fu_474_p3;

endmodule //flash_attention_kernel_flash_attention_kernel_Pipeline_INIT_O_ACC_VITIS_LOOP_202_2
