// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_kernel_normalize_output (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        O_fp32_0_address0,
        O_fp32_0_ce0,
        O_fp32_0_q0,
        O_fp32_1_address0,
        O_fp32_1_ce0,
        O_fp32_1_q0,
        O_fp32_2_address0,
        O_fp32_2_ce0,
        O_fp32_2_q0,
        O_fp32_3_address0,
        O_fp32_3_ce0,
        O_fp32_3_q0,
        O_fp32_4_address0,
        O_fp32_4_ce0,
        O_fp32_4_q0,
        O_fp32_5_address0,
        O_fp32_5_ce0,
        O_fp32_5_q0,
        O_fp32_6_address0,
        O_fp32_6_ce0,
        O_fp32_6_q0,
        O_fp32_7_address0,
        O_fp32_7_ce0,
        O_fp32_7_q0,
        O_fp32_8_address0,
        O_fp32_8_ce0,
        O_fp32_8_q0,
        O_fp32_9_address0,
        O_fp32_9_ce0,
        O_fp32_9_q0,
        O_fp32_10_address0,
        O_fp32_10_ce0,
        O_fp32_10_q0,
        O_fp32_11_address0,
        O_fp32_11_ce0,
        O_fp32_11_q0,
        O_fp32_12_address0,
        O_fp32_12_ce0,
        O_fp32_12_q0,
        O_fp32_13_address0,
        O_fp32_13_ce0,
        O_fp32_13_q0,
        O_fp32_14_address0,
        O_fp32_14_ce0,
        O_fp32_14_q0,
        O_fp32_15_address0,
        O_fp32_15_ce0,
        O_fp32_15_q0,
        O_fp16_0_address1,
        O_fp16_0_ce1,
        O_fp16_0_we1,
        O_fp16_0_d1,
        O_fp16_1_address1,
        O_fp16_1_ce1,
        O_fp16_1_we1,
        O_fp16_1_d1,
        O_fp16_2_address1,
        O_fp16_2_ce1,
        O_fp16_2_we1,
        O_fp16_2_d1,
        O_fp16_3_address1,
        O_fp16_3_ce1,
        O_fp16_3_we1,
        O_fp16_3_d1,
        O_fp16_4_address1,
        O_fp16_4_ce1,
        O_fp16_4_we1,
        O_fp16_4_d1,
        O_fp16_5_address1,
        O_fp16_5_ce1,
        O_fp16_5_we1,
        O_fp16_5_d1,
        O_fp16_6_address1,
        O_fp16_6_ce1,
        O_fp16_6_we1,
        O_fp16_6_d1,
        O_fp16_7_address1,
        O_fp16_7_ce1,
        O_fp16_7_we1,
        O_fp16_7_d1,
        O_fp16_8_address1,
        O_fp16_8_ce1,
        O_fp16_8_we1,
        O_fp16_8_d1,
        O_fp16_9_address1,
        O_fp16_9_ce1,
        O_fp16_9_we1,
        O_fp16_9_d1,
        O_fp16_10_address1,
        O_fp16_10_ce1,
        O_fp16_10_we1,
        O_fp16_10_d1,
        O_fp16_11_address1,
        O_fp16_11_ce1,
        O_fp16_11_we1,
        O_fp16_11_d1,
        O_fp16_12_address1,
        O_fp16_12_ce1,
        O_fp16_12_we1,
        O_fp16_12_d1,
        O_fp16_13_address1,
        O_fp16_13_ce1,
        O_fp16_13_we1,
        O_fp16_13_d1,
        O_fp16_14_address1,
        O_fp16_14_ce1,
        O_fp16_14_we1,
        O_fp16_14_d1,
        O_fp16_15_address1,
        O_fp16_15_ce1,
        O_fp16_15_we1,
        O_fp16_15_d1,
        l_i_0_val,
        l_i_1_val,
        l_i_2_val,
        l_i_3_val,
        l_i_4_val,
        l_i_5_val,
        l_i_6_val,
        l_i_7_val,
        l_i_8_val,
        l_i_9_val,
        l_i_10_val,
        l_i_11_val,
        l_i_12_val,
        l_i_13_val,
        l_i_14_val,
        l_i_15_val,
        l_i_16_val,
        l_i_17_val,
        l_i_18_val,
        l_i_19_val,
        l_i_20_val,
        l_i_21_val,
        l_i_22_val,
        l_i_23_val,
        l_i_24_val,
        l_i_25_val,
        l_i_26_val,
        l_i_27_val,
        l_i_28_val,
        l_i_29_val,
        l_i_30_val,
        l_i_31_val,
        l_i_32_val,
        l_i_33_val,
        l_i_34_val,
        l_i_35_val,
        l_i_36_val,
        l_i_37_val,
        l_i_38_val,
        l_i_39_val,
        l_i_40_val,
        l_i_41_val,
        l_i_42_val,
        l_i_43_val,
        l_i_44_val,
        l_i_45_val,
        l_i_46_val,
        l_i_47_val,
        l_i_48_val,
        l_i_49_val,
        l_i_50_val,
        l_i_51_val,
        l_i_52_val,
        l_i_53_val,
        l_i_54_val,
        l_i_55_val,
        l_i_56_val,
        l_i_57_val,
        l_i_58_val,
        l_i_59_val,
        l_i_60_val,
        l_i_61_val,
        l_i_62_val,
        l_i_63_val,
        br_actual
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] O_fp32_0_address0;
output   O_fp32_0_ce0;
input  [31:0] O_fp32_0_q0;
output  [8:0] O_fp32_1_address0;
output   O_fp32_1_ce0;
input  [31:0] O_fp32_1_q0;
output  [8:0] O_fp32_2_address0;
output   O_fp32_2_ce0;
input  [31:0] O_fp32_2_q0;
output  [8:0] O_fp32_3_address0;
output   O_fp32_3_ce0;
input  [31:0] O_fp32_3_q0;
output  [8:0] O_fp32_4_address0;
output   O_fp32_4_ce0;
input  [31:0] O_fp32_4_q0;
output  [8:0] O_fp32_5_address0;
output   O_fp32_5_ce0;
input  [31:0] O_fp32_5_q0;
output  [8:0] O_fp32_6_address0;
output   O_fp32_6_ce0;
input  [31:0] O_fp32_6_q0;
output  [8:0] O_fp32_7_address0;
output   O_fp32_7_ce0;
input  [31:0] O_fp32_7_q0;
output  [8:0] O_fp32_8_address0;
output   O_fp32_8_ce0;
input  [31:0] O_fp32_8_q0;
output  [8:0] O_fp32_9_address0;
output   O_fp32_9_ce0;
input  [31:0] O_fp32_9_q0;
output  [8:0] O_fp32_10_address0;
output   O_fp32_10_ce0;
input  [31:0] O_fp32_10_q0;
output  [8:0] O_fp32_11_address0;
output   O_fp32_11_ce0;
input  [31:0] O_fp32_11_q0;
output  [8:0] O_fp32_12_address0;
output   O_fp32_12_ce0;
input  [31:0] O_fp32_12_q0;
output  [8:0] O_fp32_13_address0;
output   O_fp32_13_ce0;
input  [31:0] O_fp32_13_q0;
output  [8:0] O_fp32_14_address0;
output   O_fp32_14_ce0;
input  [31:0] O_fp32_14_q0;
output  [8:0] O_fp32_15_address0;
output   O_fp32_15_ce0;
input  [31:0] O_fp32_15_q0;
output  [8:0] O_fp16_0_address1;
output   O_fp16_0_ce1;
output   O_fp16_0_we1;
output  [15:0] O_fp16_0_d1;
output  [8:0] O_fp16_1_address1;
output   O_fp16_1_ce1;
output   O_fp16_1_we1;
output  [15:0] O_fp16_1_d1;
output  [8:0] O_fp16_2_address1;
output   O_fp16_2_ce1;
output   O_fp16_2_we1;
output  [15:0] O_fp16_2_d1;
output  [8:0] O_fp16_3_address1;
output   O_fp16_3_ce1;
output   O_fp16_3_we1;
output  [15:0] O_fp16_3_d1;
output  [8:0] O_fp16_4_address1;
output   O_fp16_4_ce1;
output   O_fp16_4_we1;
output  [15:0] O_fp16_4_d1;
output  [8:0] O_fp16_5_address1;
output   O_fp16_5_ce1;
output   O_fp16_5_we1;
output  [15:0] O_fp16_5_d1;
output  [8:0] O_fp16_6_address1;
output   O_fp16_6_ce1;
output   O_fp16_6_we1;
output  [15:0] O_fp16_6_d1;
output  [8:0] O_fp16_7_address1;
output   O_fp16_7_ce1;
output   O_fp16_7_we1;
output  [15:0] O_fp16_7_d1;
output  [8:0] O_fp16_8_address1;
output   O_fp16_8_ce1;
output   O_fp16_8_we1;
output  [15:0] O_fp16_8_d1;
output  [8:0] O_fp16_9_address1;
output   O_fp16_9_ce1;
output   O_fp16_9_we1;
output  [15:0] O_fp16_9_d1;
output  [8:0] O_fp16_10_address1;
output   O_fp16_10_ce1;
output   O_fp16_10_we1;
output  [15:0] O_fp16_10_d1;
output  [8:0] O_fp16_11_address1;
output   O_fp16_11_ce1;
output   O_fp16_11_we1;
output  [15:0] O_fp16_11_d1;
output  [8:0] O_fp16_12_address1;
output   O_fp16_12_ce1;
output   O_fp16_12_we1;
output  [15:0] O_fp16_12_d1;
output  [8:0] O_fp16_13_address1;
output   O_fp16_13_ce1;
output   O_fp16_13_we1;
output  [15:0] O_fp16_13_d1;
output  [8:0] O_fp16_14_address1;
output   O_fp16_14_ce1;
output   O_fp16_14_we1;
output  [15:0] O_fp16_14_d1;
output  [8:0] O_fp16_15_address1;
output   O_fp16_15_ce1;
output   O_fp16_15_we1;
output  [15:0] O_fp16_15_d1;
input  [31:0] l_i_0_val;
input  [31:0] l_i_1_val;
input  [31:0] l_i_2_val;
input  [31:0] l_i_3_val;
input  [31:0] l_i_4_val;
input  [31:0] l_i_5_val;
input  [31:0] l_i_6_val;
input  [31:0] l_i_7_val;
input  [31:0] l_i_8_val;
input  [31:0] l_i_9_val;
input  [31:0] l_i_10_val;
input  [31:0] l_i_11_val;
input  [31:0] l_i_12_val;
input  [31:0] l_i_13_val;
input  [31:0] l_i_14_val;
input  [31:0] l_i_15_val;
input  [31:0] l_i_16_val;
input  [31:0] l_i_17_val;
input  [31:0] l_i_18_val;
input  [31:0] l_i_19_val;
input  [31:0] l_i_20_val;
input  [31:0] l_i_21_val;
input  [31:0] l_i_22_val;
input  [31:0] l_i_23_val;
input  [31:0] l_i_24_val;
input  [31:0] l_i_25_val;
input  [31:0] l_i_26_val;
input  [31:0] l_i_27_val;
input  [31:0] l_i_28_val;
input  [31:0] l_i_29_val;
input  [31:0] l_i_30_val;
input  [31:0] l_i_31_val;
input  [31:0] l_i_32_val;
input  [31:0] l_i_33_val;
input  [31:0] l_i_34_val;
input  [31:0] l_i_35_val;
input  [31:0] l_i_36_val;
input  [31:0] l_i_37_val;
input  [31:0] l_i_38_val;
input  [31:0] l_i_39_val;
input  [31:0] l_i_40_val;
input  [31:0] l_i_41_val;
input  [31:0] l_i_42_val;
input  [31:0] l_i_43_val;
input  [31:0] l_i_44_val;
input  [31:0] l_i_45_val;
input  [31:0] l_i_46_val;
input  [31:0] l_i_47_val;
input  [31:0] l_i_48_val;
input  [31:0] l_i_49_val;
input  [31:0] l_i_50_val;
input  [31:0] l_i_51_val;
input  [31:0] l_i_52_val;
input  [31:0] l_i_53_val;
input  [31:0] l_i_54_val;
input  [31:0] l_i_55_val;
input  [31:0] l_i_56_val;
input  [31:0] l_i_57_val;
input  [31:0] l_i_58_val;
input  [31:0] l_i_59_val;
input  [31:0] l_i_60_val;
input  [31:0] l_i_61_val;
input  [31:0] l_i_62_val;
input  [31:0] l_i_63_val;
input  [31:0] br_actual;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln193_fu_1481_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [33:0] tmp_s_fu_1449_p3;
reg   [33:0] tmp_s_reg_2507;
wire   [5:0] trunc_ln193_1_fu_1530_p1;
reg   [5:0] trunc_ln193_1_reg_2516;
reg   [5:0] trunc_ln193_1_reg_2516_pp0_iter2_reg;
reg   [5:0] trunc_ln193_1_reg_2516_pp0_iter3_reg;
reg   [5:0] trunc_ln193_1_reg_2516_pp0_iter4_reg;
reg   [5:0] trunc_ln193_1_reg_2516_pp0_iter5_reg;
wire   [31:0] tmp_fu_1534_p131;
reg   [31:0] tmp_reg_2521;
reg   [2:0] lshr_ln_reg_2527;
reg   [2:0] lshr_ln_reg_2527_pp0_iter2_reg;
reg   [2:0] lshr_ln_reg_2527_pp0_iter3_reg;
reg   [2:0] lshr_ln_reg_2527_pp0_iter4_reg;
reg   [2:0] lshr_ln_reg_2527_pp0_iter5_reg;
wire   [63:0] zext_ln200_fu_1778_p1;
reg   [63:0] zext_ln200_reg_2532;
reg   [63:0] zext_ln200_reg_2532_pp0_iter7_reg;
wire   [15:0] conv_fu_1367_p1;
reg   [15:0] conv_reg_2632;
wire   [15:0] conv_1_fu_1371_p1;
reg   [15:0] conv_1_reg_2638;
wire   [15:0] conv_2_fu_1375_p1;
reg   [15:0] conv_2_reg_2644;
wire   [15:0] conv_3_fu_1379_p1;
reg   [15:0] conv_3_reg_2650;
wire   [15:0] conv_4_fu_1383_p1;
reg   [15:0] conv_4_reg_2656;
wire   [15:0] conv_5_fu_1387_p1;
reg   [15:0] conv_5_reg_2662;
wire   [15:0] conv_6_fu_1391_p1;
reg   [15:0] conv_6_reg_2668;
wire   [15:0] conv_7_fu_1395_p1;
reg   [15:0] conv_7_reg_2674;
wire   [15:0] conv_8_fu_1399_p1;
reg   [15:0] conv_8_reg_2680;
wire   [15:0] conv_9_fu_1403_p1;
reg   [15:0] conv_9_reg_2686;
wire   [15:0] conv_s_fu_1407_p1;
reg   [15:0] conv_s_reg_2692;
wire   [15:0] conv_10_fu_1411_p1;
reg   [15:0] conv_10_reg_2698;
wire   [15:0] conv_11_fu_1415_p1;
reg   [15:0] conv_11_reg_2704;
wire   [15:0] conv_12_fu_1419_p1;
reg   [15:0] conv_12_reg_2710;
wire   [15:0] conv_13_fu_1423_p1;
reg   [15:0] conv_13_reg_2716;
wire   [15:0] conv_14_fu_1427_p1;
reg   [15:0] conv_14_reg_2722;
wire    ap_block_pp0_stage0;
reg   [7:0] k_fu_384;
wire   [7:0] add_ln197_fu_1744_p2;
wire    ap_loop_init;
reg   [30:0] i_fu_388;
wire   [30:0] select_ln193_1_fu_1522_p3;
reg   [33:0] indvar_flatten_fu_392;
wire   [33:0] add_ln193_1_fu_1475_p2;
reg    O_fp32_0_ce0_local;
reg    O_fp32_1_ce0_local;
reg    O_fp32_2_ce0_local;
reg    O_fp32_3_ce0_local;
reg    O_fp32_4_ce0_local;
reg    O_fp32_5_ce0_local;
reg    O_fp32_6_ce0_local;
reg    O_fp32_7_ce0_local;
reg    O_fp32_8_ce0_local;
reg    O_fp32_9_ce0_local;
reg    O_fp32_10_ce0_local;
reg    O_fp32_11_ce0_local;
reg    O_fp32_12_ce0_local;
reg    O_fp32_13_ce0_local;
reg    O_fp32_14_ce0_local;
reg    O_fp32_15_ce0_local;
reg    O_fp16_0_we1_local;
reg    O_fp16_0_ce1_local;
reg    O_fp16_1_we1_local;
reg    O_fp16_1_ce1_local;
reg    O_fp16_2_we1_local;
reg    O_fp16_2_ce1_local;
reg    O_fp16_3_we1_local;
reg    O_fp16_3_ce1_local;
reg    O_fp16_4_we1_local;
reg    O_fp16_4_ce1_local;
reg    O_fp16_5_we1_local;
reg    O_fp16_5_ce1_local;
reg    O_fp16_6_we1_local;
reg    O_fp16_6_ce1_local;
reg    O_fp16_7_we1_local;
reg    O_fp16_7_ce1_local;
reg    O_fp16_8_we1_local;
reg    O_fp16_8_ce1_local;
reg    O_fp16_9_we1_local;
reg    O_fp16_9_ce1_local;
reg    O_fp16_10_we1_local;
reg    O_fp16_10_ce1_local;
reg    O_fp16_11_we1_local;
reg    O_fp16_11_ce1_local;
reg    O_fp16_12_we1_local;
reg    O_fp16_12_ce1_local;
reg    O_fp16_13_we1_local;
reg    O_fp16_13_ce1_local;
reg    O_fp16_14_we1_local;
reg    O_fp16_14_ce1_local;
reg    O_fp16_15_we1_local;
reg    O_fp16_15_ce1_local;
wire   [31:0] grp_fu_1346_p2;
wire   [31:0] mul_fu_1266_p2;
wire   [31:0] mul_1_fu_1271_p2;
wire   [31:0] mul_2_fu_1276_p2;
wire   [31:0] mul_3_fu_1281_p2;
wire   [31:0] mul_4_fu_1286_p2;
wire   [31:0] mul_5_fu_1291_p2;
wire   [31:0] mul_6_fu_1296_p2;
wire   [31:0] mul_7_fu_1301_p2;
wire   [31:0] mul_8_fu_1306_p2;
wire   [31:0] mul_9_fu_1311_p2;
wire   [31:0] mul_s_fu_1316_p2;
wire   [31:0] mul_10_fu_1321_p2;
wire   [31:0] mul_11_fu_1326_p2;
wire   [31:0] mul_12_fu_1331_p2;
wire   [31:0] mul_13_fu_1336_p2;
wire   [31:0] mul_14_fu_1341_p2;
wire   [0:0] empty_75_fu_1435_p2;
wire   [30:0] empty_fu_1431_p1;
wire   [30:0] empty_76_fu_1441_p3;
wire   [0:0] tmp_3_fu_1502_p3;
wire   [6:0] trunc_ln193_fu_1492_p1;
wire   [6:0] select_ln193_fu_1510_p3;
wire   [30:0] add_ln193_fu_1496_p2;
wire   [31:0] tmp_fu_1534_p129;
wire   [5:0] tmp_fu_1534_p130;
wire   [7:0] zext_ln193_fu_1518_p1;
wire   [8:0] tmp_24_fu_1772_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [5:0] tmp_fu_1534_p1;
wire   [5:0] tmp_fu_1534_p3;
wire   [5:0] tmp_fu_1534_p5;
wire   [5:0] tmp_fu_1534_p7;
wire   [5:0] tmp_fu_1534_p9;
wire   [5:0] tmp_fu_1534_p11;
wire   [5:0] tmp_fu_1534_p13;
wire   [5:0] tmp_fu_1534_p15;
wire   [5:0] tmp_fu_1534_p17;
wire   [5:0] tmp_fu_1534_p19;
wire   [5:0] tmp_fu_1534_p21;
wire   [5:0] tmp_fu_1534_p23;
wire   [5:0] tmp_fu_1534_p25;
wire   [5:0] tmp_fu_1534_p27;
wire   [5:0] tmp_fu_1534_p29;
wire   [5:0] tmp_fu_1534_p31;
wire   [5:0] tmp_fu_1534_p33;
wire   [5:0] tmp_fu_1534_p35;
wire   [5:0] tmp_fu_1534_p37;
wire   [5:0] tmp_fu_1534_p39;
wire   [5:0] tmp_fu_1534_p41;
wire   [5:0] tmp_fu_1534_p43;
wire   [5:0] tmp_fu_1534_p45;
wire   [5:0] tmp_fu_1534_p47;
wire   [5:0] tmp_fu_1534_p49;
wire   [5:0] tmp_fu_1534_p51;
wire   [5:0] tmp_fu_1534_p53;
wire   [5:0] tmp_fu_1534_p55;
wire   [5:0] tmp_fu_1534_p57;
wire   [5:0] tmp_fu_1534_p59;
wire   [5:0] tmp_fu_1534_p61;
wire   [5:0] tmp_fu_1534_p63;
wire  signed [5:0] tmp_fu_1534_p65;
wire  signed [5:0] tmp_fu_1534_p67;
wire  signed [5:0] tmp_fu_1534_p69;
wire  signed [5:0] tmp_fu_1534_p71;
wire  signed [5:0] tmp_fu_1534_p73;
wire  signed [5:0] tmp_fu_1534_p75;
wire  signed [5:0] tmp_fu_1534_p77;
wire  signed [5:0] tmp_fu_1534_p79;
wire  signed [5:0] tmp_fu_1534_p81;
wire  signed [5:0] tmp_fu_1534_p83;
wire  signed [5:0] tmp_fu_1534_p85;
wire  signed [5:0] tmp_fu_1534_p87;
wire  signed [5:0] tmp_fu_1534_p89;
wire  signed [5:0] tmp_fu_1534_p91;
wire  signed [5:0] tmp_fu_1534_p93;
wire  signed [5:0] tmp_fu_1534_p95;
wire  signed [5:0] tmp_fu_1534_p97;
wire  signed [5:0] tmp_fu_1534_p99;
wire  signed [5:0] tmp_fu_1534_p101;
wire  signed [5:0] tmp_fu_1534_p103;
wire  signed [5:0] tmp_fu_1534_p105;
wire  signed [5:0] tmp_fu_1534_p107;
wire  signed [5:0] tmp_fu_1534_p109;
wire  signed [5:0] tmp_fu_1534_p111;
wire  signed [5:0] tmp_fu_1534_p113;
wire  signed [5:0] tmp_fu_1534_p115;
wire  signed [5:0] tmp_fu_1534_p117;
wire  signed [5:0] tmp_fu_1534_p119;
wire  signed [5:0] tmp_fu_1534_p121;
wire  signed [5:0] tmp_fu_1534_p123;
wire  signed [5:0] tmp_fu_1534_p125;
wire  signed [5:0] tmp_fu_1534_p127;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 k_fu_384 = 8'd0;
#0 i_fu_388 = 31'd0;
#0 indvar_flatten_fu_392 = 34'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2093(
    .din0(O_fp32_0_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_fu_1266_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2094(
    .din0(O_fp32_1_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_1_fu_1271_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2095(
    .din0(O_fp32_2_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_2_fu_1276_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2096(
    .din0(O_fp32_3_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_3_fu_1281_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2097(
    .din0(O_fp32_4_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_4_fu_1286_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2098(
    .din0(O_fp32_5_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_5_fu_1291_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2099(
    .din0(O_fp32_6_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_6_fu_1296_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2100(
    .din0(O_fp32_7_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_7_fu_1301_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2101(
    .din0(O_fp32_8_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_8_fu_1306_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2102(
    .din0(O_fp32_9_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_9_fu_1311_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2103(
    .din0(O_fp32_10_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_s_fu_1316_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2104(
    .din0(O_fp32_11_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_10_fu_1321_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2105(
    .din0(O_fp32_12_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_11_fu_1326_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2106(
    .din0(O_fp32_13_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_12_fu_1331_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2107(
    .din0(O_fp32_14_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_13_fu_1336_p2)
);

flash_attention_kernel_fmul_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_primitive_dsp_1_U2108(
    .din0(O_fp32_15_q0),
    .din1(grp_fu_1346_p2),
    .dout(mul_14_fu_1341_p2)
);

flash_attention_kernel_fdiv_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_6_no_dsp_1_U2109(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1065353216),
    .din1(tmp_reg_2521),
    .ce(1'b1),
    .dout(grp_fu_1346_p2)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2110(
    .din0(mul_fu_1266_p2),
    .dout(conv_fu_1367_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2111(
    .din0(mul_1_fu_1271_p2),
    .dout(conv_1_fu_1371_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2112(
    .din0(mul_2_fu_1276_p2),
    .dout(conv_2_fu_1375_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2113(
    .din0(mul_3_fu_1281_p2),
    .dout(conv_3_fu_1379_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2114(
    .din0(mul_4_fu_1286_p2),
    .dout(conv_4_fu_1383_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2115(
    .din0(mul_5_fu_1291_p2),
    .dout(conv_5_fu_1387_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2116(
    .din0(mul_6_fu_1296_p2),
    .dout(conv_6_fu_1391_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2117(
    .din0(mul_7_fu_1301_p2),
    .dout(conv_7_fu_1395_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2118(
    .din0(mul_8_fu_1306_p2),
    .dout(conv_8_fu_1399_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2119(
    .din0(mul_9_fu_1311_p2),
    .dout(conv_9_fu_1403_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2120(
    .din0(mul_s_fu_1316_p2),
    .dout(conv_s_fu_1407_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2121(
    .din0(mul_10_fu_1321_p2),
    .dout(conv_10_fu_1411_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2122(
    .din0(mul_11_fu_1326_p2),
    .dout(conv_11_fu_1415_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2123(
    .din0(mul_12_fu_1331_p2),
    .dout(conv_12_fu_1419_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2124(
    .din0(mul_13_fu_1336_p2),
    .dout(conv_13_fu_1423_p1)
);

flash_attention_kernel_sptohp_32ns_16_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
sptohp_32ns_16_1_no_dsp_1_U2125(
    .din0(mul_14_fu_1341_p2),
    .dout(conv_14_fu_1427_p1)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_129_6_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 32 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 32 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 32 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 32 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 32 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 32 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 32 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 32 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 32 ),
    .CASE40( 6'h28 ),
    .din40_WIDTH( 32 ),
    .CASE41( 6'h29 ),
    .din41_WIDTH( 32 ),
    .CASE42( 6'h2A ),
    .din42_WIDTH( 32 ),
    .CASE43( 6'h2B ),
    .din43_WIDTH( 32 ),
    .CASE44( 6'h2C ),
    .din44_WIDTH( 32 ),
    .CASE45( 6'h2D ),
    .din45_WIDTH( 32 ),
    .CASE46( 6'h2E ),
    .din46_WIDTH( 32 ),
    .CASE47( 6'h2F ),
    .din47_WIDTH( 32 ),
    .CASE48( 6'h30 ),
    .din48_WIDTH( 32 ),
    .CASE49( 6'h31 ),
    .din49_WIDTH( 32 ),
    .CASE50( 6'h32 ),
    .din50_WIDTH( 32 ),
    .CASE51( 6'h33 ),
    .din51_WIDTH( 32 ),
    .CASE52( 6'h34 ),
    .din52_WIDTH( 32 ),
    .CASE53( 6'h35 ),
    .din53_WIDTH( 32 ),
    .CASE54( 6'h36 ),
    .din54_WIDTH( 32 ),
    .CASE55( 6'h37 ),
    .din55_WIDTH( 32 ),
    .CASE56( 6'h38 ),
    .din56_WIDTH( 32 ),
    .CASE57( 6'h39 ),
    .din57_WIDTH( 32 ),
    .CASE58( 6'h3A ),
    .din58_WIDTH( 32 ),
    .CASE59( 6'h3B ),
    .din59_WIDTH( 32 ),
    .CASE60( 6'h3C ),
    .din60_WIDTH( 32 ),
    .CASE61( 6'h3D ),
    .din61_WIDTH( 32 ),
    .CASE62( 6'h3E ),
    .din62_WIDTH( 32 ),
    .CASE63( 6'h3F ),
    .din63_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sparsemux_129_6_32_1_1_U2126(
    .din0(l_i_0_val),
    .din1(l_i_1_val),
    .din2(l_i_2_val),
    .din3(l_i_3_val),
    .din4(l_i_4_val),
    .din5(l_i_5_val),
    .din6(l_i_6_val),
    .din7(l_i_7_val),
    .din8(l_i_8_val),
    .din9(l_i_9_val),
    .din10(l_i_10_val),
    .din11(l_i_11_val),
    .din12(l_i_12_val),
    .din13(l_i_13_val),
    .din14(l_i_14_val),
    .din15(l_i_15_val),
    .din16(l_i_16_val),
    .din17(l_i_17_val),
    .din18(l_i_18_val),
    .din19(l_i_19_val),
    .din20(l_i_20_val),
    .din21(l_i_21_val),
    .din22(l_i_22_val),
    .din23(l_i_23_val),
    .din24(l_i_24_val),
    .din25(l_i_25_val),
    .din26(l_i_26_val),
    .din27(l_i_27_val),
    .din28(l_i_28_val),
    .din29(l_i_29_val),
    .din30(l_i_30_val),
    .din31(l_i_31_val),
    .din32(l_i_32_val),
    .din33(l_i_33_val),
    .din34(l_i_34_val),
    .din35(l_i_35_val),
    .din36(l_i_36_val),
    .din37(l_i_37_val),
    .din38(l_i_38_val),
    .din39(l_i_39_val),
    .din40(l_i_40_val),
    .din41(l_i_41_val),
    .din42(l_i_42_val),
    .din43(l_i_43_val),
    .din44(l_i_44_val),
    .din45(l_i_45_val),
    .din46(l_i_46_val),
    .din47(l_i_47_val),
    .din48(l_i_48_val),
    .din49(l_i_49_val),
    .din50(l_i_50_val),
    .din51(l_i_51_val),
    .din52(l_i_52_val),
    .din53(l_i_53_val),
    .din54(l_i_54_val),
    .din55(l_i_55_val),
    .din56(l_i_56_val),
    .din57(l_i_57_val),
    .din58(l_i_58_val),
    .din59(l_i_59_val),
    .din60(l_i_60_val),
    .din61(l_i_61_val),
    .din62(l_i_62_val),
    .din63(l_i_63_val),
    .def(tmp_fu_1534_p129),
    .sel(tmp_fu_1534_p130),
    .dout(tmp_fu_1534_p131)
);

flash_attention_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_388 <= 31'd0;
        end else if (((icmp_ln193_fu_1481_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_388 <= select_ln193_1_fu_1522_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_392 <= 34'd0;
        end else if (((icmp_ln193_fu_1481_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_392 <= add_ln193_1_fu_1475_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_384 <= 8'd0;
        end else if (((icmp_ln193_fu_1481_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            k_fu_384 <= add_ln197_fu_1744_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        lshr_ln_reg_2527 <= {{select_ln193_fu_1510_p3[6:4]}};
        tmp_reg_2521 <= tmp_fu_1534_p131;
        tmp_s_reg_2507[33 : 3] <= tmp_s_fu_1449_p3[33 : 3];
        trunc_ln193_1_reg_2516 <= trunc_ln193_1_fu_1530_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        conv_10_reg_2698 <= conv_10_fu_1411_p1;
        conv_11_reg_2704 <= conv_11_fu_1415_p1;
        conv_12_reg_2710 <= conv_12_fu_1419_p1;
        conv_13_reg_2716 <= conv_13_fu_1423_p1;
        conv_14_reg_2722 <= conv_14_fu_1427_p1;
        conv_1_reg_2638 <= conv_1_fu_1371_p1;
        conv_2_reg_2644 <= conv_2_fu_1375_p1;
        conv_3_reg_2650 <= conv_3_fu_1379_p1;
        conv_4_reg_2656 <= conv_4_fu_1383_p1;
        conv_5_reg_2662 <= conv_5_fu_1387_p1;
        conv_6_reg_2668 <= conv_6_fu_1391_p1;
        conv_7_reg_2674 <= conv_7_fu_1395_p1;
        conv_8_reg_2680 <= conv_8_fu_1399_p1;
        conv_9_reg_2686 <= conv_9_fu_1403_p1;
        conv_reg_2632 <= conv_fu_1367_p1;
        conv_s_reg_2692 <= conv_s_fu_1407_p1;
        lshr_ln_reg_2527_pp0_iter2_reg <= lshr_ln_reg_2527;
        lshr_ln_reg_2527_pp0_iter3_reg <= lshr_ln_reg_2527_pp0_iter2_reg;
        lshr_ln_reg_2527_pp0_iter4_reg <= lshr_ln_reg_2527_pp0_iter3_reg;
        lshr_ln_reg_2527_pp0_iter5_reg <= lshr_ln_reg_2527_pp0_iter4_reg;
        trunc_ln193_1_reg_2516_pp0_iter2_reg <= trunc_ln193_1_reg_2516;
        trunc_ln193_1_reg_2516_pp0_iter3_reg <= trunc_ln193_1_reg_2516_pp0_iter2_reg;
        trunc_ln193_1_reg_2516_pp0_iter4_reg <= trunc_ln193_1_reg_2516_pp0_iter3_reg;
        trunc_ln193_1_reg_2516_pp0_iter5_reg <= trunc_ln193_1_reg_2516_pp0_iter4_reg;
        zext_ln200_reg_2532[8 : 0] <= zext_ln200_fu_1778_p1[8 : 0];
        zext_ln200_reg_2532_pp0_iter7_reg[8 : 0] <= zext_ln200_reg_2532[8 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_0_ce1_local = 1'b1;
    end else begin
        O_fp16_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_0_we1_local = 1'b1;
    end else begin
        O_fp16_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_10_ce1_local = 1'b1;
    end else begin
        O_fp16_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_10_we1_local = 1'b1;
    end else begin
        O_fp16_10_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_11_ce1_local = 1'b1;
    end else begin
        O_fp16_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_11_we1_local = 1'b1;
    end else begin
        O_fp16_11_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_12_ce1_local = 1'b1;
    end else begin
        O_fp16_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_12_we1_local = 1'b1;
    end else begin
        O_fp16_12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_13_ce1_local = 1'b1;
    end else begin
        O_fp16_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_13_we1_local = 1'b1;
    end else begin
        O_fp16_13_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_14_ce1_local = 1'b1;
    end else begin
        O_fp16_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_14_we1_local = 1'b1;
    end else begin
        O_fp16_14_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_15_ce1_local = 1'b1;
    end else begin
        O_fp16_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_15_we1_local = 1'b1;
    end else begin
        O_fp16_15_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_1_ce1_local = 1'b1;
    end else begin
        O_fp16_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_1_we1_local = 1'b1;
    end else begin
        O_fp16_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_2_ce1_local = 1'b1;
    end else begin
        O_fp16_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_2_we1_local = 1'b1;
    end else begin
        O_fp16_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_3_ce1_local = 1'b1;
    end else begin
        O_fp16_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_3_we1_local = 1'b1;
    end else begin
        O_fp16_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_4_ce1_local = 1'b1;
    end else begin
        O_fp16_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_4_we1_local = 1'b1;
    end else begin
        O_fp16_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_5_ce1_local = 1'b1;
    end else begin
        O_fp16_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_5_we1_local = 1'b1;
    end else begin
        O_fp16_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_6_ce1_local = 1'b1;
    end else begin
        O_fp16_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_6_we1_local = 1'b1;
    end else begin
        O_fp16_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_7_ce1_local = 1'b1;
    end else begin
        O_fp16_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_7_we1_local = 1'b1;
    end else begin
        O_fp16_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_8_ce1_local = 1'b1;
    end else begin
        O_fp16_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_8_we1_local = 1'b1;
    end else begin
        O_fp16_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_9_ce1_local = 1'b1;
    end else begin
        O_fp16_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        O_fp16_9_we1_local = 1'b1;
    end else begin
        O_fp16_9_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_0_ce0_local = 1'b1;
    end else begin
        O_fp32_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_10_ce0_local = 1'b1;
    end else begin
        O_fp32_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_11_ce0_local = 1'b1;
    end else begin
        O_fp32_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_12_ce0_local = 1'b1;
    end else begin
        O_fp32_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_13_ce0_local = 1'b1;
    end else begin
        O_fp32_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_14_ce0_local = 1'b1;
    end else begin
        O_fp32_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_15_ce0_local = 1'b1;
    end else begin
        O_fp32_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_1_ce0_local = 1'b1;
    end else begin
        O_fp32_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_2_ce0_local = 1'b1;
    end else begin
        O_fp32_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_3_ce0_local = 1'b1;
    end else begin
        O_fp32_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_4_ce0_local = 1'b1;
    end else begin
        O_fp32_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_5_ce0_local = 1'b1;
    end else begin
        O_fp32_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_6_ce0_local = 1'b1;
    end else begin
        O_fp32_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_7_ce0_local = 1'b1;
    end else begin
        O_fp32_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_8_ce0_local = 1'b1;
    end else begin
        O_fp32_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        O_fp32_9_ce0_local = 1'b1;
    end else begin
        O_fp32_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln193_fu_1481_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign O_fp16_0_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_0_ce1 = O_fp16_0_ce1_local;

assign O_fp16_0_d1 = conv_reg_2632;

assign O_fp16_0_we1 = O_fp16_0_we1_local;

assign O_fp16_10_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_10_ce1 = O_fp16_10_ce1_local;

assign O_fp16_10_d1 = conv_s_reg_2692;

assign O_fp16_10_we1 = O_fp16_10_we1_local;

assign O_fp16_11_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_11_ce1 = O_fp16_11_ce1_local;

assign O_fp16_11_d1 = conv_10_reg_2698;

assign O_fp16_11_we1 = O_fp16_11_we1_local;

assign O_fp16_12_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_12_ce1 = O_fp16_12_ce1_local;

assign O_fp16_12_d1 = conv_11_reg_2704;

assign O_fp16_12_we1 = O_fp16_12_we1_local;

assign O_fp16_13_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_13_ce1 = O_fp16_13_ce1_local;

assign O_fp16_13_d1 = conv_12_reg_2710;

assign O_fp16_13_we1 = O_fp16_13_we1_local;

assign O_fp16_14_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_14_ce1 = O_fp16_14_ce1_local;

assign O_fp16_14_d1 = conv_13_reg_2716;

assign O_fp16_14_we1 = O_fp16_14_we1_local;

assign O_fp16_15_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_15_ce1 = O_fp16_15_ce1_local;

assign O_fp16_15_d1 = conv_14_reg_2722;

assign O_fp16_15_we1 = O_fp16_15_we1_local;

assign O_fp16_1_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_1_ce1 = O_fp16_1_ce1_local;

assign O_fp16_1_d1 = conv_1_reg_2638;

assign O_fp16_1_we1 = O_fp16_1_we1_local;

assign O_fp16_2_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_2_ce1 = O_fp16_2_ce1_local;

assign O_fp16_2_d1 = conv_2_reg_2644;

assign O_fp16_2_we1 = O_fp16_2_we1_local;

assign O_fp16_3_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_3_ce1 = O_fp16_3_ce1_local;

assign O_fp16_3_d1 = conv_3_reg_2650;

assign O_fp16_3_we1 = O_fp16_3_we1_local;

assign O_fp16_4_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_4_ce1 = O_fp16_4_ce1_local;

assign O_fp16_4_d1 = conv_4_reg_2656;

assign O_fp16_4_we1 = O_fp16_4_we1_local;

assign O_fp16_5_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_5_ce1 = O_fp16_5_ce1_local;

assign O_fp16_5_d1 = conv_5_reg_2662;

assign O_fp16_5_we1 = O_fp16_5_we1_local;

assign O_fp16_6_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_6_ce1 = O_fp16_6_ce1_local;

assign O_fp16_6_d1 = conv_6_reg_2668;

assign O_fp16_6_we1 = O_fp16_6_we1_local;

assign O_fp16_7_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_7_ce1 = O_fp16_7_ce1_local;

assign O_fp16_7_d1 = conv_7_reg_2674;

assign O_fp16_7_we1 = O_fp16_7_we1_local;

assign O_fp16_8_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_8_ce1 = O_fp16_8_ce1_local;

assign O_fp16_8_d1 = conv_8_reg_2680;

assign O_fp16_8_we1 = O_fp16_8_we1_local;

assign O_fp16_9_address1 = zext_ln200_reg_2532_pp0_iter7_reg;

assign O_fp16_9_ce1 = O_fp16_9_ce1_local;

assign O_fp16_9_d1 = conv_9_reg_2686;

assign O_fp16_9_we1 = O_fp16_9_we1_local;

assign O_fp32_0_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_0_ce0 = O_fp32_0_ce0_local;

assign O_fp32_10_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_10_ce0 = O_fp32_10_ce0_local;

assign O_fp32_11_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_11_ce0 = O_fp32_11_ce0_local;

assign O_fp32_12_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_12_ce0 = O_fp32_12_ce0_local;

assign O_fp32_13_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_13_ce0 = O_fp32_13_ce0_local;

assign O_fp32_14_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_14_ce0 = O_fp32_14_ce0_local;

assign O_fp32_15_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_15_ce0 = O_fp32_15_ce0_local;

assign O_fp32_1_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_1_ce0 = O_fp32_1_ce0_local;

assign O_fp32_2_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_2_ce0 = O_fp32_2_ce0_local;

assign O_fp32_3_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_3_ce0 = O_fp32_3_ce0_local;

assign O_fp32_4_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_4_ce0 = O_fp32_4_ce0_local;

assign O_fp32_5_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_5_ce0 = O_fp32_5_ce0_local;

assign O_fp32_6_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_6_ce0 = O_fp32_6_ce0_local;

assign O_fp32_7_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_7_ce0 = O_fp32_7_ce0_local;

assign O_fp32_8_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_8_ce0 = O_fp32_8_ce0_local;

assign O_fp32_9_address0 = zext_ln200_fu_1778_p1;

assign O_fp32_9_ce0 = O_fp32_9_ce0_local;

assign add_ln193_1_fu_1475_p2 = (indvar_flatten_fu_392 + 34'd1);

assign add_ln193_fu_1496_p2 = (i_fu_388 + 31'd1);

assign add_ln197_fu_1744_p2 = (zext_ln193_fu_1518_p1 + 8'd16);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign empty_75_fu_1435_p2 = (($signed(br_actual) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_76_fu_1441_p3 = ((empty_75_fu_1435_p2[0:0] == 1'b1) ? empty_fu_1431_p1 : 31'd0);

assign empty_fu_1431_p1 = br_actual[30:0];

assign icmp_ln193_fu_1481_p2 = ((indvar_flatten_fu_392 == tmp_s_reg_2507) ? 1'b1 : 1'b0);

assign select_ln193_1_fu_1522_p3 = ((tmp_3_fu_1502_p3[0:0] == 1'b1) ? add_ln193_fu_1496_p2 : i_fu_388);

assign select_ln193_fu_1510_p3 = ((tmp_3_fu_1502_p3[0:0] == 1'b1) ? 7'd0 : trunc_ln193_fu_1492_p1);

assign tmp_24_fu_1772_p3 = {{trunc_ln193_1_reg_2516_pp0_iter5_reg}, {lshr_ln_reg_2527_pp0_iter5_reg}};

assign tmp_3_fu_1502_p3 = k_fu_384[32'd7];

assign tmp_fu_1534_p129 = 'bx;

assign tmp_fu_1534_p130 = select_ln193_1_fu_1522_p3[5:0];

assign tmp_s_fu_1449_p3 = {{empty_76_fu_1441_p3}, {3'd0}};

assign trunc_ln193_1_fu_1530_p1 = select_ln193_1_fu_1522_p3[5:0];

assign trunc_ln193_fu_1492_p1 = k_fu_384[6:0];

assign zext_ln193_fu_1518_p1 = select_ln193_fu_1510_p3;

assign zext_ln200_fu_1778_p1 = tmp_24_fu_1772_p3;

always @ (posedge ap_clk) begin
    tmp_s_reg_2507[2:0] <= 3'b000;
    zext_ln200_reg_2532[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln200_reg_2532_pp0_iter7_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //flash_attention_kernel_normalize_output
