// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_kernel_store_stats_fp32_Pipeline_STORE_STATS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_l_0_AWVALID,
        m_axi_gmem_l_0_AWREADY,
        m_axi_gmem_l_0_AWADDR,
        m_axi_gmem_l_0_AWID,
        m_axi_gmem_l_0_AWLEN,
        m_axi_gmem_l_0_AWSIZE,
        m_axi_gmem_l_0_AWBURST,
        m_axi_gmem_l_0_AWLOCK,
        m_axi_gmem_l_0_AWCACHE,
        m_axi_gmem_l_0_AWPROT,
        m_axi_gmem_l_0_AWQOS,
        m_axi_gmem_l_0_AWREGION,
        m_axi_gmem_l_0_AWUSER,
        m_axi_gmem_l_0_WVALID,
        m_axi_gmem_l_0_WREADY,
        m_axi_gmem_l_0_WDATA,
        m_axi_gmem_l_0_WSTRB,
        m_axi_gmem_l_0_WLAST,
        m_axi_gmem_l_0_WID,
        m_axi_gmem_l_0_WUSER,
        m_axi_gmem_l_0_ARVALID,
        m_axi_gmem_l_0_ARREADY,
        m_axi_gmem_l_0_ARADDR,
        m_axi_gmem_l_0_ARID,
        m_axi_gmem_l_0_ARLEN,
        m_axi_gmem_l_0_ARSIZE,
        m_axi_gmem_l_0_ARBURST,
        m_axi_gmem_l_0_ARLOCK,
        m_axi_gmem_l_0_ARCACHE,
        m_axi_gmem_l_0_ARPROT,
        m_axi_gmem_l_0_ARQOS,
        m_axi_gmem_l_0_ARREGION,
        m_axi_gmem_l_0_ARUSER,
        m_axi_gmem_l_0_RVALID,
        m_axi_gmem_l_0_RREADY,
        m_axi_gmem_l_0_RDATA,
        m_axi_gmem_l_0_RLAST,
        m_axi_gmem_l_0_RID,
        m_axi_gmem_l_0_RFIFONUM,
        m_axi_gmem_l_0_RUSER,
        m_axi_gmem_l_0_RRESP,
        m_axi_gmem_l_0_BVALID,
        m_axi_gmem_l_0_BREADY,
        m_axi_gmem_l_0_BRESP,
        m_axi_gmem_l_0_BID,
        m_axi_gmem_l_0_BUSER,
        num_elements,
        total_beats,
        sext_ln272,
        stats_0_val,
        stats_16_val,
        stats_32_val,
        stats_48_val,
        stats_1_val,
        stats_17_val,
        stats_33_val,
        stats_49_val,
        stats_2_val,
        stats_18_val,
        stats_34_val,
        stats_50_val,
        stats_3_val,
        stats_19_val,
        stats_35_val,
        stats_51_val,
        stats_4_val,
        stats_20_val,
        stats_36_val,
        stats_52_val,
        stats_5_val,
        stats_21_val,
        stats_37_val,
        stats_53_val,
        stats_6_val,
        stats_22_val,
        stats_38_val,
        stats_54_val,
        stats_7_val,
        stats_23_val,
        stats_39_val,
        stats_55_val,
        stats_8_val,
        stats_24_val,
        stats_40_val,
        stats_56_val,
        stats_9_val,
        stats_25_val,
        stats_41_val,
        stats_57_val,
        stats_10_val,
        stats_26_val,
        stats_42_val,
        stats_58_val,
        stats_11_val,
        stats_27_val,
        stats_43_val,
        stats_59_val,
        stats_12_val,
        stats_28_val,
        stats_44_val,
        stats_60_val,
        stats_13_val,
        stats_29_val,
        stats_45_val,
        stats_61_val,
        stats_14_val,
        stats_30_val,
        stats_46_val,
        stats_62_val,
        stats_15_val,
        stats_31_val,
        stats_47_val,
        stats_63_val
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_l_0_AWVALID;
input   m_axi_gmem_l_0_AWREADY;
output  [63:0] m_axi_gmem_l_0_AWADDR;
output  [0:0] m_axi_gmem_l_0_AWID;
output  [31:0] m_axi_gmem_l_0_AWLEN;
output  [2:0] m_axi_gmem_l_0_AWSIZE;
output  [1:0] m_axi_gmem_l_0_AWBURST;
output  [1:0] m_axi_gmem_l_0_AWLOCK;
output  [3:0] m_axi_gmem_l_0_AWCACHE;
output  [2:0] m_axi_gmem_l_0_AWPROT;
output  [3:0] m_axi_gmem_l_0_AWQOS;
output  [3:0] m_axi_gmem_l_0_AWREGION;
output  [0:0] m_axi_gmem_l_0_AWUSER;
output   m_axi_gmem_l_0_WVALID;
input   m_axi_gmem_l_0_WREADY;
output  [511:0] m_axi_gmem_l_0_WDATA;
output  [63:0] m_axi_gmem_l_0_WSTRB;
output   m_axi_gmem_l_0_WLAST;
output  [0:0] m_axi_gmem_l_0_WID;
output  [0:0] m_axi_gmem_l_0_WUSER;
output   m_axi_gmem_l_0_ARVALID;
input   m_axi_gmem_l_0_ARREADY;
output  [63:0] m_axi_gmem_l_0_ARADDR;
output  [0:0] m_axi_gmem_l_0_ARID;
output  [31:0] m_axi_gmem_l_0_ARLEN;
output  [2:0] m_axi_gmem_l_0_ARSIZE;
output  [1:0] m_axi_gmem_l_0_ARBURST;
output  [1:0] m_axi_gmem_l_0_ARLOCK;
output  [3:0] m_axi_gmem_l_0_ARCACHE;
output  [2:0] m_axi_gmem_l_0_ARPROT;
output  [3:0] m_axi_gmem_l_0_ARQOS;
output  [3:0] m_axi_gmem_l_0_ARREGION;
output  [0:0] m_axi_gmem_l_0_ARUSER;
input   m_axi_gmem_l_0_RVALID;
output   m_axi_gmem_l_0_RREADY;
input  [511:0] m_axi_gmem_l_0_RDATA;
input   m_axi_gmem_l_0_RLAST;
input  [0:0] m_axi_gmem_l_0_RID;
input  [8:0] m_axi_gmem_l_0_RFIFONUM;
input  [0:0] m_axi_gmem_l_0_RUSER;
input  [1:0] m_axi_gmem_l_0_RRESP;
input   m_axi_gmem_l_0_BVALID;
output   m_axi_gmem_l_0_BREADY;
input  [1:0] m_axi_gmem_l_0_BRESP;
input  [0:0] m_axi_gmem_l_0_BID;
input  [0:0] m_axi_gmem_l_0_BUSER;
input  [31:0] num_elements;
input  [28:0] total_beats;
input  [57:0] sext_ln272;
input  [31:0] stats_0_val;
input  [31:0] stats_16_val;
input  [31:0] stats_32_val;
input  [31:0] stats_48_val;
input  [31:0] stats_1_val;
input  [31:0] stats_17_val;
input  [31:0] stats_33_val;
input  [31:0] stats_49_val;
input  [31:0] stats_2_val;
input  [31:0] stats_18_val;
input  [31:0] stats_34_val;
input  [31:0] stats_50_val;
input  [31:0] stats_3_val;
input  [31:0] stats_19_val;
input  [31:0] stats_35_val;
input  [31:0] stats_51_val;
input  [31:0] stats_4_val;
input  [31:0] stats_20_val;
input  [31:0] stats_36_val;
input  [31:0] stats_52_val;
input  [31:0] stats_5_val;
input  [31:0] stats_21_val;
input  [31:0] stats_37_val;
input  [31:0] stats_53_val;
input  [31:0] stats_6_val;
input  [31:0] stats_22_val;
input  [31:0] stats_38_val;
input  [31:0] stats_54_val;
input  [31:0] stats_7_val;
input  [31:0] stats_23_val;
input  [31:0] stats_39_val;
input  [31:0] stats_55_val;
input  [31:0] stats_8_val;
input  [31:0] stats_24_val;
input  [31:0] stats_40_val;
input  [31:0] stats_56_val;
input  [31:0] stats_9_val;
input  [31:0] stats_25_val;
input  [31:0] stats_41_val;
input  [31:0] stats_57_val;
input  [31:0] stats_10_val;
input  [31:0] stats_26_val;
input  [31:0] stats_42_val;
input  [31:0] stats_58_val;
input  [31:0] stats_11_val;
input  [31:0] stats_27_val;
input  [31:0] stats_43_val;
input  [31:0] stats_59_val;
input  [31:0] stats_12_val;
input  [31:0] stats_28_val;
input  [31:0] stats_44_val;
input  [31:0] stats_60_val;
input  [31:0] stats_13_val;
input  [31:0] stats_29_val;
input  [31:0] stats_45_val;
input  [31:0] stats_61_val;
input  [31:0] stats_14_val;
input  [31:0] stats_30_val;
input  [31:0] stats_46_val;
input  [31:0] stats_62_val;
input  [31:0] stats_15_val;
input  [31:0] stats_31_val;
input  [31:0] stats_47_val;
input  [31:0] stats_63_val;

reg ap_idle;
reg m_axi_gmem_l_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln272_fu_674_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_l_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [31:0] empty_fu_730_p3;
reg   [31:0] empty_reg_1603;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] empty_58_fu_784_p3;
reg   [31:0] empty_58_reg_1608;
wire   [31:0] empty_59_fu_838_p3;
reg   [31:0] empty_59_reg_1613;
wire   [31:0] empty_60_fu_892_p3;
reg   [31:0] empty_60_reg_1618;
wire   [31:0] empty_61_fu_946_p3;
reg   [31:0] empty_61_reg_1623;
wire   [31:0] empty_62_fu_1000_p3;
reg   [31:0] empty_62_reg_1628;
wire   [31:0] empty_63_fu_1054_p3;
reg   [31:0] empty_63_reg_1633;
wire   [31:0] empty_64_fu_1108_p3;
reg   [31:0] empty_64_reg_1638;
wire   [31:0] empty_65_fu_1162_p3;
reg   [31:0] empty_65_reg_1643;
wire   [31:0] empty_66_fu_1216_p3;
reg   [31:0] empty_66_reg_1648;
wire   [31:0] empty_67_fu_1270_p3;
reg   [31:0] empty_67_reg_1653;
wire   [31:0] empty_68_fu_1324_p3;
reg   [31:0] empty_68_reg_1658;
wire   [31:0] empty_69_fu_1378_p3;
reg   [31:0] empty_69_reg_1663;
wire   [31:0] empty_70_fu_1432_p3;
reg   [31:0] empty_70_reg_1668;
wire   [31:0] empty_71_fu_1486_p3;
reg   [31:0] empty_71_reg_1673;
wire   [31:0] empty_72_fu_1540_p3;
reg   [31:0] empty_72_reg_1678;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [26:0] b_fu_238;
wire   [26:0] add_ln272_fu_664_p2;
wire    ap_loop_init;
reg   [26:0] ap_sig_allocacmp_b_1;
wire    ap_block_pp0_stage0;
wire   [28:0] zext_ln272_fu_670_p1;
wire   [30:0] tmp_15_fu_684_p3;
wire   [31:0] zext_ln279_fu_692_p1;
wire   [31:0] tmp_fu_702_p9;
wire   [1:0] trunc_ln272_fu_680_p1;
wire   [31:0] tmp_fu_702_p11;
wire   [0:0] icmp_ln279_fu_696_p2;
wire   [31:0] bitcast_ln279_fu_726_p1;
wire   [30:0] or_ln_fu_738_p3;
wire   [31:0] zext_ln279_1_fu_746_p1;
wire   [31:0] tmp_7_fu_756_p9;
wire   [31:0] tmp_7_fu_756_p11;
wire   [0:0] icmp_ln279_1_fu_750_p2;
wire   [31:0] bitcast_ln279_1_fu_780_p1;
wire   [30:0] or_ln278_1_fu_792_p3;
wire   [31:0] zext_ln279_2_fu_800_p1;
wire   [31:0] tmp_8_fu_810_p9;
wire   [31:0] tmp_8_fu_810_p11;
wire   [0:0] icmp_ln279_2_fu_804_p2;
wire   [31:0] bitcast_ln279_2_fu_834_p1;
wire   [30:0] or_ln278_2_fu_846_p3;
wire   [31:0] zext_ln279_3_fu_854_p1;
wire   [31:0] tmp_9_fu_864_p9;
wire   [31:0] tmp_9_fu_864_p11;
wire   [0:0] icmp_ln279_3_fu_858_p2;
wire   [31:0] bitcast_ln279_3_fu_888_p1;
wire   [30:0] or_ln278_3_fu_900_p3;
wire   [31:0] zext_ln279_4_fu_908_p1;
wire   [31:0] tmp_s_fu_918_p9;
wire   [31:0] tmp_s_fu_918_p11;
wire   [0:0] icmp_ln279_4_fu_912_p2;
wire   [31:0] bitcast_ln279_4_fu_942_p1;
wire   [30:0] or_ln278_4_fu_954_p3;
wire   [31:0] zext_ln279_5_fu_962_p1;
wire   [31:0] tmp_1_fu_972_p9;
wire   [31:0] tmp_1_fu_972_p11;
wire   [0:0] icmp_ln279_5_fu_966_p2;
wire   [31:0] bitcast_ln279_5_fu_996_p1;
wire   [30:0] or_ln278_5_fu_1008_p3;
wire   [31:0] zext_ln279_6_fu_1016_p1;
wire   [31:0] tmp_2_fu_1026_p9;
wire   [31:0] tmp_2_fu_1026_p11;
wire   [0:0] icmp_ln279_6_fu_1020_p2;
wire   [31:0] bitcast_ln279_6_fu_1050_p1;
wire   [30:0] or_ln278_6_fu_1062_p3;
wire   [31:0] zext_ln279_7_fu_1070_p1;
wire   [31:0] tmp_3_fu_1080_p9;
wire   [31:0] tmp_3_fu_1080_p11;
wire   [0:0] icmp_ln279_7_fu_1074_p2;
wire   [31:0] bitcast_ln279_7_fu_1104_p1;
wire   [30:0] or_ln278_7_fu_1116_p3;
wire   [31:0] zext_ln279_8_fu_1124_p1;
wire   [31:0] tmp_4_fu_1134_p9;
wire   [31:0] tmp_4_fu_1134_p11;
wire   [0:0] icmp_ln279_8_fu_1128_p2;
wire   [31:0] bitcast_ln279_8_fu_1158_p1;
wire   [30:0] or_ln278_8_fu_1170_p3;
wire   [31:0] zext_ln279_9_fu_1178_p1;
wire   [31:0] tmp_5_fu_1188_p9;
wire   [31:0] tmp_5_fu_1188_p11;
wire   [0:0] icmp_ln279_9_fu_1182_p2;
wire   [31:0] bitcast_ln279_9_fu_1212_p1;
wire   [30:0] or_ln278_9_fu_1224_p3;
wire   [31:0] zext_ln279_10_fu_1232_p1;
wire   [31:0] tmp_6_fu_1242_p9;
wire   [31:0] tmp_6_fu_1242_p11;
wire   [0:0] icmp_ln279_10_fu_1236_p2;
wire   [31:0] bitcast_ln279_10_fu_1266_p1;
wire   [30:0] or_ln278_s_fu_1278_p3;
wire   [31:0] zext_ln279_11_fu_1286_p1;
wire   [31:0] tmp_10_fu_1296_p9;
wire   [31:0] tmp_10_fu_1296_p11;
wire   [0:0] icmp_ln279_11_fu_1290_p2;
wire   [31:0] bitcast_ln279_11_fu_1320_p1;
wire   [30:0] or_ln278_10_fu_1332_p3;
wire   [31:0] zext_ln279_12_fu_1340_p1;
wire   [31:0] tmp_11_fu_1350_p9;
wire   [31:0] tmp_11_fu_1350_p11;
wire   [0:0] icmp_ln279_12_fu_1344_p2;
wire   [31:0] bitcast_ln279_12_fu_1374_p1;
wire   [30:0] or_ln278_11_fu_1386_p3;
wire   [31:0] zext_ln279_13_fu_1394_p1;
wire   [31:0] tmp_12_fu_1404_p9;
wire   [31:0] tmp_12_fu_1404_p11;
wire   [0:0] icmp_ln279_13_fu_1398_p2;
wire   [31:0] bitcast_ln279_13_fu_1428_p1;
wire   [30:0] or_ln278_12_fu_1440_p3;
wire   [31:0] zext_ln279_14_fu_1448_p1;
wire   [31:0] tmp_13_fu_1458_p9;
wire   [31:0] tmp_13_fu_1458_p11;
wire   [0:0] icmp_ln279_14_fu_1452_p2;
wire   [31:0] bitcast_ln279_14_fu_1482_p1;
wire   [30:0] or_ln278_13_fu_1494_p3;
wire   [31:0] zext_ln279_15_fu_1502_p1;
wire   [31:0] tmp_14_fu_1512_p9;
wire   [31:0] tmp_14_fu_1512_p11;
wire   [0:0] icmp_ln279_15_fu_1506_p2;
wire   [31:0] bitcast_ln279_15_fu_1536_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_fu_702_p1;
wire   [1:0] tmp_fu_702_p3;
wire  signed [1:0] tmp_fu_702_p5;
wire  signed [1:0] tmp_fu_702_p7;
wire   [1:0] tmp_7_fu_756_p1;
wire   [1:0] tmp_7_fu_756_p3;
wire  signed [1:0] tmp_7_fu_756_p5;
wire  signed [1:0] tmp_7_fu_756_p7;
wire   [1:0] tmp_8_fu_810_p1;
wire   [1:0] tmp_8_fu_810_p3;
wire  signed [1:0] tmp_8_fu_810_p5;
wire  signed [1:0] tmp_8_fu_810_p7;
wire   [1:0] tmp_9_fu_864_p1;
wire   [1:0] tmp_9_fu_864_p3;
wire  signed [1:0] tmp_9_fu_864_p5;
wire  signed [1:0] tmp_9_fu_864_p7;
wire   [1:0] tmp_s_fu_918_p1;
wire   [1:0] tmp_s_fu_918_p3;
wire  signed [1:0] tmp_s_fu_918_p5;
wire  signed [1:0] tmp_s_fu_918_p7;
wire   [1:0] tmp_1_fu_972_p1;
wire   [1:0] tmp_1_fu_972_p3;
wire  signed [1:0] tmp_1_fu_972_p5;
wire  signed [1:0] tmp_1_fu_972_p7;
wire   [1:0] tmp_2_fu_1026_p1;
wire   [1:0] tmp_2_fu_1026_p3;
wire  signed [1:0] tmp_2_fu_1026_p5;
wire  signed [1:0] tmp_2_fu_1026_p7;
wire   [1:0] tmp_3_fu_1080_p1;
wire   [1:0] tmp_3_fu_1080_p3;
wire  signed [1:0] tmp_3_fu_1080_p5;
wire  signed [1:0] tmp_3_fu_1080_p7;
wire   [1:0] tmp_4_fu_1134_p1;
wire   [1:0] tmp_4_fu_1134_p3;
wire  signed [1:0] tmp_4_fu_1134_p5;
wire  signed [1:0] tmp_4_fu_1134_p7;
wire   [1:0] tmp_5_fu_1188_p1;
wire   [1:0] tmp_5_fu_1188_p3;
wire  signed [1:0] tmp_5_fu_1188_p5;
wire  signed [1:0] tmp_5_fu_1188_p7;
wire   [1:0] tmp_6_fu_1242_p1;
wire   [1:0] tmp_6_fu_1242_p3;
wire  signed [1:0] tmp_6_fu_1242_p5;
wire  signed [1:0] tmp_6_fu_1242_p7;
wire   [1:0] tmp_10_fu_1296_p1;
wire   [1:0] tmp_10_fu_1296_p3;
wire  signed [1:0] tmp_10_fu_1296_p5;
wire  signed [1:0] tmp_10_fu_1296_p7;
wire   [1:0] tmp_11_fu_1350_p1;
wire   [1:0] tmp_11_fu_1350_p3;
wire  signed [1:0] tmp_11_fu_1350_p5;
wire  signed [1:0] tmp_11_fu_1350_p7;
wire   [1:0] tmp_12_fu_1404_p1;
wire   [1:0] tmp_12_fu_1404_p3;
wire  signed [1:0] tmp_12_fu_1404_p5;
wire  signed [1:0] tmp_12_fu_1404_p7;
wire   [1:0] tmp_13_fu_1458_p1;
wire   [1:0] tmp_13_fu_1458_p3;
wire  signed [1:0] tmp_13_fu_1458_p5;
wire  signed [1:0] tmp_13_fu_1458_p7;
wire   [1:0] tmp_14_fu_1512_p1;
wire   [1:0] tmp_14_fu_1512_p3;
wire  signed [1:0] tmp_14_fu_1512_p5;
wire  signed [1:0] tmp_14_fu_1512_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 b_fu_238 = 27'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2264(
    .din0(stats_0_val),
    .din1(stats_16_val),
    .din2(stats_32_val),
    .din3(stats_48_val),
    .def(tmp_fu_702_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_fu_702_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2265(
    .din0(stats_1_val),
    .din1(stats_17_val),
    .din2(stats_33_val),
    .din3(stats_49_val),
    .def(tmp_7_fu_756_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_7_fu_756_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2266(
    .din0(stats_2_val),
    .din1(stats_18_val),
    .din2(stats_34_val),
    .din3(stats_50_val),
    .def(tmp_8_fu_810_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_8_fu_810_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2267(
    .din0(stats_3_val),
    .din1(stats_19_val),
    .din2(stats_35_val),
    .din3(stats_51_val),
    .def(tmp_9_fu_864_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_9_fu_864_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2268(
    .din0(stats_4_val),
    .din1(stats_20_val),
    .din2(stats_36_val),
    .din3(stats_52_val),
    .def(tmp_s_fu_918_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_s_fu_918_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2269(
    .din0(stats_5_val),
    .din1(stats_21_val),
    .din2(stats_37_val),
    .din3(stats_53_val),
    .def(tmp_1_fu_972_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_1_fu_972_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2270(
    .din0(stats_6_val),
    .din1(stats_22_val),
    .din2(stats_38_val),
    .din3(stats_54_val),
    .def(tmp_2_fu_1026_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_2_fu_1026_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2271(
    .din0(stats_7_val),
    .din1(stats_23_val),
    .din2(stats_39_val),
    .din3(stats_55_val),
    .def(tmp_3_fu_1080_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_3_fu_1080_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2272(
    .din0(stats_8_val),
    .din1(stats_24_val),
    .din2(stats_40_val),
    .din3(stats_56_val),
    .def(tmp_4_fu_1134_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_4_fu_1134_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2273(
    .din0(stats_9_val),
    .din1(stats_25_val),
    .din2(stats_41_val),
    .din3(stats_57_val),
    .def(tmp_5_fu_1188_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_5_fu_1188_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2274(
    .din0(stats_10_val),
    .din1(stats_26_val),
    .din2(stats_42_val),
    .din3(stats_58_val),
    .def(tmp_6_fu_1242_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_6_fu_1242_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2275(
    .din0(stats_11_val),
    .din1(stats_27_val),
    .din2(stats_43_val),
    .din3(stats_59_val),
    .def(tmp_10_fu_1296_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_10_fu_1296_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2276(
    .din0(stats_12_val),
    .din1(stats_28_val),
    .din2(stats_44_val),
    .din3(stats_60_val),
    .def(tmp_11_fu_1350_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_11_fu_1350_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2277(
    .din0(stats_13_val),
    .din1(stats_29_val),
    .din2(stats_45_val),
    .din3(stats_61_val),
    .def(tmp_12_fu_1404_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_12_fu_1404_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2278(
    .din0(stats_14_val),
    .din1(stats_30_val),
    .din2(stats_46_val),
    .din3(stats_62_val),
    .def(tmp_13_fu_1458_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_13_fu_1458_p11)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2279(
    .din0(stats_15_val),
    .din1(stats_31_val),
    .din2(stats_47_val),
    .din3(stats_63_val),
    .def(tmp_14_fu_1512_p9),
    .sel(trunc_ln272_fu_680_p1),
    .dout(tmp_14_fu_1512_p11)
);

flash_attention_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln272_fu_674_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            b_fu_238 <= add_ln272_fu_664_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            b_fu_238 <= 27'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_58_reg_1608 <= empty_58_fu_784_p3;
        empty_59_reg_1613 <= empty_59_fu_838_p3;
        empty_60_reg_1618 <= empty_60_fu_892_p3;
        empty_61_reg_1623 <= empty_61_fu_946_p3;
        empty_62_reg_1628 <= empty_62_fu_1000_p3;
        empty_63_reg_1633 <= empty_63_fu_1054_p3;
        empty_64_reg_1638 <= empty_64_fu_1108_p3;
        empty_65_reg_1643 <= empty_65_fu_1162_p3;
        empty_66_reg_1648 <= empty_66_fu_1216_p3;
        empty_67_reg_1653 <= empty_67_fu_1270_p3;
        empty_68_reg_1658 <= empty_68_fu_1324_p3;
        empty_69_reg_1663 <= empty_69_fu_1378_p3;
        empty_70_reg_1668 <= empty_70_fu_1432_p3;
        empty_71_reg_1673 <= empty_71_fu_1486_p3;
        empty_72_reg_1678 <= empty_72_fu_1540_p3;
        empty_reg_1603 <= empty_fu_730_p3;
    end
end

always @ (*) begin
    if (((icmp_ln272_fu_674_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_b_1 = 27'd0;
    end else begin
        ap_sig_allocacmp_b_1 = b_fu_238;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem_l_blk_n_W = m_axi_gmem_l_0_WREADY;
    end else begin
        gmem_l_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem_l_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem_l_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln272_fu_664_p2 = (ap_sig_allocacmp_b_1 + 27'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem_l_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem_l_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem_l_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln279_10_fu_1266_p1 = tmp_6_fu_1242_p11;

assign bitcast_ln279_11_fu_1320_p1 = tmp_10_fu_1296_p11;

assign bitcast_ln279_12_fu_1374_p1 = tmp_11_fu_1350_p11;

assign bitcast_ln279_13_fu_1428_p1 = tmp_12_fu_1404_p11;

assign bitcast_ln279_14_fu_1482_p1 = tmp_13_fu_1458_p11;

assign bitcast_ln279_15_fu_1536_p1 = tmp_14_fu_1512_p11;

assign bitcast_ln279_1_fu_780_p1 = tmp_7_fu_756_p11;

assign bitcast_ln279_2_fu_834_p1 = tmp_8_fu_810_p11;

assign bitcast_ln279_3_fu_888_p1 = tmp_9_fu_864_p11;

assign bitcast_ln279_4_fu_942_p1 = tmp_s_fu_918_p11;

assign bitcast_ln279_5_fu_996_p1 = tmp_1_fu_972_p11;

assign bitcast_ln279_6_fu_1050_p1 = tmp_2_fu_1026_p11;

assign bitcast_ln279_7_fu_1104_p1 = tmp_3_fu_1080_p11;

assign bitcast_ln279_8_fu_1158_p1 = tmp_4_fu_1134_p11;

assign bitcast_ln279_9_fu_1212_p1 = tmp_5_fu_1188_p11;

assign bitcast_ln279_fu_726_p1 = tmp_fu_702_p11;

assign empty_58_fu_784_p3 = ((icmp_ln279_1_fu_750_p2[0:0] == 1'b1) ? bitcast_ln279_1_fu_780_p1 : 32'd0);

assign empty_59_fu_838_p3 = ((icmp_ln279_2_fu_804_p2[0:0] == 1'b1) ? bitcast_ln279_2_fu_834_p1 : 32'd0);

assign empty_60_fu_892_p3 = ((icmp_ln279_3_fu_858_p2[0:0] == 1'b1) ? bitcast_ln279_3_fu_888_p1 : 32'd0);

assign empty_61_fu_946_p3 = ((icmp_ln279_4_fu_912_p2[0:0] == 1'b1) ? bitcast_ln279_4_fu_942_p1 : 32'd0);

assign empty_62_fu_1000_p3 = ((icmp_ln279_5_fu_966_p2[0:0] == 1'b1) ? bitcast_ln279_5_fu_996_p1 : 32'd0);

assign empty_63_fu_1054_p3 = ((icmp_ln279_6_fu_1020_p2[0:0] == 1'b1) ? bitcast_ln279_6_fu_1050_p1 : 32'd0);

assign empty_64_fu_1108_p3 = ((icmp_ln279_7_fu_1074_p2[0:0] == 1'b1) ? bitcast_ln279_7_fu_1104_p1 : 32'd0);

assign empty_65_fu_1162_p3 = ((icmp_ln279_8_fu_1128_p2[0:0] == 1'b1) ? bitcast_ln279_8_fu_1158_p1 : 32'd0);

assign empty_66_fu_1216_p3 = ((icmp_ln279_9_fu_1182_p2[0:0] == 1'b1) ? bitcast_ln279_9_fu_1212_p1 : 32'd0);

assign empty_67_fu_1270_p3 = ((icmp_ln279_10_fu_1236_p2[0:0] == 1'b1) ? bitcast_ln279_10_fu_1266_p1 : 32'd0);

assign empty_68_fu_1324_p3 = ((icmp_ln279_11_fu_1290_p2[0:0] == 1'b1) ? bitcast_ln279_11_fu_1320_p1 : 32'd0);

assign empty_69_fu_1378_p3 = ((icmp_ln279_12_fu_1344_p2[0:0] == 1'b1) ? bitcast_ln279_12_fu_1374_p1 : 32'd0);

assign empty_70_fu_1432_p3 = ((icmp_ln279_13_fu_1398_p2[0:0] == 1'b1) ? bitcast_ln279_13_fu_1428_p1 : 32'd0);

assign empty_71_fu_1486_p3 = ((icmp_ln279_14_fu_1452_p2[0:0] == 1'b1) ? bitcast_ln279_14_fu_1482_p1 : 32'd0);

assign empty_72_fu_1540_p3 = ((icmp_ln279_15_fu_1506_p2[0:0] == 1'b1) ? bitcast_ln279_15_fu_1536_p1 : 32'd0);

assign empty_fu_730_p3 = ((icmp_ln279_fu_696_p2[0:0] == 1'b1) ? bitcast_ln279_fu_726_p1 : 32'd0);

assign icmp_ln272_fu_674_p2 = (($signed(zext_ln272_fu_670_p1) < $signed(total_beats)) ? 1'b1 : 1'b0);

assign icmp_ln279_10_fu_1236_p2 = (($signed(zext_ln279_10_fu_1232_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_11_fu_1290_p2 = (($signed(zext_ln279_11_fu_1286_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_12_fu_1344_p2 = (($signed(zext_ln279_12_fu_1340_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_13_fu_1398_p2 = (($signed(zext_ln279_13_fu_1394_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_14_fu_1452_p2 = (($signed(zext_ln279_14_fu_1448_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_15_fu_1506_p2 = (($signed(zext_ln279_15_fu_1502_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_1_fu_750_p2 = (($signed(zext_ln279_1_fu_746_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_2_fu_804_p2 = (($signed(zext_ln279_2_fu_800_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_3_fu_858_p2 = (($signed(zext_ln279_3_fu_854_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_4_fu_912_p2 = (($signed(zext_ln279_4_fu_908_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_5_fu_966_p2 = (($signed(zext_ln279_5_fu_962_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_6_fu_1020_p2 = (($signed(zext_ln279_6_fu_1016_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_7_fu_1074_p2 = (($signed(zext_ln279_7_fu_1070_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_8_fu_1128_p2 = (($signed(zext_ln279_8_fu_1124_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_9_fu_1182_p2 = (($signed(zext_ln279_9_fu_1178_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign icmp_ln279_fu_696_p2 = (($signed(zext_ln279_fu_692_p1) < $signed(num_elements)) ? 1'b1 : 1'b0);

assign m_axi_gmem_l_0_ARADDR = 64'd0;

assign m_axi_gmem_l_0_ARBURST = 2'd0;

assign m_axi_gmem_l_0_ARCACHE = 4'd0;

assign m_axi_gmem_l_0_ARID = 1'd0;

assign m_axi_gmem_l_0_ARLEN = 32'd0;

assign m_axi_gmem_l_0_ARLOCK = 2'd0;

assign m_axi_gmem_l_0_ARPROT = 3'd0;

assign m_axi_gmem_l_0_ARQOS = 4'd0;

assign m_axi_gmem_l_0_ARREGION = 4'd0;

assign m_axi_gmem_l_0_ARSIZE = 3'd0;

assign m_axi_gmem_l_0_ARUSER = 1'd0;

assign m_axi_gmem_l_0_ARVALID = 1'b0;

assign m_axi_gmem_l_0_AWADDR = 64'd0;

assign m_axi_gmem_l_0_AWBURST = 2'd0;

assign m_axi_gmem_l_0_AWCACHE = 4'd0;

assign m_axi_gmem_l_0_AWID = 1'd0;

assign m_axi_gmem_l_0_AWLEN = 32'd0;

assign m_axi_gmem_l_0_AWLOCK = 2'd0;

assign m_axi_gmem_l_0_AWPROT = 3'd0;

assign m_axi_gmem_l_0_AWQOS = 4'd0;

assign m_axi_gmem_l_0_AWREGION = 4'd0;

assign m_axi_gmem_l_0_AWSIZE = 3'd0;

assign m_axi_gmem_l_0_AWUSER = 1'd0;

assign m_axi_gmem_l_0_AWVALID = 1'b0;

assign m_axi_gmem_l_0_BREADY = 1'b0;

assign m_axi_gmem_l_0_RREADY = 1'b0;

assign m_axi_gmem_l_0_WDATA = {{{{{{{{{{{{{{{{empty_72_reg_1678}, {empty_71_reg_1673}}, {empty_70_reg_1668}}, {empty_69_reg_1663}}, {empty_68_reg_1658}}, {empty_67_reg_1653}}, {empty_66_reg_1648}}, {empty_65_reg_1643}}, {empty_64_reg_1638}}, {empty_63_reg_1633}}, {empty_62_reg_1628}}, {empty_61_reg_1623}}, {empty_60_reg_1618}}, {empty_59_reg_1613}}, {empty_58_reg_1608}}, {empty_reg_1603}};

assign m_axi_gmem_l_0_WID = 1'd0;

assign m_axi_gmem_l_0_WLAST = 1'b0;

assign m_axi_gmem_l_0_WSTRB = 64'd18446744073709551615;

assign m_axi_gmem_l_0_WUSER = 1'd0;

assign or_ln278_10_fu_1332_p3 = {{ap_sig_allocacmp_b_1}, {4'd12}};

assign or_ln278_11_fu_1386_p3 = {{ap_sig_allocacmp_b_1}, {4'd13}};

assign or_ln278_12_fu_1440_p3 = {{ap_sig_allocacmp_b_1}, {4'd14}};

assign or_ln278_13_fu_1494_p3 = {{ap_sig_allocacmp_b_1}, {4'd15}};

assign or_ln278_1_fu_792_p3 = {{ap_sig_allocacmp_b_1}, {4'd2}};

assign or_ln278_2_fu_846_p3 = {{ap_sig_allocacmp_b_1}, {4'd3}};

assign or_ln278_3_fu_900_p3 = {{ap_sig_allocacmp_b_1}, {4'd4}};

assign or_ln278_4_fu_954_p3 = {{ap_sig_allocacmp_b_1}, {4'd5}};

assign or_ln278_5_fu_1008_p3 = {{ap_sig_allocacmp_b_1}, {4'd6}};

assign or_ln278_6_fu_1062_p3 = {{ap_sig_allocacmp_b_1}, {4'd7}};

assign or_ln278_7_fu_1116_p3 = {{ap_sig_allocacmp_b_1}, {4'd8}};

assign or_ln278_8_fu_1170_p3 = {{ap_sig_allocacmp_b_1}, {4'd9}};

assign or_ln278_9_fu_1224_p3 = {{ap_sig_allocacmp_b_1}, {4'd10}};

assign or_ln278_s_fu_1278_p3 = {{ap_sig_allocacmp_b_1}, {4'd11}};

assign or_ln_fu_738_p3 = {{ap_sig_allocacmp_b_1}, {4'd1}};

assign tmp_10_fu_1296_p9 = 'bx;

assign tmp_11_fu_1350_p9 = 'bx;

assign tmp_12_fu_1404_p9 = 'bx;

assign tmp_13_fu_1458_p9 = 'bx;

assign tmp_14_fu_1512_p9 = 'bx;

assign tmp_15_fu_684_p3 = {{ap_sig_allocacmp_b_1}, {4'd0}};

assign tmp_1_fu_972_p9 = 'bx;

assign tmp_2_fu_1026_p9 = 'bx;

assign tmp_3_fu_1080_p9 = 'bx;

assign tmp_4_fu_1134_p9 = 'bx;

assign tmp_5_fu_1188_p9 = 'bx;

assign tmp_6_fu_1242_p9 = 'bx;

assign tmp_7_fu_756_p9 = 'bx;

assign tmp_8_fu_810_p9 = 'bx;

assign tmp_9_fu_864_p9 = 'bx;

assign tmp_fu_702_p9 = 'bx;

assign tmp_s_fu_918_p9 = 'bx;

assign trunc_ln272_fu_680_p1 = ap_sig_allocacmp_b_1[1:0];

assign zext_ln272_fu_670_p1 = ap_sig_allocacmp_b_1;

assign zext_ln279_10_fu_1232_p1 = or_ln278_9_fu_1224_p3;

assign zext_ln279_11_fu_1286_p1 = or_ln278_s_fu_1278_p3;

assign zext_ln279_12_fu_1340_p1 = or_ln278_10_fu_1332_p3;

assign zext_ln279_13_fu_1394_p1 = or_ln278_11_fu_1386_p3;

assign zext_ln279_14_fu_1448_p1 = or_ln278_12_fu_1440_p3;

assign zext_ln279_15_fu_1502_p1 = or_ln278_13_fu_1494_p3;

assign zext_ln279_1_fu_746_p1 = or_ln_fu_738_p3;

assign zext_ln279_2_fu_800_p1 = or_ln278_1_fu_792_p3;

assign zext_ln279_3_fu_854_p1 = or_ln278_2_fu_846_p3;

assign zext_ln279_4_fu_908_p1 = or_ln278_3_fu_900_p3;

assign zext_ln279_5_fu_962_p1 = or_ln278_4_fu_954_p3;

assign zext_ln279_6_fu_1016_p1 = or_ln278_5_fu_1008_p3;

assign zext_ln279_7_fu_1070_p1 = or_ln278_6_fu_1062_p3;

assign zext_ln279_8_fu_1124_p1 = or_ln278_7_fu_1116_p3;

assign zext_ln279_9_fu_1178_p1 = or_ln278_8_fu_1170_p3;

assign zext_ln279_fu_692_p1 = tmp_15_fu_684_p3;

endmodule //flash_attention_kernel_store_stats_fp32_Pipeline_STORE_STATS
