// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_kernel_flash_attention_kernel_Pipeline_CONVERT_O_TO_FP32_VITIS_LOOP_186_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tmp_211,
        O_tile_fp16_address0,
        O_tile_fp16_ce0,
        O_tile_fp16_q0,
        O_tile_fp16_1_address0,
        O_tile_fp16_1_ce0,
        O_tile_fp16_1_q0,
        O_tile_fp16_2_address0,
        O_tile_fp16_2_ce0,
        O_tile_fp16_2_q0,
        O_tile_fp16_3_address0,
        O_tile_fp16_3_ce0,
        O_tile_fp16_3_q0,
        O_tile_fp16_4_address0,
        O_tile_fp16_4_ce0,
        O_tile_fp16_4_q0,
        O_tile_fp16_5_address0,
        O_tile_fp16_5_ce0,
        O_tile_fp16_5_q0,
        O_tile_fp16_6_address0,
        O_tile_fp16_6_ce0,
        O_tile_fp16_6_q0,
        O_tile_fp16_7_address0,
        O_tile_fp16_7_ce0,
        O_tile_fp16_7_q0,
        O_tile_fp16_8_address0,
        O_tile_fp16_8_ce0,
        O_tile_fp16_8_q0,
        O_tile_fp16_9_address0,
        O_tile_fp16_9_ce0,
        O_tile_fp16_9_q0,
        O_tile_fp16_10_address0,
        O_tile_fp16_10_ce0,
        O_tile_fp16_10_q0,
        O_tile_fp16_11_address0,
        O_tile_fp16_11_ce0,
        O_tile_fp16_11_q0,
        O_tile_fp16_12_address0,
        O_tile_fp16_12_ce0,
        O_tile_fp16_12_q0,
        O_tile_fp16_13_address0,
        O_tile_fp16_13_ce0,
        O_tile_fp16_13_q0,
        O_tile_fp16_14_address0,
        O_tile_fp16_14_ce0,
        O_tile_fp16_14_q0,
        O_tile_fp16_15_address0,
        O_tile_fp16_15_ce0,
        O_tile_fp16_15_q0,
        O_acc_address1,
        O_acc_ce1,
        O_acc_we1,
        O_acc_d1,
        O_acc_1_address1,
        O_acc_1_ce1,
        O_acc_1_we1,
        O_acc_1_d1,
        O_acc_2_address1,
        O_acc_2_ce1,
        O_acc_2_we1,
        O_acc_2_d1,
        O_acc_3_address1,
        O_acc_3_ce1,
        O_acc_3_we1,
        O_acc_3_d1,
        O_acc_4_address1,
        O_acc_4_ce1,
        O_acc_4_we1,
        O_acc_4_d1,
        O_acc_5_address1,
        O_acc_5_ce1,
        O_acc_5_we1,
        O_acc_5_d1,
        O_acc_6_address1,
        O_acc_6_ce1,
        O_acc_6_we1,
        O_acc_6_d1,
        O_acc_7_address1,
        O_acc_7_ce1,
        O_acc_7_we1,
        O_acc_7_d1,
        O_acc_8_address1,
        O_acc_8_ce1,
        O_acc_8_we1,
        O_acc_8_d1,
        O_acc_9_address1,
        O_acc_9_ce1,
        O_acc_9_we1,
        O_acc_9_d1,
        O_acc_10_address1,
        O_acc_10_ce1,
        O_acc_10_we1,
        O_acc_10_d1,
        O_acc_11_address1,
        O_acc_11_ce1,
        O_acc_11_we1,
        O_acc_11_d1,
        O_acc_12_address1,
        O_acc_12_ce1,
        O_acc_12_we1,
        O_acc_12_d1,
        O_acc_13_address1,
        O_acc_13_ce1,
        O_acc_13_we1,
        O_acc_13_d1,
        O_acc_14_address1,
        O_acc_14_ce1,
        O_acc_14_we1,
        O_acc_14_d1,
        O_acc_15_address1,
        O_acc_15_ce1,
        O_acc_15_we1,
        O_acc_15_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [33:0] tmp_211;
output  [8:0] O_tile_fp16_address0;
output   O_tile_fp16_ce0;
input  [15:0] O_tile_fp16_q0;
output  [8:0] O_tile_fp16_1_address0;
output   O_tile_fp16_1_ce0;
input  [15:0] O_tile_fp16_1_q0;
output  [8:0] O_tile_fp16_2_address0;
output   O_tile_fp16_2_ce0;
input  [15:0] O_tile_fp16_2_q0;
output  [8:0] O_tile_fp16_3_address0;
output   O_tile_fp16_3_ce0;
input  [15:0] O_tile_fp16_3_q0;
output  [8:0] O_tile_fp16_4_address0;
output   O_tile_fp16_4_ce0;
input  [15:0] O_tile_fp16_4_q0;
output  [8:0] O_tile_fp16_5_address0;
output   O_tile_fp16_5_ce0;
input  [15:0] O_tile_fp16_5_q0;
output  [8:0] O_tile_fp16_6_address0;
output   O_tile_fp16_6_ce0;
input  [15:0] O_tile_fp16_6_q0;
output  [8:0] O_tile_fp16_7_address0;
output   O_tile_fp16_7_ce0;
input  [15:0] O_tile_fp16_7_q0;
output  [8:0] O_tile_fp16_8_address0;
output   O_tile_fp16_8_ce0;
input  [15:0] O_tile_fp16_8_q0;
output  [8:0] O_tile_fp16_9_address0;
output   O_tile_fp16_9_ce0;
input  [15:0] O_tile_fp16_9_q0;
output  [8:0] O_tile_fp16_10_address0;
output   O_tile_fp16_10_ce0;
input  [15:0] O_tile_fp16_10_q0;
output  [8:0] O_tile_fp16_11_address0;
output   O_tile_fp16_11_ce0;
input  [15:0] O_tile_fp16_11_q0;
output  [8:0] O_tile_fp16_12_address0;
output   O_tile_fp16_12_ce0;
input  [15:0] O_tile_fp16_12_q0;
output  [8:0] O_tile_fp16_13_address0;
output   O_tile_fp16_13_ce0;
input  [15:0] O_tile_fp16_13_q0;
output  [8:0] O_tile_fp16_14_address0;
output   O_tile_fp16_14_ce0;
input  [15:0] O_tile_fp16_14_q0;
output  [8:0] O_tile_fp16_15_address0;
output   O_tile_fp16_15_ce0;
input  [15:0] O_tile_fp16_15_q0;
output  [8:0] O_acc_address1;
output   O_acc_ce1;
output   O_acc_we1;
output  [31:0] O_acc_d1;
output  [8:0] O_acc_1_address1;
output   O_acc_1_ce1;
output   O_acc_1_we1;
output  [31:0] O_acc_1_d1;
output  [8:0] O_acc_2_address1;
output   O_acc_2_ce1;
output   O_acc_2_we1;
output  [31:0] O_acc_2_d1;
output  [8:0] O_acc_3_address1;
output   O_acc_3_ce1;
output   O_acc_3_we1;
output  [31:0] O_acc_3_d1;
output  [8:0] O_acc_4_address1;
output   O_acc_4_ce1;
output   O_acc_4_we1;
output  [31:0] O_acc_4_d1;
output  [8:0] O_acc_5_address1;
output   O_acc_5_ce1;
output   O_acc_5_we1;
output  [31:0] O_acc_5_d1;
output  [8:0] O_acc_6_address1;
output   O_acc_6_ce1;
output   O_acc_6_we1;
output  [31:0] O_acc_6_d1;
output  [8:0] O_acc_7_address1;
output   O_acc_7_ce1;
output   O_acc_7_we1;
output  [31:0] O_acc_7_d1;
output  [8:0] O_acc_8_address1;
output   O_acc_8_ce1;
output   O_acc_8_we1;
output  [31:0] O_acc_8_d1;
output  [8:0] O_acc_9_address1;
output   O_acc_9_ce1;
output   O_acc_9_we1;
output  [31:0] O_acc_9_d1;
output  [8:0] O_acc_10_address1;
output   O_acc_10_ce1;
output   O_acc_10_we1;
output  [31:0] O_acc_10_d1;
output  [8:0] O_acc_11_address1;
output   O_acc_11_ce1;
output   O_acc_11_we1;
output  [31:0] O_acc_11_d1;
output  [8:0] O_acc_12_address1;
output   O_acc_12_ce1;
output   O_acc_12_we1;
output  [31:0] O_acc_12_d1;
output  [8:0] O_acc_13_address1;
output   O_acc_13_ce1;
output   O_acc_13_we1;
output  [31:0] O_acc_13_d1;
output  [8:0] O_acc_14_address1;
output   O_acc_14_ce1;
output   O_acc_14_we1;
output  [31:0] O_acc_14_d1;
output  [8:0] O_acc_15_address1;
output   O_acc_15_ce1;
output   O_acc_15_we1;
output  [31:0] O_acc_15_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln185_fu_718_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln189_fu_789_p1;
reg   [63:0] zext_ln189_reg_1115;
wire    ap_block_pp0_stage0;
reg   [7:0] c_fu_116;
wire   [7:0] add_ln186_fu_873_p2;
wire    ap_loop_init;
reg   [30:0] r_fu_120;
wire   [30:0] select_ln185_1_fu_759_p3;
reg   [33:0] indvar_flatten_fu_124;
wire   [33:0] add_ln185_1_fu_712_p2;
reg    O_tile_fp16_ce0_local;
reg    O_tile_fp16_1_ce0_local;
reg    O_tile_fp16_2_ce0_local;
reg    O_tile_fp16_3_ce0_local;
reg    O_tile_fp16_4_ce0_local;
reg    O_tile_fp16_5_ce0_local;
reg    O_tile_fp16_6_ce0_local;
reg    O_tile_fp16_7_ce0_local;
reg    O_tile_fp16_8_ce0_local;
reg    O_tile_fp16_9_ce0_local;
reg    O_tile_fp16_10_ce0_local;
reg    O_tile_fp16_11_ce0_local;
reg    O_tile_fp16_12_ce0_local;
reg    O_tile_fp16_13_ce0_local;
reg    O_tile_fp16_14_ce0_local;
reg    O_tile_fp16_15_ce0_local;
reg    O_acc_we1_local;
wire   [31:0] conv_fu_614_p1;
reg    O_acc_ce1_local;
reg    O_acc_1_we1_local;
wire   [31:0] conv_1_fu_619_p1;
reg    O_acc_1_ce1_local;
reg    O_acc_2_we1_local;
wire   [31:0] conv_2_fu_624_p1;
reg    O_acc_2_ce1_local;
reg    O_acc_3_we1_local;
wire   [31:0] conv_3_fu_629_p1;
reg    O_acc_3_ce1_local;
reg    O_acc_4_we1_local;
wire   [31:0] conv_4_fu_634_p1;
reg    O_acc_4_ce1_local;
reg    O_acc_5_we1_local;
wire   [31:0] conv_5_fu_639_p1;
reg    O_acc_5_ce1_local;
reg    O_acc_6_we1_local;
wire   [31:0] conv_6_fu_644_p1;
reg    O_acc_6_ce1_local;
reg    O_acc_7_we1_local;
wire   [31:0] conv_7_fu_649_p1;
reg    O_acc_7_ce1_local;
reg    O_acc_8_we1_local;
wire   [31:0] conv_8_fu_654_p1;
reg    O_acc_8_ce1_local;
reg    O_acc_9_we1_local;
wire   [31:0] conv_9_fu_659_p1;
reg    O_acc_9_ce1_local;
reg    O_acc_10_we1_local;
wire   [31:0] conv_10_fu_664_p1;
reg    O_acc_10_ce1_local;
reg    O_acc_11_we1_local;
wire   [31:0] conv_11_fu_669_p1;
reg    O_acc_11_ce1_local;
reg    O_acc_12_we1_local;
wire   [31:0] conv_12_fu_674_p1;
reg    O_acc_12_ce1_local;
reg    O_acc_13_we1_local;
wire   [31:0] conv_13_fu_679_p1;
reg    O_acc_13_ce1_local;
reg    O_acc_14_we1_local;
wire   [31:0] conv_14_fu_684_p1;
reg    O_acc_14_ce1_local;
reg    O_acc_15_we1_local;
wire   [31:0] conv_s_fu_689_p1;
reg    O_acc_15_ce1_local;
wire   [0:0] tmp_fu_739_p3;
wire   [6:0] trunc_ln185_fu_729_p1;
wire   [6:0] select_ln185_fu_747_p3;
wire   [30:0] add_ln185_fu_733_p2;
wire   [5:0] trunc_ln187_fu_767_p1;
wire   [2:0] lshr_ln4_fu_771_p4;
wire   [8:0] tmp_s_fu_781_p3;
wire   [7:0] zext_ln185_fu_755_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 c_fu_116 = 8'd0;
#0 r_fu_120 = 31'd0;
#0 indvar_flatten_fu_124 = 34'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U316(
    .din0(O_tile_fp16_q0),
    .dout(conv_fu_614_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U317(
    .din0(O_tile_fp16_1_q0),
    .dout(conv_1_fu_619_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U318(
    .din0(O_tile_fp16_2_q0),
    .dout(conv_2_fu_624_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U319(
    .din0(O_tile_fp16_3_q0),
    .dout(conv_3_fu_629_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U320(
    .din0(O_tile_fp16_4_q0),
    .dout(conv_4_fu_634_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U321(
    .din0(O_tile_fp16_5_q0),
    .dout(conv_5_fu_639_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U322(
    .din0(O_tile_fp16_6_q0),
    .dout(conv_6_fu_644_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U323(
    .din0(O_tile_fp16_7_q0),
    .dout(conv_7_fu_649_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U324(
    .din0(O_tile_fp16_8_q0),
    .dout(conv_8_fu_654_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U325(
    .din0(O_tile_fp16_9_q0),
    .dout(conv_9_fu_659_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U326(
    .din0(O_tile_fp16_10_q0),
    .dout(conv_10_fu_664_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U327(
    .din0(O_tile_fp16_11_q0),
    .dout(conv_11_fu_669_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U328(
    .din0(O_tile_fp16_12_q0),
    .dout(conv_12_fu_674_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U329(
    .din0(O_tile_fp16_13_q0),
    .dout(conv_13_fu_679_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U330(
    .din0(O_tile_fp16_14_q0),
    .dout(conv_14_fu_684_p1)
);

flash_attention_kernel_hptosp_16ns_32_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_1_no_dsp_1_U331(
    .din0(O_tile_fp16_15_q0),
    .dout(conv_s_fu_689_p1)
);

flash_attention_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_116 <= 8'd0;
        end else if (((icmp_ln185_fu_718_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_116 <= add_ln186_fu_873_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_124 <= 34'd0;
        end else if (((icmp_ln185_fu_718_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_124 <= add_ln185_1_fu_712_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_fu_120 <= 31'd0;
        end else if (((icmp_ln185_fu_718_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            r_fu_120 <= select_ln185_1_fu_759_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln189_reg_1115[8 : 0] <= zext_ln189_fu_789_p1[8 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_10_ce1_local = 1'b1;
    end else begin
        O_acc_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_10_we1_local = 1'b1;
    end else begin
        O_acc_10_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_11_ce1_local = 1'b1;
    end else begin
        O_acc_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_11_we1_local = 1'b1;
    end else begin
        O_acc_11_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_12_ce1_local = 1'b1;
    end else begin
        O_acc_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_12_we1_local = 1'b1;
    end else begin
        O_acc_12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_13_ce1_local = 1'b1;
    end else begin
        O_acc_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_13_we1_local = 1'b1;
    end else begin
        O_acc_13_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_14_ce1_local = 1'b1;
    end else begin
        O_acc_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_14_we1_local = 1'b1;
    end else begin
        O_acc_14_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_15_ce1_local = 1'b1;
    end else begin
        O_acc_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_15_we1_local = 1'b1;
    end else begin
        O_acc_15_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_1_ce1_local = 1'b1;
    end else begin
        O_acc_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_1_we1_local = 1'b1;
    end else begin
        O_acc_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_2_ce1_local = 1'b1;
    end else begin
        O_acc_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_2_we1_local = 1'b1;
    end else begin
        O_acc_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_3_ce1_local = 1'b1;
    end else begin
        O_acc_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_3_we1_local = 1'b1;
    end else begin
        O_acc_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_4_ce1_local = 1'b1;
    end else begin
        O_acc_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_4_we1_local = 1'b1;
    end else begin
        O_acc_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_5_ce1_local = 1'b1;
    end else begin
        O_acc_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_5_we1_local = 1'b1;
    end else begin
        O_acc_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_6_ce1_local = 1'b1;
    end else begin
        O_acc_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_6_we1_local = 1'b1;
    end else begin
        O_acc_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_7_ce1_local = 1'b1;
    end else begin
        O_acc_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_7_we1_local = 1'b1;
    end else begin
        O_acc_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_8_ce1_local = 1'b1;
    end else begin
        O_acc_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_8_we1_local = 1'b1;
    end else begin
        O_acc_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_9_ce1_local = 1'b1;
    end else begin
        O_acc_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_9_we1_local = 1'b1;
    end else begin
        O_acc_9_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_ce1_local = 1'b1;
    end else begin
        O_acc_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        O_acc_we1_local = 1'b1;
    end else begin
        O_acc_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_10_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_11_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_12_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_13_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_14_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_15_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_1_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_2_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_3_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_4_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_5_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_6_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_7_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_8_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_9_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_tile_fp16_ce0_local = 1'b1;
    end else begin
        O_tile_fp16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_fu_718_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign O_acc_10_address1 = zext_ln189_reg_1115;

assign O_acc_10_ce1 = O_acc_10_ce1_local;

assign O_acc_10_d1 = conv_10_fu_664_p1;

assign O_acc_10_we1 = O_acc_10_we1_local;

assign O_acc_11_address1 = zext_ln189_reg_1115;

assign O_acc_11_ce1 = O_acc_11_ce1_local;

assign O_acc_11_d1 = conv_11_fu_669_p1;

assign O_acc_11_we1 = O_acc_11_we1_local;

assign O_acc_12_address1 = zext_ln189_reg_1115;

assign O_acc_12_ce1 = O_acc_12_ce1_local;

assign O_acc_12_d1 = conv_12_fu_674_p1;

assign O_acc_12_we1 = O_acc_12_we1_local;

assign O_acc_13_address1 = zext_ln189_reg_1115;

assign O_acc_13_ce1 = O_acc_13_ce1_local;

assign O_acc_13_d1 = conv_13_fu_679_p1;

assign O_acc_13_we1 = O_acc_13_we1_local;

assign O_acc_14_address1 = zext_ln189_reg_1115;

assign O_acc_14_ce1 = O_acc_14_ce1_local;

assign O_acc_14_d1 = conv_14_fu_684_p1;

assign O_acc_14_we1 = O_acc_14_we1_local;

assign O_acc_15_address1 = zext_ln189_reg_1115;

assign O_acc_15_ce1 = O_acc_15_ce1_local;

assign O_acc_15_d1 = conv_s_fu_689_p1;

assign O_acc_15_we1 = O_acc_15_we1_local;

assign O_acc_1_address1 = zext_ln189_reg_1115;

assign O_acc_1_ce1 = O_acc_1_ce1_local;

assign O_acc_1_d1 = conv_1_fu_619_p1;

assign O_acc_1_we1 = O_acc_1_we1_local;

assign O_acc_2_address1 = zext_ln189_reg_1115;

assign O_acc_2_ce1 = O_acc_2_ce1_local;

assign O_acc_2_d1 = conv_2_fu_624_p1;

assign O_acc_2_we1 = O_acc_2_we1_local;

assign O_acc_3_address1 = zext_ln189_reg_1115;

assign O_acc_3_ce1 = O_acc_3_ce1_local;

assign O_acc_3_d1 = conv_3_fu_629_p1;

assign O_acc_3_we1 = O_acc_3_we1_local;

assign O_acc_4_address1 = zext_ln189_reg_1115;

assign O_acc_4_ce1 = O_acc_4_ce1_local;

assign O_acc_4_d1 = conv_4_fu_634_p1;

assign O_acc_4_we1 = O_acc_4_we1_local;

assign O_acc_5_address1 = zext_ln189_reg_1115;

assign O_acc_5_ce1 = O_acc_5_ce1_local;

assign O_acc_5_d1 = conv_5_fu_639_p1;

assign O_acc_5_we1 = O_acc_5_we1_local;

assign O_acc_6_address1 = zext_ln189_reg_1115;

assign O_acc_6_ce1 = O_acc_6_ce1_local;

assign O_acc_6_d1 = conv_6_fu_644_p1;

assign O_acc_6_we1 = O_acc_6_we1_local;

assign O_acc_7_address1 = zext_ln189_reg_1115;

assign O_acc_7_ce1 = O_acc_7_ce1_local;

assign O_acc_7_d1 = conv_7_fu_649_p1;

assign O_acc_7_we1 = O_acc_7_we1_local;

assign O_acc_8_address1 = zext_ln189_reg_1115;

assign O_acc_8_ce1 = O_acc_8_ce1_local;

assign O_acc_8_d1 = conv_8_fu_654_p1;

assign O_acc_8_we1 = O_acc_8_we1_local;

assign O_acc_9_address1 = zext_ln189_reg_1115;

assign O_acc_9_ce1 = O_acc_9_ce1_local;

assign O_acc_9_d1 = conv_9_fu_659_p1;

assign O_acc_9_we1 = O_acc_9_we1_local;

assign O_acc_address1 = zext_ln189_reg_1115;

assign O_acc_ce1 = O_acc_ce1_local;

assign O_acc_d1 = conv_fu_614_p1;

assign O_acc_we1 = O_acc_we1_local;

assign O_tile_fp16_10_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_10_ce0 = O_tile_fp16_10_ce0_local;

assign O_tile_fp16_11_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_11_ce0 = O_tile_fp16_11_ce0_local;

assign O_tile_fp16_12_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_12_ce0 = O_tile_fp16_12_ce0_local;

assign O_tile_fp16_13_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_13_ce0 = O_tile_fp16_13_ce0_local;

assign O_tile_fp16_14_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_14_ce0 = O_tile_fp16_14_ce0_local;

assign O_tile_fp16_15_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_15_ce0 = O_tile_fp16_15_ce0_local;

assign O_tile_fp16_1_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_1_ce0 = O_tile_fp16_1_ce0_local;

assign O_tile_fp16_2_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_2_ce0 = O_tile_fp16_2_ce0_local;

assign O_tile_fp16_3_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_3_ce0 = O_tile_fp16_3_ce0_local;

assign O_tile_fp16_4_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_4_ce0 = O_tile_fp16_4_ce0_local;

assign O_tile_fp16_5_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_5_ce0 = O_tile_fp16_5_ce0_local;

assign O_tile_fp16_6_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_6_ce0 = O_tile_fp16_6_ce0_local;

assign O_tile_fp16_7_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_7_ce0 = O_tile_fp16_7_ce0_local;

assign O_tile_fp16_8_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_8_ce0 = O_tile_fp16_8_ce0_local;

assign O_tile_fp16_9_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_9_ce0 = O_tile_fp16_9_ce0_local;

assign O_tile_fp16_address0 = zext_ln189_fu_789_p1;

assign O_tile_fp16_ce0 = O_tile_fp16_ce0_local;

assign add_ln185_1_fu_712_p2 = (indvar_flatten_fu_124 + 34'd1);

assign add_ln185_fu_733_p2 = (r_fu_120 + 31'd1);

assign add_ln186_fu_873_p2 = (zext_ln185_fu_755_p1 + 8'd16);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln185_fu_718_p2 = ((indvar_flatten_fu_124 == tmp_211) ? 1'b1 : 1'b0);

assign lshr_ln4_fu_771_p4 = {{select_ln185_fu_747_p3[6:4]}};

assign select_ln185_1_fu_759_p3 = ((tmp_fu_739_p3[0:0] == 1'b1) ? add_ln185_fu_733_p2 : r_fu_120);

assign select_ln185_fu_747_p3 = ((tmp_fu_739_p3[0:0] == 1'b1) ? 7'd0 : trunc_ln185_fu_729_p1);

assign tmp_fu_739_p3 = c_fu_116[32'd7];

assign tmp_s_fu_781_p3 = {{trunc_ln187_fu_767_p1}, {lshr_ln4_fu_771_p4}};

assign trunc_ln185_fu_729_p1 = c_fu_116[6:0];

assign trunc_ln187_fu_767_p1 = select_ln185_1_fu_759_p3[5:0];

assign zext_ln185_fu_755_p1 = select_ln185_fu_747_p3;

assign zext_ln189_fu_789_p1 = tmp_s_fu_781_p3;

always @ (posedge ap_clk) begin
    zext_ln189_reg_1115[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //flash_attention_kernel_flash_attention_kernel_Pipeline_CONVERT_O_TO_FP32_VITIS_LOOP_186_1
