// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_kernel_online_softmax_tile_Pipeline_ROWMAX_INNER (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i,
        S_tile_0_address0,
        S_tile_0_ce0,
        S_tile_0_q0,
        S_tile_1_address0,
        S_tile_1_ce0,
        S_tile_1_q0,
        S_tile_2_address0,
        S_tile_2_ce0,
        S_tile_2_q0,
        S_tile_3_address0,
        S_tile_3_ce0,
        S_tile_3_q0,
        S_tile_4_address0,
        S_tile_4_ce0,
        S_tile_4_q0,
        S_tile_5_address0,
        S_tile_5_ce0,
        S_tile_5_q0,
        S_tile_6_address0,
        S_tile_6_ce0,
        S_tile_6_q0,
        S_tile_7_address0,
        S_tile_7_ce0,
        S_tile_7_q0,
        bc_actual,
        cmp6_not,
        row_max_out,
        row_max_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] i;
output  [8:0] S_tile_0_address0;
output   S_tile_0_ce0;
input  [31:0] S_tile_0_q0;
output  [8:0] S_tile_1_address0;
output   S_tile_1_ce0;
input  [31:0] S_tile_1_q0;
output  [8:0] S_tile_2_address0;
output   S_tile_2_ce0;
input  [31:0] S_tile_2_q0;
output  [8:0] S_tile_3_address0;
output   S_tile_3_ce0;
input  [31:0] S_tile_3_q0;
output  [8:0] S_tile_4_address0;
output   S_tile_4_ce0;
input  [31:0] S_tile_4_q0;
output  [8:0] S_tile_5_address0;
output   S_tile_5_ce0;
input  [31:0] S_tile_5_q0;
output  [8:0] S_tile_6_address0;
output   S_tile_6_ce0;
input  [31:0] S_tile_6_q0;
output  [8:0] S_tile_7_address0;
output   S_tile_7_ce0;
input  [31:0] S_tile_7_q0;
input  [31:0] bc_actual;
input  [0:0] cmp6_not;
output  [31:0] row_max_out;
output   row_max_out_ap_vld;

reg ap_idle;
reg row_max_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln50_fu_266_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] trunc_ln50_fu_276_p1;
reg   [2:0] trunc_ln50_reg_547;
wire   [0:0] icmp_ln52_fu_310_p2;
reg   [0:0] icmp_ln52_reg_592;
wire   [63:0] zext_ln52_fu_298_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] row_max_fu_106;
wire   [31:0] row_max_2_fu_507_p3;
wire    ap_loop_init;
reg   [6:0] j_fu_110;
wire   [6:0] add_ln50_fu_260_p2;
reg   [6:0] ap_sig_allocacmp_j_1;
wire    ap_block_pp0_stage0_01001;
reg    S_tile_0_ce0_local;
reg    S_tile_1_ce0_local;
reg    S_tile_2_ce0_local;
reg    S_tile_3_ce0_local;
reg    S_tile_4_ce0_local;
reg    S_tile_5_ce0_local;
reg    S_tile_6_ce0_local;
reg    S_tile_7_ce0_local;
wire   [31:0] val_fu_406_p3;
wire   [2:0] lshr_ln_fu_280_p4;
wire   [8:0] tmp_20_fu_290_p3;
wire   [31:0] zext_ln50_fu_272_p1;
wire   [0:0] xor_ln52_fu_357_p2;
wire   [31:0] tmp_fu_367_p17;
wire   [0:0] or_ln52_fu_362_p2;
wire   [31:0] tmp_fu_367_p19;
wire   [31:0] bitcast_ln53_fu_415_p1;
wire   [31:0] bitcast_ln53_1_fu_433_p1;
wire   [7:0] tmp_5_fu_419_p4;
wire   [22:0] trunc_ln53_fu_429_p1;
wire   [0:0] icmp_ln53_1_fu_457_p2;
wire   [0:0] icmp_ln53_fu_451_p2;
wire   [7:0] tmp_6_fu_437_p4;
wire   [22:0] trunc_ln53_1_fu_447_p1;
wire   [0:0] icmp_ln53_3_fu_475_p2;
wire   [0:0] icmp_ln53_2_fu_469_p2;
wire   [0:0] tmp_7_fu_243_p2;
wire   [0:0] or_ln53_fu_463_p2;
wire   [0:0] and_ln53_fu_495_p2;
wire   [0:0] or_ln53_1_fu_481_p2;
wire   [0:0] and_ln53_1_fu_501_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_fu_367_p1;
wire   [2:0] tmp_fu_367_p3;
wire   [2:0] tmp_fu_367_p5;
wire   [2:0] tmp_fu_367_p7;
wire  signed [2:0] tmp_fu_367_p9;
wire  signed [2:0] tmp_fu_367_p11;
wire  signed [2:0] tmp_fu_367_p13;
wire  signed [2:0] tmp_fu_367_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 row_max_fu_106 = 32'd0;
#0 j_fu_110 = 7'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_kernel_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U658(
    .din0(val_fu_406_p3),
    .din1(row_max_fu_106),
    .opcode(5'd2),
    .dout(tmp_7_fu_243_p2)
);

(* dissolve_hierarchy = "yes" *) flash_attention_kernel_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U659(
    .din0(S_tile_0_q0),
    .din1(S_tile_1_q0),
    .din2(S_tile_2_q0),
    .din3(S_tile_3_q0),
    .din4(S_tile_4_q0),
    .din5(S_tile_5_q0),
    .din6(S_tile_6_q0),
    .din7(S_tile_7_q0),
    .def(tmp_fu_367_p17),
    .sel(trunc_ln50_reg_547),
    .dout(tmp_fu_367_p19)
);

flash_attention_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln50_fu_266_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_110 <= add_ln50_fu_260_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_110 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            row_max_fu_106 <= 32'd4048155338;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            row_max_fu_106 <= row_max_2_fu_507_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln52_reg_592 <= icmp_ln52_fu_310_p2;
        trunc_ln50_reg_547 <= trunc_ln50_fu_276_p1;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_266_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_tile_0_ce0_local = 1'b1;
    end else begin
        S_tile_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_266_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_tile_1_ce0_local = 1'b1;
    end else begin
        S_tile_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_266_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_tile_2_ce0_local = 1'b1;
    end else begin
        S_tile_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_266_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_tile_3_ce0_local = 1'b1;
    end else begin
        S_tile_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_266_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_tile_4_ce0_local = 1'b1;
    end else begin
        S_tile_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_266_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_tile_5_ce0_local = 1'b1;
    end else begin
        S_tile_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_266_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_tile_6_ce0_local = 1'b1;
    end else begin
        S_tile_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_266_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_tile_7_ce0_local = 1'b1;
    end else begin
        S_tile_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_266_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_110;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln50_fu_266_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_max_out_ap_vld = 1'b1;
    end else begin
        row_max_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign S_tile_0_address0 = zext_ln52_fu_298_p1;

assign S_tile_0_ce0 = S_tile_0_ce0_local;

assign S_tile_1_address0 = zext_ln52_fu_298_p1;

assign S_tile_1_ce0 = S_tile_1_ce0_local;

assign S_tile_2_address0 = zext_ln52_fu_298_p1;

assign S_tile_2_ce0 = S_tile_2_ce0_local;

assign S_tile_3_address0 = zext_ln52_fu_298_p1;

assign S_tile_3_ce0 = S_tile_3_ce0_local;

assign S_tile_4_address0 = zext_ln52_fu_298_p1;

assign S_tile_4_ce0 = S_tile_4_ce0_local;

assign S_tile_5_address0 = zext_ln52_fu_298_p1;

assign S_tile_5_ce0 = S_tile_5_ce0_local;

assign S_tile_6_address0 = zext_ln52_fu_298_p1;

assign S_tile_6_ce0 = S_tile_6_ce0_local;

assign S_tile_7_address0 = zext_ln52_fu_298_p1;

assign S_tile_7_ce0 = S_tile_7_ce0_local;

assign add_ln50_fu_260_p2 = (ap_sig_allocacmp_j_1 + 7'd1);

assign and_ln53_1_fu_501_p2 = (or_ln53_1_fu_481_p2 & and_ln53_fu_495_p2);

assign and_ln53_fu_495_p2 = (tmp_7_fu_243_p2 & or_ln53_fu_463_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln53_1_fu_433_p1 = row_max_fu_106;

assign bitcast_ln53_fu_415_p1 = val_fu_406_p3;

assign icmp_ln50_fu_266_p2 = ((ap_sig_allocacmp_j_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_310_p2 = (($signed(zext_ln50_fu_272_p1) < $signed(bc_actual)) ? 1'b1 : 1'b0);

assign icmp_ln53_1_fu_457_p2 = ((trunc_ln53_fu_429_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_2_fu_469_p2 = ((tmp_6_fu_437_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln53_3_fu_475_p2 = ((trunc_ln53_1_fu_447_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_451_p2 = ((tmp_5_fu_419_p4 != 8'd255) ? 1'b1 : 1'b0);

assign lshr_ln_fu_280_p4 = {{ap_sig_allocacmp_j_1[5:3]}};

assign or_ln52_fu_362_p2 = (xor_ln52_fu_357_p2 | cmp6_not);

assign or_ln53_1_fu_481_p2 = (icmp_ln53_3_fu_475_p2 | icmp_ln53_2_fu_469_p2);

assign or_ln53_fu_463_p2 = (icmp_ln53_fu_451_p2 | icmp_ln53_1_fu_457_p2);

assign row_max_2_fu_507_p3 = ((and_ln53_1_fu_501_p2[0:0] == 1'b1) ? val_fu_406_p3 : row_max_fu_106);

assign row_max_out = row_max_fu_106;

assign tmp_20_fu_290_p3 = {{i}, {lshr_ln_fu_280_p4}};

assign tmp_5_fu_419_p4 = {{bitcast_ln53_fu_415_p1[30:23]}};

assign tmp_6_fu_437_p4 = {{bitcast_ln53_1_fu_433_p1[30:23]}};

assign tmp_fu_367_p17 = 'bx;

assign trunc_ln50_fu_276_p1 = ap_sig_allocacmp_j_1[2:0];

assign trunc_ln53_1_fu_447_p1 = bitcast_ln53_1_fu_433_p1[22:0];

assign trunc_ln53_fu_429_p1 = bitcast_ln53_fu_415_p1[22:0];

assign val_fu_406_p3 = ((or_ln52_fu_362_p2[0:0] == 1'b1) ? 32'd4048155338 : tmp_fu_367_p19);

assign xor_ln52_fu_357_p2 = (icmp_ln52_reg_592 ^ 1'd1);

assign zext_ln50_fu_272_p1 = ap_sig_allocacmp_j_1;

assign zext_ln52_fu_298_p1 = tmp_20_fu_290_p3;

endmodule //flash_attention_kernel_online_softmax_tile_Pipeline_ROWMAX_INNER
