-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flash_attention_kernel_gemm_qkt_Pipeline_STORE_S_ROW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    i : IN STD_LOGIC_VECTOR (5 downto 0);
    S_tile_0_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    S_tile_0_ce1 : OUT STD_LOGIC;
    S_tile_0_we1 : OUT STD_LOGIC;
    S_tile_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    S_tile_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    S_tile_1_ce1 : OUT STD_LOGIC;
    S_tile_1_we1 : OUT STD_LOGIC;
    S_tile_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    S_tile_2_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    S_tile_2_ce1 : OUT STD_LOGIC;
    S_tile_2_we1 : OUT STD_LOGIC;
    S_tile_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    S_tile_3_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    S_tile_3_ce1 : OUT STD_LOGIC;
    S_tile_3_we1 : OUT STD_LOGIC;
    S_tile_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    S_tile_4_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    S_tile_4_ce1 : OUT STD_LOGIC;
    S_tile_4_we1 : OUT STD_LOGIC;
    S_tile_4_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    S_tile_5_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    S_tile_5_ce1 : OUT STD_LOGIC;
    S_tile_5_we1 : OUT STD_LOGIC;
    S_tile_5_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    S_tile_6_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    S_tile_6_ce1 : OUT STD_LOGIC;
    S_tile_6_we1 : OUT STD_LOGIC;
    S_tile_6_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    S_tile_7_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    S_tile_7_ce1 : OUT STD_LOGIC;
    S_tile_7_we1 : OUT STD_LOGIC;
    S_tile_7_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bc_actual : IN STD_LOGIC_VECTOR (31 downto 0);
    cmp60 : IN STD_LOGIC_VECTOR (0 downto 0);
    acc_row_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_8_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_16_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_24_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_32_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_40_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_48_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_56_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_1_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_9_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_17_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_25_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_33_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_41_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_49_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_57_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_2_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_10_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_18_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_26_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_34_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_42_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_50_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_58_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_3_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_11_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_19_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_27_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_35_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_43_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_51_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_59_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_4_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_12_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_20_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_28_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_36_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_44_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_52_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_60_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_5_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_13_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_21_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_29_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_37_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_45_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_53_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_61_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_6_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_14_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_22_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_30_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_38_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_46_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_54_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_62_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_7_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_15_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_23_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_31_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_39_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_47_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_55_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_row_63_load_reload : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of flash_attention_kernel_gemm_qkt_Pipeline_STORE_S_ROW is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv7_8 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_fu_798_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln102_7_fu_838_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_248 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln99_fu_806_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_2 : STD_LOGIC_VECTOR (6 downto 0);
    signal S_tile_0_we1_local : STD_LOGIC;
    signal cond_fu_902_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_tile_0_ce1_local : STD_LOGIC;
    signal S_tile_1_we1_local : STD_LOGIC;
    signal cond_1_fu_993_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_tile_1_ce1_local : STD_LOGIC;
    signal S_tile_2_we1_local : STD_LOGIC;
    signal cond_2_fu_1084_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_tile_2_ce1_local : STD_LOGIC;
    signal S_tile_3_we1_local : STD_LOGIC;
    signal cond_3_fu_1165_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_tile_3_ce1_local : STD_LOGIC;
    signal S_tile_4_we1_local : STD_LOGIC;
    signal cond_4_fu_1246_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_tile_4_ce1_local : STD_LOGIC;
    signal S_tile_5_we1_local : STD_LOGIC;
    signal cond_5_fu_1339_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_tile_5_ce1_local : STD_LOGIC;
    signal S_tile_6_we1_local : STD_LOGIC;
    signal cond_6_fu_1420_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_tile_6_ce1_local : STD_LOGIC;
    signal S_tile_7_we1_local : STD_LOGIC;
    signal cond_7_fu_1501_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal S_tile_7_ce1_local : STD_LOGIC;
    signal lshr_ln_fu_820_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_178_fu_830_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln99_fu_812_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln102_fu_850_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_862_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln99_fu_816_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln102_fu_856_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_862_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_179_fu_919_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln_fu_929_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln102_fu_937_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln102_1_fu_941_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_171_fu_953_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln102_1_fu_947_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_171_fu_953_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_180_fu_1010_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln99_1_fu_1020_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln102_1_fu_1028_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln102_2_fu_1032_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_172_fu_1044_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln102_2_fu_1038_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_172_fu_1044_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln99_2_fu_1101_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln102_2_fu_1109_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln102_3_fu_1113_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_173_fu_1125_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln102_3_fu_1119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_173_fu_1125_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln99_3_fu_1182_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln102_3_fu_1190_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln102_4_fu_1194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_174_fu_1206_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln102_4_fu_1200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_174_fu_1206_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_1263_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln99_4_fu_1271_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln102_4_fu_1283_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln102_5_fu_1287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_175_fu_1299_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln102_5_fu_1293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_175_fu_1299_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln99_5_fu_1356_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln102_5_fu_1364_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln102_6_fu_1368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_176_fu_1380_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln102_6_fu_1374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_176_fu_1380_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln99_6_fu_1437_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln102_6_fu_1445_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln102_7_fu_1449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_177_fu_1461_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln102_7_fu_1455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_177_fu_1461_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_s_fu_862_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_862_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_862_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_862_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_862_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_862_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_862_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_862_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_171_fu_953_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_171_fu_953_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_171_fu_953_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_171_fu_953_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_171_fu_953_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_171_fu_953_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_171_fu_953_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_171_fu_953_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_172_fu_1044_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_172_fu_1044_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_172_fu_1044_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_172_fu_1044_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_172_fu_1044_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_172_fu_1044_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_172_fu_1044_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_172_fu_1044_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_173_fu_1125_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_173_fu_1125_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_173_fu_1125_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_173_fu_1125_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_173_fu_1125_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_173_fu_1125_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_173_fu_1125_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_173_fu_1125_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_174_fu_1206_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_174_fu_1206_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_174_fu_1206_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_174_fu_1206_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_174_fu_1206_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_174_fu_1206_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_174_fu_1206_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_174_fu_1206_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_175_fu_1299_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_175_fu_1299_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_175_fu_1299_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_175_fu_1299_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_175_fu_1299_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_175_fu_1299_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_175_fu_1299_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_175_fu_1299_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_176_fu_1380_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_176_fu_1380_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_176_fu_1380_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_176_fu_1380_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_176_fu_1380_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_176_fu_1380_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_176_fu_1380_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_176_fu_1380_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_177_fu_1461_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_177_fu_1461_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_177_fu_1461_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_177_fu_1461_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_177_fu_1461_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_177_fu_1461_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_177_fu_1461_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_177_fu_1461_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component flash_attention_kernel_sparsemux_17_6_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (5 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component flash_attention_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_17_6_32_1_1_U532 : component flash_attention_kernel_sparsemux_17_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "001000",
        din1_WIDTH => 32,
        CASE2 => "010000",
        din2_WIDTH => 32,
        CASE3 => "011000",
        din3_WIDTH => 32,
        CASE4 => "100000",
        din4_WIDTH => 32,
        CASE5 => "101000",
        din5_WIDTH => 32,
        CASE6 => "110000",
        din6_WIDTH => 32,
        CASE7 => "111000",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => acc_row_load_reload,
        din1 => acc_row_8_load_reload,
        din2 => acc_row_16_load_reload,
        din3 => acc_row_24_load_reload,
        din4 => acc_row_32_load_reload,
        din5 => acc_row_40_load_reload,
        din6 => acc_row_48_load_reload,
        din7 => acc_row_56_load_reload,
        def => tmp_s_fu_862_p17,
        sel => trunc_ln99_fu_816_p1,
        dout => tmp_s_fu_862_p19);

    sparsemux_17_6_32_1_1_U533 : component flash_attention_kernel_sparsemux_17_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "001000",
        din1_WIDTH => 32,
        CASE2 => "010000",
        din2_WIDTH => 32,
        CASE3 => "011000",
        din3_WIDTH => 32,
        CASE4 => "100000",
        din4_WIDTH => 32,
        CASE5 => "101000",
        din5_WIDTH => 32,
        CASE6 => "110000",
        din6_WIDTH => 32,
        CASE7 => "111000",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => acc_row_1_load_reload,
        din1 => acc_row_9_load_reload,
        din2 => acc_row_17_load_reload,
        din3 => acc_row_25_load_reload,
        din4 => acc_row_33_load_reload,
        din5 => acc_row_41_load_reload,
        din6 => acc_row_49_load_reload,
        din7 => acc_row_57_load_reload,
        def => tmp_171_fu_953_p17,
        sel => trunc_ln99_fu_816_p1,
        dout => tmp_171_fu_953_p19);

    sparsemux_17_6_32_1_1_U534 : component flash_attention_kernel_sparsemux_17_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "001000",
        din1_WIDTH => 32,
        CASE2 => "010000",
        din2_WIDTH => 32,
        CASE3 => "011000",
        din3_WIDTH => 32,
        CASE4 => "100000",
        din4_WIDTH => 32,
        CASE5 => "101000",
        din5_WIDTH => 32,
        CASE6 => "110000",
        din6_WIDTH => 32,
        CASE7 => "111000",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => acc_row_2_load_reload,
        din1 => acc_row_10_load_reload,
        din2 => acc_row_18_load_reload,
        din3 => acc_row_26_load_reload,
        din4 => acc_row_34_load_reload,
        din5 => acc_row_42_load_reload,
        din6 => acc_row_50_load_reload,
        din7 => acc_row_58_load_reload,
        def => tmp_172_fu_1044_p17,
        sel => trunc_ln99_fu_816_p1,
        dout => tmp_172_fu_1044_p19);

    sparsemux_17_6_32_1_1_U535 : component flash_attention_kernel_sparsemux_17_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "001000",
        din1_WIDTH => 32,
        CASE2 => "010000",
        din2_WIDTH => 32,
        CASE3 => "011000",
        din3_WIDTH => 32,
        CASE4 => "100000",
        din4_WIDTH => 32,
        CASE5 => "101000",
        din5_WIDTH => 32,
        CASE6 => "110000",
        din6_WIDTH => 32,
        CASE7 => "111000",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => acc_row_3_load_reload,
        din1 => acc_row_11_load_reload,
        din2 => acc_row_19_load_reload,
        din3 => acc_row_27_load_reload,
        din4 => acc_row_35_load_reload,
        din5 => acc_row_43_load_reload,
        din6 => acc_row_51_load_reload,
        din7 => acc_row_59_load_reload,
        def => tmp_173_fu_1125_p17,
        sel => trunc_ln99_fu_816_p1,
        dout => tmp_173_fu_1125_p19);

    sparsemux_17_6_32_1_1_U536 : component flash_attention_kernel_sparsemux_17_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "001000",
        din1_WIDTH => 32,
        CASE2 => "010000",
        din2_WIDTH => 32,
        CASE3 => "011000",
        din3_WIDTH => 32,
        CASE4 => "100000",
        din4_WIDTH => 32,
        CASE5 => "101000",
        din5_WIDTH => 32,
        CASE6 => "110000",
        din6_WIDTH => 32,
        CASE7 => "111000",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => acc_row_4_load_reload,
        din1 => acc_row_12_load_reload,
        din2 => acc_row_20_load_reload,
        din3 => acc_row_28_load_reload,
        din4 => acc_row_36_load_reload,
        din5 => acc_row_44_load_reload,
        din6 => acc_row_52_load_reload,
        din7 => acc_row_60_load_reload,
        def => tmp_174_fu_1206_p17,
        sel => trunc_ln99_fu_816_p1,
        dout => tmp_174_fu_1206_p19);

    sparsemux_17_6_32_1_1_U537 : component flash_attention_kernel_sparsemux_17_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "001000",
        din1_WIDTH => 32,
        CASE2 => "010000",
        din2_WIDTH => 32,
        CASE3 => "011000",
        din3_WIDTH => 32,
        CASE4 => "100000",
        din4_WIDTH => 32,
        CASE5 => "101000",
        din5_WIDTH => 32,
        CASE6 => "110000",
        din6_WIDTH => 32,
        CASE7 => "111000",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => acc_row_5_load_reload,
        din1 => acc_row_13_load_reload,
        din2 => acc_row_21_load_reload,
        din3 => acc_row_29_load_reload,
        din4 => acc_row_37_load_reload,
        din5 => acc_row_45_load_reload,
        din6 => acc_row_53_load_reload,
        din7 => acc_row_61_load_reload,
        def => tmp_175_fu_1299_p17,
        sel => trunc_ln99_fu_816_p1,
        dout => tmp_175_fu_1299_p19);

    sparsemux_17_6_32_1_1_U538 : component flash_attention_kernel_sparsemux_17_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "001000",
        din1_WIDTH => 32,
        CASE2 => "010000",
        din2_WIDTH => 32,
        CASE3 => "011000",
        din3_WIDTH => 32,
        CASE4 => "100000",
        din4_WIDTH => 32,
        CASE5 => "101000",
        din5_WIDTH => 32,
        CASE6 => "110000",
        din6_WIDTH => 32,
        CASE7 => "111000",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => acc_row_6_load_reload,
        din1 => acc_row_14_load_reload,
        din2 => acc_row_22_load_reload,
        din3 => acc_row_30_load_reload,
        din4 => acc_row_38_load_reload,
        din5 => acc_row_46_load_reload,
        din6 => acc_row_54_load_reload,
        din7 => acc_row_62_load_reload,
        def => tmp_176_fu_1380_p17,
        sel => trunc_ln99_fu_816_p1,
        dout => tmp_176_fu_1380_p19);

    sparsemux_17_6_32_1_1_U539 : component flash_attention_kernel_sparsemux_17_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "001000",
        din1_WIDTH => 32,
        CASE2 => "010000",
        din2_WIDTH => 32,
        CASE3 => "011000",
        din3_WIDTH => 32,
        CASE4 => "100000",
        din4_WIDTH => 32,
        CASE5 => "101000",
        din5_WIDTH => 32,
        CASE6 => "110000",
        din6_WIDTH => 32,
        CASE7 => "111000",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => acc_row_7_load_reload,
        din1 => acc_row_15_load_reload,
        din2 => acc_row_23_load_reload,
        din3 => acc_row_31_load_reload,
        din4 => acc_row_39_load_reload,
        din5 => acc_row_47_load_reload,
        din6 => acc_row_55_load_reload,
        din7 => acc_row_63_load_reload,
        def => tmp_177_fu_1461_p17,
        sel => trunc_ln99_fu_816_p1,
        dout => tmp_177_fu_1461_p19);

    flow_control_loop_pipe_sequential_init_U : component flash_attention_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((tmp_fu_798_p3 = ap_const_lv1_0)) then 
                    j_fu_248 <= add_ln99_fu_806_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_248 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    S_tile_0_address1 <= zext_ln102_7_fu_838_p1(9 - 1 downto 0);
    S_tile_0_ce1 <= S_tile_0_ce1_local;

    S_tile_0_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_0_ce1_local <= ap_const_logic_1;
        else 
            S_tile_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_0_d1 <= cond_fu_902_p3;
    S_tile_0_we1 <= S_tile_0_we1_local;

    S_tile_0_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_0_we1_local <= ap_const_logic_1;
        else 
            S_tile_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_1_address1 <= zext_ln102_7_fu_838_p1(9 - 1 downto 0);
    S_tile_1_ce1 <= S_tile_1_ce1_local;

    S_tile_1_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_1_ce1_local <= ap_const_logic_1;
        else 
            S_tile_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_1_d1 <= cond_1_fu_993_p3;
    S_tile_1_we1 <= S_tile_1_we1_local;

    S_tile_1_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_1_we1_local <= ap_const_logic_1;
        else 
            S_tile_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_2_address1 <= zext_ln102_7_fu_838_p1(9 - 1 downto 0);
    S_tile_2_ce1 <= S_tile_2_ce1_local;

    S_tile_2_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_2_ce1_local <= ap_const_logic_1;
        else 
            S_tile_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_2_d1 <= cond_2_fu_1084_p3;
    S_tile_2_we1 <= S_tile_2_we1_local;

    S_tile_2_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_2_we1_local <= ap_const_logic_1;
        else 
            S_tile_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_3_address1 <= zext_ln102_7_fu_838_p1(9 - 1 downto 0);
    S_tile_3_ce1 <= S_tile_3_ce1_local;

    S_tile_3_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_3_ce1_local <= ap_const_logic_1;
        else 
            S_tile_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_3_d1 <= cond_3_fu_1165_p3;
    S_tile_3_we1 <= S_tile_3_we1_local;

    S_tile_3_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_3_we1_local <= ap_const_logic_1;
        else 
            S_tile_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_4_address1 <= zext_ln102_7_fu_838_p1(9 - 1 downto 0);
    S_tile_4_ce1 <= S_tile_4_ce1_local;

    S_tile_4_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_4_ce1_local <= ap_const_logic_1;
        else 
            S_tile_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_4_d1 <= cond_4_fu_1246_p3;
    S_tile_4_we1 <= S_tile_4_we1_local;

    S_tile_4_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_4_we1_local <= ap_const_logic_1;
        else 
            S_tile_4_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_5_address1 <= zext_ln102_7_fu_838_p1(9 - 1 downto 0);
    S_tile_5_ce1 <= S_tile_5_ce1_local;

    S_tile_5_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_5_ce1_local <= ap_const_logic_1;
        else 
            S_tile_5_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_5_d1 <= cond_5_fu_1339_p3;
    S_tile_5_we1 <= S_tile_5_we1_local;

    S_tile_5_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_5_we1_local <= ap_const_logic_1;
        else 
            S_tile_5_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_6_address1 <= zext_ln102_7_fu_838_p1(9 - 1 downto 0);
    S_tile_6_ce1 <= S_tile_6_ce1_local;

    S_tile_6_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_6_ce1_local <= ap_const_logic_1;
        else 
            S_tile_6_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_6_d1 <= cond_6_fu_1420_p3;
    S_tile_6_we1 <= S_tile_6_we1_local;

    S_tile_6_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_6_we1_local <= ap_const_logic_1;
        else 
            S_tile_6_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_7_address1 <= zext_ln102_7_fu_838_p1(9 - 1 downto 0);
    S_tile_7_ce1 <= S_tile_7_ce1_local;

    S_tile_7_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_7_ce1_local <= ap_const_logic_1;
        else 
            S_tile_7_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    S_tile_7_d1 <= cond_7_fu_1501_p3;
    S_tile_7_we1 <= S_tile_7_we1_local;

    S_tile_7_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_tile_7_we1_local <= ap_const_logic_1;
        else 
            S_tile_7_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln99_fu_806_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_2) + unsigned(ap_const_lv7_8));
    and_ln102_1_fu_947_p2 <= (icmp_ln102_1_fu_941_p2 and cmp60);
    and_ln102_2_fu_1038_p2 <= (icmp_ln102_2_fu_1032_p2 and cmp60);
    and_ln102_3_fu_1119_p2 <= (icmp_ln102_3_fu_1113_p2 and cmp60);
    and_ln102_4_fu_1200_p2 <= (icmp_ln102_4_fu_1194_p2 and cmp60);
    and_ln102_5_fu_1293_p2 <= (icmp_ln102_5_fu_1287_p2 and cmp60);
    and_ln102_6_fu_1374_p2 <= (icmp_ln102_6_fu_1368_p2 and cmp60);
    and_ln102_7_fu_1455_p2 <= (icmp_ln102_7_fu_1449_p2 and cmp60);
    and_ln102_fu_856_p2 <= (icmp_ln102_fu_850_p2 and cmp60);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_798_p3)
    begin
        if (((tmp_fu_798_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_2_assign_proc : process(ap_CS_fsm_state1, j_fu_248, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_2 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_j_2 <= j_fu_248;
        end if; 
    end process;

    cond_1_fu_993_p3 <= 
        tmp_171_fu_953_p19 when (and_ln102_1_fu_947_p2(0) = '1') else 
        ap_const_lv32_0;
    cond_2_fu_1084_p3 <= 
        tmp_172_fu_1044_p19 when (and_ln102_2_fu_1038_p2(0) = '1') else 
        ap_const_lv32_0;
    cond_3_fu_1165_p3 <= 
        tmp_173_fu_1125_p19 when (and_ln102_3_fu_1119_p2(0) = '1') else 
        ap_const_lv32_0;
    cond_4_fu_1246_p3 <= 
        tmp_174_fu_1206_p19 when (and_ln102_4_fu_1200_p2(0) = '1') else 
        ap_const_lv32_0;
    cond_5_fu_1339_p3 <= 
        tmp_175_fu_1299_p19 when (and_ln102_5_fu_1293_p2(0) = '1') else 
        ap_const_lv32_0;
    cond_6_fu_1420_p3 <= 
        tmp_176_fu_1380_p19 when (and_ln102_6_fu_1374_p2(0) = '1') else 
        ap_const_lv32_0;
    cond_7_fu_1501_p3 <= 
        tmp_177_fu_1461_p19 when (and_ln102_7_fu_1455_p2(0) = '1') else 
        ap_const_lv32_0;
    cond_fu_902_p3 <= 
        tmp_s_fu_862_p19 when (and_ln102_fu_856_p2(0) = '1') else 
        ap_const_lv32_0;
    icmp_ln102_1_fu_941_p2 <= "1" when (signed(zext_ln102_fu_937_p1) < signed(bc_actual)) else "0";
    icmp_ln102_2_fu_1032_p2 <= "1" when (signed(zext_ln102_1_fu_1028_p1) < signed(bc_actual)) else "0";
    icmp_ln102_3_fu_1113_p2 <= "1" when (signed(zext_ln102_2_fu_1109_p1) < signed(bc_actual)) else "0";
    icmp_ln102_4_fu_1194_p2 <= "1" when (signed(zext_ln102_3_fu_1190_p1) < signed(bc_actual)) else "0";
    icmp_ln102_5_fu_1287_p2 <= "1" when (signed(zext_ln102_4_fu_1283_p1) < signed(bc_actual)) else "0";
    icmp_ln102_6_fu_1368_p2 <= "1" when (signed(zext_ln102_5_fu_1364_p1) < signed(bc_actual)) else "0";
    icmp_ln102_7_fu_1449_p2 <= "1" when (signed(zext_ln102_6_fu_1445_p1) < signed(bc_actual)) else "0";
    icmp_ln102_fu_850_p2 <= "1" when (signed(zext_ln99_fu_812_p1) < signed(bc_actual)) else "0";
    lshr_ln_fu_820_p4 <= ap_sig_allocacmp_j_2(5 downto 3);
    or_ln99_1_fu_1020_p3 <= (tmp_180_fu_1010_p4 & ap_const_lv2_2);
    or_ln99_2_fu_1101_p3 <= (tmp_180_fu_1010_p4 & ap_const_lv2_3);
    or_ln99_3_fu_1182_p3 <= (lshr_ln_fu_820_p4 & ap_const_lv3_4);
    or_ln99_4_fu_1271_p5 <= (((lshr_ln_fu_820_p4 & ap_const_lv1_1) & tmp_7_fu_1263_p3) & ap_const_lv1_1);
    or_ln99_5_fu_1356_p3 <= (lshr_ln_fu_820_p4 & ap_const_lv3_6);
    or_ln99_6_fu_1437_p3 <= (lshr_ln_fu_820_p4 & ap_const_lv3_7);
    or_ln_fu_929_p3 <= (tmp_179_fu_919_p4 & ap_const_lv1_1);
    tmp_171_fu_953_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_172_fu_1044_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_173_fu_1125_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_174_fu_1206_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_175_fu_1299_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_176_fu_1380_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_177_fu_1461_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_178_fu_830_p3 <= (i & lshr_ln_fu_820_p4);
    tmp_179_fu_919_p4 <= ap_sig_allocacmp_j_2(5 downto 1);
    tmp_180_fu_1010_p4 <= ap_sig_allocacmp_j_2(5 downto 2);
    tmp_7_fu_1263_p3 <= ap_sig_allocacmp_j_2(1 downto 1);
    tmp_fu_798_p3 <= ap_sig_allocacmp_j_2(6 downto 6);
    tmp_s_fu_862_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln99_fu_816_p1 <= ap_sig_allocacmp_j_2(6 - 1 downto 0);
    zext_ln102_1_fu_1028_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln99_1_fu_1020_p3),32));
    zext_ln102_2_fu_1109_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln99_2_fu_1101_p3),32));
    zext_ln102_3_fu_1190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln99_3_fu_1182_p3),32));
    zext_ln102_4_fu_1283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln99_4_fu_1271_p5),32));
    zext_ln102_5_fu_1364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln99_5_fu_1356_p3),32));
    zext_ln102_6_fu_1445_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln99_6_fu_1437_p3),32));
    zext_ln102_7_fu_838_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_178_fu_830_p3),64));
    zext_ln102_fu_937_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_929_p3),32));
    zext_ln99_fu_812_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_2),32));
end behav;
