-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flash_attention_kernel_store_stats_fp32_Pipeline_STORE_STATS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_l_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_l_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_l_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_l_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_l_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_l_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_l_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_l_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_l_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_l_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_l_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_l_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_l_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_l_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_l_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_l_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_l_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_l_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_l_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_l_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_l_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_l_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_l_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_l_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_l_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_l_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_l_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_l_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_l_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_l_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_l_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_l_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_l_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_l_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_l_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_l_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_l_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_l_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_l_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_l_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_l_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_l_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_l_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_l_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_l_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_l_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    num_elements : IN STD_LOGIC_VECTOR (31 downto 0);
    total_beats : IN STD_LOGIC_VECTOR (28 downto 0);
    sext_ln272 : IN STD_LOGIC_VECTOR (57 downto 0);
    stats_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_16_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_32_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_48_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_17_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_33_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_49_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_18_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_34_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_50_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_19_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_35_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_51_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_20_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_36_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_52_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_21_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_37_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_53_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_22_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_38_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_54_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_23_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_39_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_55_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_24_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_40_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_56_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_25_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_41_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_57_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_26_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_42_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_58_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_27_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_43_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_59_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_28_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_44_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_60_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_29_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_45_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_61_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_30_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_46_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_62_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_31_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_47_val : IN STD_LOGIC_VECTOR (31 downto 0);
    stats_63_val : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of flash_attention_kernel_store_stats_fp32_Pipeline_STORE_STATS is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv27_1 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln272_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_l_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal empty_fu_730_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_reg_1603 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal empty_58_fu_784_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_58_reg_1608 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_59_fu_838_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_59_reg_1613 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_60_fu_892_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_60_reg_1618 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_61_fu_946_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_61_reg_1623 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_62_fu_1000_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_62_reg_1628 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_63_fu_1054_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_63_reg_1633 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_64_fu_1108_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_64_reg_1638 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_65_fu_1162_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_65_reg_1643 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_66_fu_1216_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_66_reg_1648 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_67_fu_1270_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_67_reg_1653 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_68_fu_1324_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_68_reg_1658 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_69_fu_1378_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_69_reg_1663 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_70_fu_1432_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_70_reg_1668 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_71_fu_1486_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_71_reg_1673 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_72_fu_1540_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_72_reg_1678 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal b_fu_238 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    signal add_ln272_fu_664_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_b_1 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln272_fu_670_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_15_fu_684_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_fu_692_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_702_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln272_fu_680_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_702_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_fu_726_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln_fu_738_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_1_fu_746_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_756_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_756_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_1_fu_750_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_1_fu_780_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_1_fu_792_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_2_fu_800_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_810_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_810_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_2_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_2_fu_834_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_2_fu_846_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_3_fu_854_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_864_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_864_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_3_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_3_fu_888_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_3_fu_900_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_4_fu_908_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_918_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_918_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_4_fu_912_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_4_fu_942_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_4_fu_954_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_5_fu_962_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_972_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_972_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_5_fu_966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_5_fu_996_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_5_fu_1008_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_6_fu_1016_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_1026_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_1026_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_6_fu_1020_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_6_fu_1050_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_6_fu_1062_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_7_fu_1070_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_1080_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_1080_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_7_fu_1074_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_7_fu_1104_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_7_fu_1116_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_8_fu_1124_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_1134_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_1134_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_8_fu_1128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_8_fu_1158_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_8_fu_1170_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_9_fu_1178_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_1188_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_1188_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_9_fu_1182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_9_fu_1212_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_9_fu_1224_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_10_fu_1232_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_1242_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_1242_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_10_fu_1236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_10_fu_1266_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_s_fu_1278_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_11_fu_1286_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_1296_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_1296_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_11_fu_1290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_11_fu_1320_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_10_fu_1332_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_12_fu_1340_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_1350_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_1350_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_12_fu_1344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_12_fu_1374_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_11_fu_1386_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_13_fu_1394_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_1404_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_1404_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_13_fu_1398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_13_fu_1428_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_12_fu_1440_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_14_fu_1448_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_1458_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_1458_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_14_fu_1452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_14_fu_1482_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln278_13_fu_1494_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln279_15_fu_1502_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_1512_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_1512_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln279_15_fu_1506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln279_15_fu_1536_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_702_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_702_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_702_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_702_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_756_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_756_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_756_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_756_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_810_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_810_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_810_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_810_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_864_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_864_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_864_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_864_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_918_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_918_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_918_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_918_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_972_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_972_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_972_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_972_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1026_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1026_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1026_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1026_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_1080_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_1080_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_1080_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_1080_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_1134_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_1134_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_1134_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_1134_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_1188_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_1188_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_1188_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_1188_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_1242_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_1242_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_1242_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_1242_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_fu_1296_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_fu_1296_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_fu_1296_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_fu_1296_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_1350_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_1350_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_1350_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_1350_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_1404_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_1404_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_1404_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_1404_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_1458_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_1458_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_1458_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_1458_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_1512_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_1512_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_1512_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_1512_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component flash_attention_kernel_sparsemux_9_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component flash_attention_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_32_1_1_U2264 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_0_val,
        din1 => stats_16_val,
        din2 => stats_32_val,
        din3 => stats_48_val,
        def => tmp_fu_702_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_fu_702_p11);

    sparsemux_9_2_32_1_1_U2265 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_1_val,
        din1 => stats_17_val,
        din2 => stats_33_val,
        din3 => stats_49_val,
        def => tmp_7_fu_756_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_7_fu_756_p11);

    sparsemux_9_2_32_1_1_U2266 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_2_val,
        din1 => stats_18_val,
        din2 => stats_34_val,
        din3 => stats_50_val,
        def => tmp_8_fu_810_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_8_fu_810_p11);

    sparsemux_9_2_32_1_1_U2267 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_3_val,
        din1 => stats_19_val,
        din2 => stats_35_val,
        din3 => stats_51_val,
        def => tmp_9_fu_864_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_9_fu_864_p11);

    sparsemux_9_2_32_1_1_U2268 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_4_val,
        din1 => stats_20_val,
        din2 => stats_36_val,
        din3 => stats_52_val,
        def => tmp_s_fu_918_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_s_fu_918_p11);

    sparsemux_9_2_32_1_1_U2269 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_5_val,
        din1 => stats_21_val,
        din2 => stats_37_val,
        din3 => stats_53_val,
        def => tmp_1_fu_972_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_1_fu_972_p11);

    sparsemux_9_2_32_1_1_U2270 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_6_val,
        din1 => stats_22_val,
        din2 => stats_38_val,
        din3 => stats_54_val,
        def => tmp_2_fu_1026_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_2_fu_1026_p11);

    sparsemux_9_2_32_1_1_U2271 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_7_val,
        din1 => stats_23_val,
        din2 => stats_39_val,
        din3 => stats_55_val,
        def => tmp_3_fu_1080_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_3_fu_1080_p11);

    sparsemux_9_2_32_1_1_U2272 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_8_val,
        din1 => stats_24_val,
        din2 => stats_40_val,
        din3 => stats_56_val,
        def => tmp_4_fu_1134_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_4_fu_1134_p11);

    sparsemux_9_2_32_1_1_U2273 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_9_val,
        din1 => stats_25_val,
        din2 => stats_41_val,
        din3 => stats_57_val,
        def => tmp_5_fu_1188_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_5_fu_1188_p11);

    sparsemux_9_2_32_1_1_U2274 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_10_val,
        din1 => stats_26_val,
        din2 => stats_42_val,
        din3 => stats_58_val,
        def => tmp_6_fu_1242_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_6_fu_1242_p11);

    sparsemux_9_2_32_1_1_U2275 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_11_val,
        din1 => stats_27_val,
        din2 => stats_43_val,
        din3 => stats_59_val,
        def => tmp_10_fu_1296_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_10_fu_1296_p11);

    sparsemux_9_2_32_1_1_U2276 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_12_val,
        din1 => stats_28_val,
        din2 => stats_44_val,
        din3 => stats_60_val,
        def => tmp_11_fu_1350_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_11_fu_1350_p11);

    sparsemux_9_2_32_1_1_U2277 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_13_val,
        din1 => stats_29_val,
        din2 => stats_45_val,
        din3 => stats_61_val,
        def => tmp_12_fu_1404_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_12_fu_1404_p11);

    sparsemux_9_2_32_1_1_U2278 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_14_val,
        din1 => stats_30_val,
        din2 => stats_46_val,
        din3 => stats_62_val,
        def => tmp_13_fu_1458_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_13_fu_1458_p11);

    sparsemux_9_2_32_1_1_U2279 : component flash_attention_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => stats_15_val,
        din1 => stats_31_val,
        din2 => stats_47_val,
        din3 => stats_63_val,
        def => tmp_14_fu_1512_p9,
        sel => trunc_ln272_fu_680_p1,
        dout => tmp_14_fu_1512_p11);

    flow_control_loop_pipe_sequential_init_U : component flash_attention_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    b_fu_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln272_fu_674_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    b_fu_238 <= add_ln272_fu_664_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    b_fu_238 <= ap_const_lv27_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                empty_58_reg_1608 <= empty_58_fu_784_p3;
                empty_59_reg_1613 <= empty_59_fu_838_p3;
                empty_60_reg_1618 <= empty_60_fu_892_p3;
                empty_61_reg_1623 <= empty_61_fu_946_p3;
                empty_62_reg_1628 <= empty_62_fu_1000_p3;
                empty_63_reg_1633 <= empty_63_fu_1054_p3;
                empty_64_reg_1638 <= empty_64_fu_1108_p3;
                empty_65_reg_1643 <= empty_65_fu_1162_p3;
                empty_66_reg_1648 <= empty_66_fu_1216_p3;
                empty_67_reg_1653 <= empty_67_fu_1270_p3;
                empty_68_reg_1658 <= empty_68_fu_1324_p3;
                empty_69_reg_1663 <= empty_69_fu_1378_p3;
                empty_70_reg_1668 <= empty_70_fu_1432_p3;
                empty_71_reg_1673 <= empty_71_fu_1486_p3;
                empty_72_reg_1678 <= empty_72_fu_1540_p3;
                empty_reg_1603 <= empty_fu_730_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln272_fu_664_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_b_1) + unsigned(ap_const_lv27_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_l_0_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem_l_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_l_0_WREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_gmem_l_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_l_0_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem_l_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln272_fu_674_p2)
    begin
        if (((icmp_ln272_fu_674_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_b_1_assign_proc : process(ap_CS_fsm_pp0_stage0, b_fu_238, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_b_1 <= ap_const_lv27_0;
        else 
            ap_sig_allocacmp_b_1 <= b_fu_238;
        end if; 
    end process;

    bitcast_ln279_10_fu_1266_p1 <= tmp_6_fu_1242_p11;
    bitcast_ln279_11_fu_1320_p1 <= tmp_10_fu_1296_p11;
    bitcast_ln279_12_fu_1374_p1 <= tmp_11_fu_1350_p11;
    bitcast_ln279_13_fu_1428_p1 <= tmp_12_fu_1404_p11;
    bitcast_ln279_14_fu_1482_p1 <= tmp_13_fu_1458_p11;
    bitcast_ln279_15_fu_1536_p1 <= tmp_14_fu_1512_p11;
    bitcast_ln279_1_fu_780_p1 <= tmp_7_fu_756_p11;
    bitcast_ln279_2_fu_834_p1 <= tmp_8_fu_810_p11;
    bitcast_ln279_3_fu_888_p1 <= tmp_9_fu_864_p11;
    bitcast_ln279_4_fu_942_p1 <= tmp_s_fu_918_p11;
    bitcast_ln279_5_fu_996_p1 <= tmp_1_fu_972_p11;
    bitcast_ln279_6_fu_1050_p1 <= tmp_2_fu_1026_p11;
    bitcast_ln279_7_fu_1104_p1 <= tmp_3_fu_1080_p11;
    bitcast_ln279_8_fu_1158_p1 <= tmp_4_fu_1134_p11;
    bitcast_ln279_9_fu_1212_p1 <= tmp_5_fu_1188_p11;
    bitcast_ln279_fu_726_p1 <= tmp_fu_702_p11;
    empty_58_fu_784_p3 <= 
        bitcast_ln279_1_fu_780_p1 when (icmp_ln279_1_fu_750_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_59_fu_838_p3 <= 
        bitcast_ln279_2_fu_834_p1 when (icmp_ln279_2_fu_804_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_60_fu_892_p3 <= 
        bitcast_ln279_3_fu_888_p1 when (icmp_ln279_3_fu_858_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_61_fu_946_p3 <= 
        bitcast_ln279_4_fu_942_p1 when (icmp_ln279_4_fu_912_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_62_fu_1000_p3 <= 
        bitcast_ln279_5_fu_996_p1 when (icmp_ln279_5_fu_966_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_63_fu_1054_p3 <= 
        bitcast_ln279_6_fu_1050_p1 when (icmp_ln279_6_fu_1020_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_64_fu_1108_p3 <= 
        bitcast_ln279_7_fu_1104_p1 when (icmp_ln279_7_fu_1074_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_65_fu_1162_p3 <= 
        bitcast_ln279_8_fu_1158_p1 when (icmp_ln279_8_fu_1128_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_66_fu_1216_p3 <= 
        bitcast_ln279_9_fu_1212_p1 when (icmp_ln279_9_fu_1182_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_67_fu_1270_p3 <= 
        bitcast_ln279_10_fu_1266_p1 when (icmp_ln279_10_fu_1236_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_68_fu_1324_p3 <= 
        bitcast_ln279_11_fu_1320_p1 when (icmp_ln279_11_fu_1290_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_69_fu_1378_p3 <= 
        bitcast_ln279_12_fu_1374_p1 when (icmp_ln279_12_fu_1344_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_70_fu_1432_p3 <= 
        bitcast_ln279_13_fu_1428_p1 when (icmp_ln279_13_fu_1398_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_71_fu_1486_p3 <= 
        bitcast_ln279_14_fu_1482_p1 when (icmp_ln279_14_fu_1452_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_72_fu_1540_p3 <= 
        bitcast_ln279_15_fu_1536_p1 when (icmp_ln279_15_fu_1506_p2(0) = '1') else 
        ap_const_lv32_0;
    empty_fu_730_p3 <= 
        bitcast_ln279_fu_726_p1 when (icmp_ln279_fu_696_p2(0) = '1') else 
        ap_const_lv32_0;

    gmem_l_blk_n_W_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_l_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_l_blk_n_W <= m_axi_gmem_l_0_WREADY;
        else 
            gmem_l_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln272_fu_674_p2 <= "1" when (signed(zext_ln272_fu_670_p1) < signed(total_beats)) else "0";
    icmp_ln279_10_fu_1236_p2 <= "1" when (signed(zext_ln279_10_fu_1232_p1) < signed(num_elements)) else "0";
    icmp_ln279_11_fu_1290_p2 <= "1" when (signed(zext_ln279_11_fu_1286_p1) < signed(num_elements)) else "0";
    icmp_ln279_12_fu_1344_p2 <= "1" when (signed(zext_ln279_12_fu_1340_p1) < signed(num_elements)) else "0";
    icmp_ln279_13_fu_1398_p2 <= "1" when (signed(zext_ln279_13_fu_1394_p1) < signed(num_elements)) else "0";
    icmp_ln279_14_fu_1452_p2 <= "1" when (signed(zext_ln279_14_fu_1448_p1) < signed(num_elements)) else "0";
    icmp_ln279_15_fu_1506_p2 <= "1" when (signed(zext_ln279_15_fu_1502_p1) < signed(num_elements)) else "0";
    icmp_ln279_1_fu_750_p2 <= "1" when (signed(zext_ln279_1_fu_746_p1) < signed(num_elements)) else "0";
    icmp_ln279_2_fu_804_p2 <= "1" when (signed(zext_ln279_2_fu_800_p1) < signed(num_elements)) else "0";
    icmp_ln279_3_fu_858_p2 <= "1" when (signed(zext_ln279_3_fu_854_p1) < signed(num_elements)) else "0";
    icmp_ln279_4_fu_912_p2 <= "1" when (signed(zext_ln279_4_fu_908_p1) < signed(num_elements)) else "0";
    icmp_ln279_5_fu_966_p2 <= "1" when (signed(zext_ln279_5_fu_962_p1) < signed(num_elements)) else "0";
    icmp_ln279_6_fu_1020_p2 <= "1" when (signed(zext_ln279_6_fu_1016_p1) < signed(num_elements)) else "0";
    icmp_ln279_7_fu_1074_p2 <= "1" when (signed(zext_ln279_7_fu_1070_p1) < signed(num_elements)) else "0";
    icmp_ln279_8_fu_1128_p2 <= "1" when (signed(zext_ln279_8_fu_1124_p1) < signed(num_elements)) else "0";
    icmp_ln279_9_fu_1182_p2 <= "1" when (signed(zext_ln279_9_fu_1178_p1) < signed(num_elements)) else "0";
    icmp_ln279_fu_696_p2 <= "1" when (signed(zext_ln279_fu_692_p1) < signed(num_elements)) else "0";
    m_axi_gmem_l_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_l_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_l_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_l_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_l_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_l_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_l_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_l_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_l_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_l_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_l_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_l_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_l_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_l_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_l_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_l_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_l_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_l_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_l_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_l_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_l_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_l_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_l_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_l_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_l_0_BREADY <= ap_const_logic_0;
    m_axi_gmem_l_0_RREADY <= ap_const_logic_0;
    m_axi_gmem_l_0_WDATA <= (((((((((((((((empty_72_reg_1678 & empty_71_reg_1673) & empty_70_reg_1668) & empty_69_reg_1663) & empty_68_reg_1658) & empty_67_reg_1653) & empty_66_reg_1648) & empty_65_reg_1643) & empty_64_reg_1638) & empty_63_reg_1633) & empty_62_reg_1628) & empty_61_reg_1623) & empty_60_reg_1618) & empty_59_reg_1613) & empty_58_reg_1608) & empty_reg_1603);
    m_axi_gmem_l_0_WID <= ap_const_lv1_0;
    m_axi_gmem_l_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_l_0_WSTRB <= ap_const_lv64_FFFFFFFFFFFFFFFF;
    m_axi_gmem_l_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem_l_0_WVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem_l_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_l_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln278_10_fu_1332_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_C);
    or_ln278_11_fu_1386_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_D);
    or_ln278_12_fu_1440_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_E);
    or_ln278_13_fu_1494_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_F);
    or_ln278_1_fu_792_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_2);
    or_ln278_2_fu_846_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_3);
    or_ln278_3_fu_900_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_4);
    or_ln278_4_fu_954_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_5);
    or_ln278_5_fu_1008_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_6);
    or_ln278_6_fu_1062_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_7);
    or_ln278_7_fu_1116_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_8);
    or_ln278_8_fu_1170_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_9);
    or_ln278_9_fu_1224_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_A);
    or_ln278_s_fu_1278_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_B);
    or_ln_fu_738_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_1);
    tmp_10_fu_1296_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_11_fu_1350_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_12_fu_1404_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_13_fu_1458_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_14_fu_1512_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_15_fu_684_p3 <= (ap_sig_allocacmp_b_1 & ap_const_lv4_0);
    tmp_1_fu_972_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_2_fu_1026_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_3_fu_1080_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_4_fu_1134_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_5_fu_1188_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_6_fu_1242_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_7_fu_756_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_8_fu_810_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_9_fu_864_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_fu_702_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_s_fu_918_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln272_fu_680_p1 <= ap_sig_allocacmp_b_1(2 - 1 downto 0);
    zext_ln272_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_b_1),29));
    zext_ln279_10_fu_1232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_9_fu_1224_p3),32));
    zext_ln279_11_fu_1286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_s_fu_1278_p3),32));
    zext_ln279_12_fu_1340_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_10_fu_1332_p3),32));
    zext_ln279_13_fu_1394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_11_fu_1386_p3),32));
    zext_ln279_14_fu_1448_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_12_fu_1440_p3),32));
    zext_ln279_15_fu_1502_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_13_fu_1494_p3),32));
    zext_ln279_1_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_738_p3),32));
    zext_ln279_2_fu_800_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_1_fu_792_p3),32));
    zext_ln279_3_fu_854_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_2_fu_846_p3),32));
    zext_ln279_4_fu_908_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_3_fu_900_p3),32));
    zext_ln279_5_fu_962_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_4_fu_954_p3),32));
    zext_ln279_6_fu_1016_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_5_fu_1008_p3),32));
    zext_ln279_7_fu_1070_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_6_fu_1062_p3),32));
    zext_ln279_8_fu_1124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_7_fu_1116_p3),32));
    zext_ln279_9_fu_1178_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln278_8_fu_1170_p3),32));
    zext_ln279_fu_692_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_684_p3),32));
end behav;
